### PR TITLE
78629914 admin all users

### PR DESCRIPTION
**Pull request by enkanba**
First part of the feature. Although it was not stated explicitly but as I understand org page to be opened in new tab/page, so target='_blank' was added as well.

### CODE REVIEW

**Comment by tansaku** [comment]
great start @enkanba !

**Comment by enkanba** [comment]
@tansaku It turned out that there is no need to bump rails_bootstrap_sortable gem. By providing timestamp in td attribute named data-value in UTC format makes legacy string sorting work quite normal.  Merry christmas to you and your family!

**Comment by Maroo-b** [comment]
+1

**Comment by tansaku** [comment]
great work @enkanba - I'll get this merged in!

**Pull request merged**
