### PR TITLE
149069421 embedded version of map [SPIKE]

### PR DESCRIPTION
**Pull request by vardyb**
https://www.pivotaltracker.com/story/show/149069421

Work in progress to create a new embedded map view that can be displayed within an iframe on other websites.

TODO:

- [x] Implement code to allow cross origin and test
- [x] Fix map so it fills page/iframe 
- [x] Fix CSS for map popup stylings
- [x] update so only the minimal javascript files are loaded
- [x] implement tests
- [ ]  provide documentation explaining how to embed in external site

### CODE REVIEW

**Comment by vardyb** [comment]
Initial commits are only a starting point, added a layout free page `/embedded/map` with place holder for map.

**Comment by vardyb** [comment]
Latest commit now displays the map and markers, however the scripts loaded need to be reviewed and reduced to minimum required.  Currently loading all scripts for application.

**Comment by tansaku** [comment]
great start @vardyb - note that you automatically link PRs to pivotal tracker if you include certain syntax in the commit messages:

https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#git-comments

**Comment by vardyb** [comment]
@tansaku , @gnomonunes  I've added some basic tests for the embedded map page but as I'm not too familiar with cucumber would appreciate your thoughts on how to improve.

**Comment by tansaku** [comment]
@vardyb great stuff - I do see a load of fails in CI - maybe network timeout.  Does everything pass locally for you?

for reference here are the build failures:

```
  Scenario: See a volunteer opportunity and hyperlink                                        # features/volunteer_opportunities/show_volunteer_opportunity.feature:18
    Given I visit the show page for the volunteer_op titled "Office Support"                 # features/step_definitions/navigation_steps.rb:92
    Then I should see:                                                                       # features/step_definitions/basic_steps.rb:514
      | title          | description                                     | organisation              |
      | Office Support | Help with printing and copying. http://test.com | Indian Elders Association |
    And I click "Indian Elders Association" organisation link                                # features/step_definitions/navigation_steps.rb:136
      Unable to find css "#column2" (Capybara::ElementNotFound)
      ./features/step_definitions/navigation_steps.rb:141:in `/^I click "(.*)" (.*) link$/'
      features/volunteer_opportunities/show_volunteer_opportunity.feature:23:in `And I click "Indian Elders Association" organisation link'
    Then I should be on the show page for the organisation named "Indian Elders Association" # features/step_definitions/navigation_steps.rb:92
    Then I visit the show page for the volunteer_op titled "Office Support"                  # features/step_definitions/navigation_steps.rb:92
    And I click "Indian Elders Association" breadcrumb link                                  # features/step_definitions/navigation_steps.rb:136
    Then I should be on the show page for the organisation named "Indian Elders Association" # features/step_definitions/navigation_steps.rb:92
  Scenario: See URLs in volunteer opportunity pages are hyperlinked          # features/volunteer_opportunities/show_volunteer_opportunity.feature:29
    Given I visit the show page for the volunteer_op titled "Office Support" # features/step_definitions/navigation_steps.rb:92
    Then the page includes a hyperlink to "http://test.com"                  # features/step_definitions/navigation_steps.rb:192
  Scenario: See emails in volunteer opportunity pages are hyperlinked            # features/volunteer_opportunities/show_volunteer_opportunity.feature:33
    Given I visit the show page for the volunteer_op titled "Litter Box Scooper" # features/step_definitions/navigation_steps.rb:92
    Then the page includes email hyperlink "test@test.com"                       # features/step_definitions/navigation_steps.rb:197
  Scenario: See volunteer opportunity location with different address         # features/volunteer_opportunities/show_volunteer_opportunity.feature:37
    Given I visit the show page for the volunteer_op titled "Mini Bus Driver" # features/step_definitions/navigation_steps.rb:92
    Then I should see "Volunteer opportunity location: Station Rd, HA8 7BD"   # features/step_definitions/basic_steps.rb:336
  Scenario: See search form on show page                                     # features/volunteer_opportunities/show_volunteer_opportunity.feature:41
    Given I visit the show page for the volunteer_op titled "Office Support" # features/step_definitions/navigation_steps.rb:92
    Then I should see a search form                                          # features/step_definitions/volunteer_op_steps.rb:130
Failing Scenarios:
cucumber -p first_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:12 # Scenario: See a map of current doit volunteer opportunities
cucumber -p first_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:16 # Scenario: See a map of current doit and harrow volunteer opportunities
cucumber -p first_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:31 # Scenario: See a list of current doit volunteer opportunities with a link to  organisation page
cucumber -p first_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:37 # Scenario: See a list of current doit volunteer opportunities with a link to opportunity page
cucumber -p first_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:43 # Scenario: Doit volunteer opportunites are listed in map popups
cucumber -p first_try features/volunteer_opportunities/list_volunteer_opportunities.feature:18 # Scenario: See a list of current volunteer opportunities
cucumber -p first_try features/volunteer_opportunities/list_volunteer_opportunities.feature:24 # Scenario: Volunteer index page has two column layout
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:22 # Scenario Outline: See a list of local volunteer ops with same coordiantes in same maker popup, Examples (#1)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:23 # Scenario Outline: See a list of local volunteer ops with same coordiantes in same maker popup, Examples (#2)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:36 # Scenario Outline: See a list of do-it volunteer ops with same coordiantes in same maker popup, Examples (#1)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:37 # Scenario Outline: See a list of do-it volunteer ops with same coordiantes in same maker popup, Examples (#2)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:60 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#1)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:61 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#2)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:62 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#3)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:63 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#4)
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:66 # Scenario: See map when editing my volunteer opportunity
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:82 # Scenario: See map when editing my volunteer opportunity
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:87 # Scenario: Infowindow appears when mouse hovers over volunteer opportunity in table
cucumber -p first_try features/volunteer_opportunities/map_volunteer_opportunities.feature:104 # Scenario: Infowindow continues to work when mouse hovers over volunteer opportunity without long and lat values in table
cucumber -p first_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:12 # Scenario: See a map of current reachskills volunteer opportunities
cucumber -p first_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:16 # Scenario: See a map of current reachskills and harrow volunteer opportunities
cucumber -p first_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:31 # Scenario: See a list of current reachskills volunteer opportunities with a link to organisation page
cucumber -p first_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:37 # Scenario: Reachskills volunteer opportunites are listed in map popups
cucumber -p first_try features/volunteer_opportunities/show_volunteer_opportunity.feature:18 # Scenario: See a volunteer opportunity and hyperlink

```

**Comment by tansaku** [comment]
I've restarted the build ...

**Comment by tansaku** [comment]
@vardyb I am seeing those errors locally when I build your branch - looks like css errors - some subtle issue going on with routes maybe ...

**Comment by vardyb** [comment]
@tansaku I'm also seeing the same errors.  I was convinced the test were ok, but looking back at my history I was only running specific tests.  I will take another look.

**Comment by vardyb** [comment]
@tansaku - The problem was related to how I was disabling the layout for the embedded map.  I've now refactored this and all cucumber tests and passing locally for me now.

**Comment by tansaku** [comment]
fantastic work on this @vardyb - will get pushed out for further tests :-)

**Pull request merged**
