### PR TITLE
Email validations

### PR DESCRIPTION
**Pull request by tansaku**
Addresses: https://www.pivotaltracker.com/story/show/61986126

### CODE REVIEW

**Comment by tansaku** [comment]
@samover here's my command line history from doing this merge:

```
 559  git checkout samover/61986126_email_validation
  560  git merge develop
  561  bundle
  562  ber
  563  bec
  564  bec
  565  git commit -am 'merges develop'
  566  git status
  567  git checkout -b 61986126_email_validation
  568  git push origin 61986126_email_validation
  569  hub pull-request -b develop 
```

the key point was that when I merged develop I got three conflicts which I fixed in the code editor:

```
$ git merge develop
Auto-merging spec/models/base_organisation_spec.rb
CONFLICT (content): Merge conflict in spec/models/base_organisation_spec.rb
Auto-merging features/step_definitions/basic_steps.rb
CONFLICT (content): Merge conflict in features/step_definitions/basic_steps.rb
Auto-merging features/admin/admin_new_charity.feature
CONFLICT (content): Merge conflict in features/admin/admin_new_charity.feature
Automatic merge failed; fix conflicts and then commit the result.
```

the key thing was that I had my develop branch synced to the lastest upstream in order to be merging against the very latest develop code ...

**Comment by tansaku** [comment]
okay, so this build failed because of the tests removed - however I would argue that even with validations in place that one can still be working with a legacy database that has invalid data so the tests should remain ...

**Comment by tansaku** [comment]
also I notice our schema suddenly seems to be enabling a lot more pg extensions ...

**Comment by tansaku** [comment]
hmm, and putting those tests back in causes failures that would need to be analyzed, but the code coverage drop is something to be concerned about.  We can delete tests but all code paths should still be exercised - according to coveralls it's the proposed org accepting process - should combine with a bit of a cucumber clearup ...

**Comment by tansaku** [comment]
so I've been looking closely at cucumber features/admin/admin_moderate_proposed_organisations.feature:55 and it seems like rather than extensive updates of the orgs in our cukes, we could have adjusted the creation steps to do things like:

```
proposed_org.save!(validate: false)
```

to avoid validations in cases where we want to simulate the effect of working with legacy data.  Adding the above to factory_steps.rb:1 Given the following proposed organisations exist, allows us to create a proposed org with an invalid email, however, we then get a different failure when the admin accepts the org and the conversion to a full org fails ...

The test then fails because the service doesn't handle the validation failure:

```
    And having accepted the proposed organisation named "Unfriendly", I see "No invitation email was sent because the email associated with Unfriendly, xyt, seems invalid" # features/step_definitions/moderate_proposed_organisation_steps.rb:9
      Validation failed: Email is invalid (ActiveRecord::RecordInvalid)
      ./app/models/proposed_organisation.rb:5:in `accept_proposal'
      ./app/services/accept_proposed_organisation.rb:24:in `run'
      ./app/controllers/proposed_organisations_controller.rb:12:in `update'
      ./features/support/helpers.rb:76:in `/^having accepted the proposed organisation named "(.*?)", I see "(.*?)"$/'
      features/admin/admin_moderate_proposed_organisations.feature:59:in `And having accepted the proposed organisation named "Unfriendly", I see "No invitation email was sent because the email associated with Unfriendly, xyt, seems invalid"'
```

Now I guess ideally the service would handle this error and reflect back to the user?  Allow the admin to edit the email?  Is this a downside of custom services since I imagine in the absence of the service the error might just naturally bubble up (although maybe not in the relatively complex setup we have here) ...

**Comment by tansaku** [comment]
@mtc2013 @johnnymo87 any thoughts on whether it's worth pushing ahead with this, or even just sidelining it?  I'm not sure it's really delivering customer value at present ...

It starts to feel like a distraction - although cleaning it up would be good refactoring I guess ...

**Comment by johnnymo87** [comment]
I think this PR needs rebasing, but otherwise it looks good to me. Any reason we shouldn't :shipit: ?

**Comment by tansaku** [comment]
@johnnymo87 just the concerns from my previous comment

**Comment by tansaku** [comment]
so @mtc2013 and I worked on this and we managed to clean quite a lot of things up, but we got down to the point where we were looking at how the services were displaying errors to the admin user, and the deeper issue here is that the validations change the way we interact with the admin user.

In the past the validations were only on the user and so we have a set of services that can handle that an error for a user email and then pass it back up into the admin interface.

Now the validation error will occur earlier in the sequence (on the proposed organisation, or the organisation itself) and the services are not set up to pass back the new kind of error.  Our options include

1) just deleting the test (and doing some data cleaning on production db)
2) refactoring the service
3) refactoring the UX

I am conflicted about how important email validation is.  I would like to have a clean set of services and a clean UX for the proposed organisation pathway - I think that probably this needs to be done in the context of clearing the entire pathway.  

For the record, I think we now have five pathways into the system:

1) This is My Organisation (TIMO) - user requests control of an org
2) Existing organisation has no associated user - admin sends invite to org email
3) User signs up to create a user account with unknown email
4) User signs up with an email associated with an existing organisation (automatically gets control)
5) Someone proposes a new organisation (which admin can then approve or decline) (unclear if user account is created or not)

The general goal of these pathways is to have users empowered to be able to edit their organisation details

Which supports the higher goal of increasing the #users, #orgs, and ensuring all the data is up to date

**Comment by tansaku** [comment]
okay, so there's important stuff here, but the PR being open for 6 months doesn't make much sense.  The clients not demanding this functionality and while there would be some great refactoring to do here, I think we'll have to close this for the moment and see if the stories being generated by the project push us back in this direction again in the future

**Pull request closed without merging**
