### PR TITLE
Bower away, yarn in 

### PR DESCRIPTION
**Pull request by mattwr18**
Addresses https://www.pivotaltracker.com/n/projects/742821/stories/160006881

### CODE REVIEW

**Comment by mattwr18** [comment]
Will need to keep debugging this when my head is clearer @tansaku... It works locally when you do yarn install, but not when you add it to the install script or the travis.yml... It make me wonder about something I read that said if there is only one dependency it's better to install it directly https://github.com/sheerun/bower-away

**Comment by tansaku** [comment]
thanks for working on this @mattwr18 

As you've probably seen it's currently failing on CI with:

```
ERROR Sprockets::FileNotFound: couldn't find file 'google-infobox/google-infobox' with type 'application/javascript'\nChecked in these paths: 
```

we're also got some Rubocop stuff in the PR - is that related?

It seems like it's looking for the module in /home/travis/build/AgileVentures/LocalSupport/vendor/assets/bower_components

Is this all working correctly for you locally?

**Comment by tansaku** [comment]
I wonder why we aren't using the official library  https://github.com/googlemaps/v3-utility-library/tree/master/infobox ? maybe there's some good reason ... 

At least these are available on the npm network:

https://www.npmjs.com/package/google-maps-infobox
https://www.npmjs.com/package/google-maps-utility-library-v3-infobox

but of course perhaps switching infobox library will generate lots more work  ... ?

**Comment by mattwr18** [comment]
Hey @tansaku, I'm not sure if you saw cause it is two commits before, but the CI was passing when I added the JS file locally. It failed the overall build cause of code smells in infobox's js file, but I think that can be ignored on our end? 

We were pairing on Friday and we decided to have another go at getting the build to pass using yarn, but were unsuccessful and decided to move to pairing on #websiteone till I could clarify with you if there is a specific reason not to just have the js to get the infoboxes working locally. Does it make it more difficult to update, for example? 

The rubocop stuff is from when I ran `mry rubocop.yml` and I kinda expected it to be `.gitignore`d like websiteone, but then when it wasn't I shouldn't have included it. I can remove it when I clean it up. 

Also, @faithngetich brought up the fact that it seems strange to move from bower to yarn, but keep npm and that maybe this ticket could be done in conjunction with a move from npm to yarn as well?

**Comment by tansaku** [comment]
@mattwr18 wrote:

> I'm not sure if you saw cause it is two commits before, but the CI was passing when I added the JS file locally. It failed the overall build cause of code smells in infobox's js file, but I think that can be ignored on our end?

Ah, no, I didn't see that.  Yeah, we can't prioritize fixing code smells in third party libraries - ideally we'd tell codeclimate to ignore files in vendor dirs or wherever ...

> till I could clarify with you if there is a specific reason not to just have the js to get the infoboxes working locally. Does it make it more difficult to update, for example?

Yeah, although the whole bower/npm thing for LocalSupport seems rather over-engineered.  I think we basically have an app that's using a single js library that's not being updated, i.e. it's being pulled directly off github.

> Also, @faithngetich brought up the fact that it seems strange to move from bower to yarn, but keep npm and that maybe this ticket could be done in conjunction with a move from npm to yarn as well?

Yeah, which is related.  Do we actually need any of npm, yarn or bower?  Clearly moving to one consistent thing is a good idea, but what we haven't seen in this project over several years is anyone adding very many javascript libraries, i.e. none.  Unless I'm mistaken and of course that's always possible :-)

The thing we might want to do is step back and ask what's the big picture here and how will different approaches best serve the end client in the long run ...?

**Comment by tansaku** [comment]
will review during LocalSupport devops sprint

**Pull request closed without merging**
