### PR TITLE
Invite user when added as org admin

### PR DESCRIPTION
**Pull request by mtc2013**
PT: https://www.pivotaltracker.com/story/show/55253798

This feature now allows both superadmins and charity admins to invite users to the site if they do not exist to be associated with a given org; in the case of superadmins this is for any org, for charity admins just for their charity.  

We can discuss whether we want this functionality to be exposed in that way for charity admins.

### CODE REVIEW

**Comment by mtc2013** [comment]
This can be pulled in after https://github.com/AgileVentures/LocalSupport/pull/171

**Comment by mtc2013** [comment]
@tansaku ready for review

**Comment by tansaku** [comment]
Hi @mtc2013 great job getting this to work. I'm pretty sure we do also want this functionality for charity admins, but we can check with client.

Here is my general thinking out loud as I review the code on the train :-)

In manage_charity_admins.feature, "Scenario: Adding non-existent user as charity superadmin invites said user"  looks a little confused in that it seems to switch from superadmin user activity to org admin mid way through the feature and we seem to have a dummy scenario in " Scenario: Adding non-existent user as charity superadmin invites said user"

specs look good

method update_attributes_with_superadmin in organisation.rb was already in need of refactoring, and is now longer and more convoluted.  I wonder if the whole thing can't be simplified by using a nested form such as we use for creating category_organisation relations when updating the org?  Maybe the need to invite the user prevents that?  Some investigation required I think - even if that route doesn't work I think we need some refactoring before we can merge this.

Steps:
1) investigate if params can be adjusted to be using a nested form style to auto-create user
2) extract methods to ensure that we are documenting the components activities, and ensuring that each method has a single responsibility
3) see if those methods can be redistributed to other classes where they make sense to be part of the single responsibility of that class

**Comment by mtc2013** [comment]
@tansaku I've pushed some refactorings to deal with the mess in the update_attributes_with_email method.  What do you think of them so far?

**Comment by mtc2013** [comment]
@tansaku I've pushed some more changes. Make sure to synch before more detailed review tommorow.

**Comment by mtc2013** [comment]
@tansaku merged with https://github.com/AgileVentures/LocalSupport/pull/171

**Pull request merged**
