### PR TITLE
Add new reference document for contributing

### PR DESCRIPTION
**Pull request by NickSchimek**
This is a cheat sheet that summarizes the main content of the primary
contributing document.

This is here as a reference to aid developers as they contribute so that
a pull request can contain all the necessary information that will aid
our code review process.

### CODE REVIEW

**Comment by NickSchimek** [comment]
Any suggestions? Do you think this would be helpful?

**Comment by tansaku** [comment]
@NickSchimek I think this is great - the trick will be to link it into the flow through the existing documentation so folks can find it at the right time ... maybe need to link it from multiple locations ...

**Comment by NickSchimek** [comment]
@tansaku Thanks! I wasn't really sure where to add a link, but eventually decided the main contributing.md document makes the most sense. Let me know if the wording needs to be changed. 
I can't think of any other place that makes sense to add a another link. Do you have any suggestions?

**Comment by tansaku** [comment]
that's a great start - I'll merge and look for other places

**Pull request merged**
