### PR TITLE
Org cat show

### PR DESCRIPTION
**Pull request by Icicleta**
Created feature tests to show categories by the three different types. We decide use map(&:name) instead of pluck(:name) because Tom things in this case doesn't matter, I'll have a look because still I don't understand it very well. We can talk tomorrow about it.

### CODE REVIEW

**Comment by tansaku** [comment]
Thanks @icicleta and @tom.bratto

So I think you should definitely go with pluck(:name) since it avoids the & character (i.e. simpler) and @johnnymo says in https://github.com/AgileVentures/LocalSupport/pull/153  "because ... no AR models need to be initialized." implying it will generally be faster

At the moment we've got one spec failing and several other feature tests indicating that there's still a bit of work to do here.

I'm not a big fan of this cucumber step:

```
Then(/^I should see "(.*?)" within "(.*?)"$/) do |text, type|
  selector = 'first-child' if type == 'What they do'
  selector = 'nth-child(2)' if type == 'Who they help'
  selector = 'last-child' if type == 'How they help'
  within('#org-categories li:' + selector) { expect(page).to have_content text}
end
```
since we have now hard-coded our test specifically to a certain type of HTML element, i.e. 'li', which I believe makes this test rather brittle.  If we used ids we could clearly indicate which elements we wanted our category sub-types to appear in, and then one could change the type of html element without having to worry about breaking the test.   Similarly we have locked to an order where the three category sub-types have to be in a particular order which is something that is not specified by the client, so again it feels that the test is too tight.

I would love to get @sjmog's opinion here too.  I know there's a move towards avoiding addition of ids to CSS in order to support testing, but if the alternative is locking the feature test to particular HTML elements and layout, then I am strongly against that.  In seems to make eminent sense to add an id to clearly and precisely specify what the intended contents of an element are, if semantic HTML is telling is the kind of thing an element is, not what it means.  Computers can't parse HTML visually, and in order to avoid locking tests to particular HTML layouts that are likely to change, we should ensure we have ids in place to allow acceptance tests of the correct calibre.

The change in indenting to the show view are slightly distracting - they could easily go into their own pull request to make this one cleaner.  Not a critical change to make here, but something to bear in mind in the future.  Thinking about pull requests from the point of view of others interpreting them, you want to include the minimum set of files and changes necessary, reducing the burden on others reviewing the changes, and minimizing the chances for accidental knock on effects.

From my point of view, no pull request is too small.  I would much rather have 20 "easy-to-merge" pull requests with a single change in each than a single pull request consisting of 20 changes.  The only reason that multiple changes should be grouped together is when they form a single unit of work, a feature, that delivers value to the customer; and when they are in a group they should be only those items that are essential to that feature.

I'm just going to post this now to get it going.  You've got some great work here, but I'm a little confused why the rspec that checks for the new categories functionality isn't failing, and instead it's the view spec that's failing - I will investigate further.

I hope any criticism above comes across as constructive :-) that's always my intention at least :-)

**Comment by tommasobratto** [comment]
While from a point of readability pluck(:name) is definitely more readable than map(&:name), I was wondering more about the effective difference of the two methods since we just target ```org.category.what_they_do``` etc... we don't "map" through every model attribute, just the particular field we need. That said, I searched a bit more about the issue and it seems that pluck() is definitely  working on a lower level (queries a db field directly according to the [Rails doc](http://guides.rubyonrails.org/active_record_querying.html#pluck)) so it should be better anyway, I suppose.

**Comment by sjmog** [comment]
From an HTML/CSS perspective, this is a _style guide_ decision, rather than a 'best practices' one. This is the same for a lot of HTML/CSS stuff, because they were never built to be tested in this way.

My personal style guide:

1. Add `id` attributes to HTML elements so JavaScript can hook on to them:

```html
<div id="myThing">I'll show first.</div>

<script type="text/javascript">
  var myThing = document.getElementById('myThing');
  myThing.innerHTML = "I'll show now";
</script>
```

By this logic, it's **totally OK to use `id` attributes for JavaScript-led testing**. Capybara doesn't use JavaScript to tell if elements are on a page, though, so `id` doesn't seem the right attribute to use.

2. Add `class` attributes to HTML elements to tell what they are:

```html
<div class="the_thing">I'll show first.</div>

<script type="text/javascript">
  // getElementsByClassName returns an array containing the .the_thing element
  var myThing = document.getElementsByClassName("the_thing")[0];
  myThing.innerHTML = "I'll show now";
</script>
```

By this logic, **`class` is the right attribute to use for non-JavaScript testing.**

However, this approach to using classes relies on two assumptions:

- We are using [Object-Oriented CSS](http://oocss.org/);
- We are using class names to name HTML/CSS 'objects'.

There is a third route, which seems messy but is potentially better: 

3. Use a `data-testinghook` attribute like this:

```html
<div data-testinghook="myThing">I'll show first.</div>

<script type="text/javascript">
  // querySelectorAll returns an array containing the element
  var myThing = document.querySelectorAll('[data-testinghook="myThing"]')[0];
  myThing.innerHTML = "I'll show now";
</script>
```

That last one seems fairly messy, though, and it'll make your HTML look awful (which is actually not as bad as it sounds).

My 2 cents - use suggestion number 2.

@Icicleta @tansaku @tommasobratto

**Comment by tansaku** [comment]
Very interesting @sjmog.  You are saying that it's okay to grab items via id if we are doing so with JavaScript.  Capybara doesn't use JavaScript, so we shouldn't do the same with Capybara?  But both Capybara and JavaScript are navigating the DOM.  Why should the fact that Capybara is not using JavaScript make a substantive difference here?

I quite like the self-documenting aspect of the data-testinghook attribute, but doesn't the id have the big advantage that it is by necessity unique, so that we can't accidentally get a situation where the same class or data-testinghook has been applied to multiple elements?

The unambiguous nature of the ID, would seem to be a big factor here.  Also shouldn't classes be about telling html elements what style they have, rather than what they are?  Although as I reflect on it I seem to recall that CSS is completely ambivalent in terms of what mechanism we use to associate styles with HTML, e.g. we can associate a style based on ID, based on class, based on attribute, based on HTML element type.  Nothing in the fundamental workings of CSS prevents any of there.  It is a matter of convention right?

The only constraints that I am aware of are that IDs must be unique, while classes, attributes and html elements have no such restriction.  I wonder if there are any other pragmatic (rather than conventional) differences between these four that I am not aware of?  If the only constraint is that IDs must be unique then I'd see that as a strong pragmatic reason in favour of using them for capybara testing ...

**Comment by tansaku** [comment]
and as a side note, reviewing the capybara internal tests, I note that they are almost exclusively using ids and attributes in their within operations:

https://github.com/jnicklas/capybara/search?p=2&q=%22session.within%28%22&type=Code&utf8=%E2%9C%93

**Comment by sjmog** [comment]
No real difference! As stated - that's my personal style guide, and everyone needs one to avoid insanity. So long as you're consistent, you're golden.

On the CSS class use question - CSS classes shouldn't really be explicitly presentational IMO: that's a code smell. That's tying your HTML class structure to your presentation layer very tightly, and you want to keep them separate. Something like:

```html
<h1 class="pt-10 mb-20">Lovely Content</h1>

<style>
.pt-10 {
  padding-top: 10px;
}
.mb-20 {
  margin-bottom: 20px;
}
</style>
```

is a real pain in the ass when you want to be a bit responsive, or when you want things to display slightly differently. I get weird when I see classes called things like `no-display-desktop`, even though they're fairly sensible.

By comparison:

```html
<h1 class="nice-title">Lovely Content</h1>

<style>
.nice-title {
  padding-top: 10px;
  margin-bottom: 20px;
}
</style>
```

allows you to use `@media` queries to determine presentation for a component when you want to switch things up. Plus, it encourages consistent frontend layouts for all future developers.

If you follow those rules, you can usually be pretty specific about on-page elements using `class`, even if you have to chain your selector a bit (or use BEM).

But yeah, I have no problem using IDs - MDN says `id` is for use ["When linking, scripting, or styling"](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) but I don't think there's too much bother whacking in other ways of doing DOM traversal in there too. @tansaku

**Comment by tansaku** [comment]
I think the problem with DOM traversal via "h2 > ol" style selectors is that we're locking our tests (assuming we're talking about tests) to aspects of the interface that are likely to change.

The OOCS suggest we shouldn't use ids for styling:

https://github.com/stubbornella/oocss/wiki/faq#should-i-use-ids-to-style-my-content

I assume we're in agreement there.

However I think you've also mis-interpreted my comment about "shouldn't classes be about telling html elements what style they have". I'm not saying the class name should name the style per se - more that classes are about specifying aspects of presentation first and foremost?

As we both agree, we shouldn't lock elements in to particular styles, but the class is thing to hang a style on right?  As in your example:

```
<h1 class="nice-title">Lovely Content</h1>

<style>
.nice-title {
  padding-top: 10px;
  margin-bottom: 20px;
}
</style>
```

We're said that the element IS a 'nice-title', but with CSS 'nice-title' is only going to have implications for what style the element ends up with, i.e. it's all about presentation, or am I mistaken? 

Clearly one can use classes to hook javascript functionality, but we're avoiding doing that, I thought ...

And anyhow this still warns us off using classes and things for testing hooks, no?  What happens when we start to have a couple of nice-titles?  If we are testing that a unique element is in a unique place in the interface, then I think it follows that we should use unique ids as the hook to test them.

I agree that consistency in one's personal style is a must, but I'd also worry slightly if my personal style guide was inconsistent with they way in which an author intended a library to be used.

Locking capybara test code to CSS classes seems slightly dangerous to me.  I'd say ids or attributes are preferable over classes for testing hooks - wouldn't you agree?

**Comment by tansaku** [comment]
@sjmog if you ever get a chance to review my post above ^^^ I'd be very interested in your thoughts

**Pull request merged**
