### PR TITLE
Bug fix password reset error

### PR DESCRIPTION
**Pull request by Icicleta**
So far I just fixed some indentation and changed the html to don't have <div>'s without id or class, I think is a bad thing. 

I'm requesting the pull request to you have more pull requests, to you find easier you see the changes as you suggested once ;)

More to come soon!!

### CODE REVIEW

**Comment by tansaku** [comment]
@Icicleta great - pull requests early and often - that's the way!

**Comment by tansaku** [comment]
great work @icicleta

a few notes

1) I was just reading the comments at the top of the devise helper:

```
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
```

which makes me think that we should follow the instructions and move this to our application_helper?

2) I wonder if ```<div id="reset_password">``` should be <password_reset_form_fields> - or do we need the id at all (since there is a form that we can refer to and look inside ...) - I wonder what @sjmog would do ...?

3) Also, I think you compiled the assets for "show me the page", but I think we might not want to check those in.  Try deploying to heroku and see what happens ... but I think we might need to place something in .gitignore about these ...

4) it's entirely my fault for muddying the water with the "forgot my password", "reset password" discussion; but now we are back to almost how we had it before; but I think  let's properly revert and have "Forgot Your Password?" rather than "Forgot Password?".  I'm just thinking of the principle of if a user clicks on a link with some text, then the title on the page they are taken to should then have the exact same text for consistency.

Overall this is a huge improvement though.  It's exactly the kind of UX issues that are particularly important in this site given that it is targeted at non-technical users.

**Comment by tansaku** [comment]
@sjmog  how about the two following alternatives:

```
    <error_explanation>
      <ul>#{messages}</ul>
    </error_explanation>
```

```
    <div id="error_explanation">
      <!-- <h4>#{sentence}</h4> -->
      <ul>#{messages}</ul>
    </div>
```

???

**Comment by tansaku** [comment]
thanks @Icicleta will try to review this and get it merged (if possible) in the next 24 hours

**Comment by sjmog** [comment]
Hey @tansaku ! In general, we should try to avoid creating extra HTML tags. 'Semantic' as in 'semantic breakup of information', rather than 'semantic as in tells you what the component does'. For the moment, that's the W3C's advise. Just ignore everything React does.

For reference, [Devise suggest](https://github.com/plataformatec/devise/wiki/Override-devise_error_messages!-for-views) this code (I'm guessing that's where @Icicleta got the idea):

```html
<div id="error_explanation">
  <h2>#{sentence}</h2>
  <ul>#{messages}</ul>
</div>
```

**Comment by tansaku** [comment]
thanks @sjmog so from your perspective there's no sense here towards wanting to avoid divs, unless there was some other existing html5 element that was more appropriate (e.g. aside, nav etc.)

**Comment by tansaku** [comment]
@Icicleta I notice this pull request still has all the public assets in it from when you precompiled them.  Did you add them to .gitignore?  I think you'll also need to `git rm` them from this branch.

I'd very much like to look through the process of having the CSS all work for you for the show me the page functionality - but I think that will need to wait till I return the last week in August :-)

**Comment by Icicleta** [comment]
@tansaku, I have fixed it, sorry I forgot to add public/assets to .gitignore 
Now should be ok :)

**Comment by tansaku** [comment]
great thanks @Icicleta - looking pretty damn good :-)

Two things I note:

1) it seems like the Gemfile.lock is taking us back to older versions of some gems?  Maybe delete that locally and re-check out just the Gemfile.lock from the develop branch?

2) the formatting is a huge improvement but I feel like when there is a token mismatch the error message leaves something to be desired:

invalid token error message

as in it won't make much sense to the average user.  Now I don't think that's a reason not to merge this in.  Get the Gemfile.lock sorted and I think we are good to go, however I think I'll make another ticket related to this 'invalid token' error message, which I think should say something like 'reset token expired - please request a new one via the "forgot password" link'

**Comment by Icicleta** [comment]
hey @tansaku yes, I agree, I did point that at some point as even myself I wasn't sure what that means and what should I do.

About Gemfile.lock is strange as I when I pull develop I had a conflict in this file and I kept the one from develop and deleted the one from my branch. I will do as you say and see if it works.

Thanks Sam

**Comment by tansaku** [comment]
excellent work @Icicleta

**Pull request merged**
