### PR TITLE
RFC: Site admin

### PR DESCRIPTION
**Pull request by mtc2013**
This will enable a new type of user, site admin, who can be set in the backend and who can edit nonpublic fields.

### CODE REVIEW

**Comment by tansaku** [comment]
is this ready to go then @mtc2013 I guess that's what the RFC label means :-)

**Comment by mtc2013** [comment]
@tansaku I think it is ready and asked @marianmosley to review it a few days ago and she never said it wasn't ready

**Comment by tansaku** [comment]
pulling it down to look at on the train :-)

**Comment by tansaku** [comment]
nice small pull request - I have some concerns about excess logic in controllers and views as follows:

ProposedOrganisationEditsController

```ruby
   if !current_user.siteadmin?
      in_memory_edit.non_published_generally_editable_fields.each do |non_published_field|
        create_params.merge!(non_published_field => org.send(non_published_field))
      end
    end
```

looks convoluted  at least it should be 

```ruby
    unless current_user.siteadmin?
      in_memory_edit.non_published_generally_editable_fields.each do |non_published_field|
        create_params.merge!(non_published_field => org.send(non_published_field))
      end
    end
```

and wouldn't it all be much cleaner if pulled inside ProposedOrganisationEdit.  Just looking through this it makes me feel that the ProposesEdits module is more complexity than we need to get the job done here, particularly to get the job done cleanly.  Ideally any code in the controller should be reading like English

At the very least the chunk above should be in some private method

proposed_organisation_edits/_form.html.erb

```ruby
@proposed_organisation_edit.editable?(:address) || current_user.siteadmin?
```

too much logic in the view, wouldn't it make more sense to pull this into the model like so:


```ruby
@proposed_organisation_edit.editable?(:address, current_user)
```

similarly for show.html.erb

and why do we need 'allow(result).to receive_message_chain(:page, :per).and_return(result)' in org controller spec?

**Comment by mtc2013** [comment]
I've pushed some changes to address the if not to unless, the extraction into a private method and the removal of that remnant of a stub chain for kaminari.

The question on making the current_user be injected into the editable method on proposed organisation edit is a question of whether it should know about users at all.  Or if that's the business of some other piece of code.  I'll think about the options here.  What do you think?

**Comment by tansaku** [comment]
The following is an improvement:

```ruby
  def create
    org = Organisation.find(params[:organisation_id])
    create_params = params.require(:proposed_organisation_edit).permit(:address, :telephone, :postcode, :name,
      :description, :website, :postcode, :email, :donation_info).merge(organisation: org, editor: current_user)
    unless current_user.siteadmin?
      merge_in_non_published_fields org, create_params
    end
    redirect_to organisation_proposed_organisation_edit_path org, ProposedOrganisationEdit.create!(create_params)
  end
```

since it exposes the business logic a bit better, but now that it's a bit more readable I wonder why we are merging in the non-published fields if the current_user is not a siteadmin

The categories of users we have are:

1. Super Admin
2. Site Admin
3. Org Admin
4. Normal User

I'm sure I may be confused somewhere, but shouldn't we only be merging in the non-published fields IF the user is a site admin?  Either way, ultimately we should go further to remove any business logic from the controller

Regarding injecting the current user into the editable method on the proposed organisation edit, I think that proposed organisation edit should know about the user to the extent that we are moving the business logic in there.  We have a precedent in the User object, where we have methods like:

```ruby
  def can_create_volunteer_ops? org
    belongs_to?(org) || superadmin?
  end
```

Now it might be cleaner to have the business logic relating to what the user can do in a service, or in some other model, however I hope we can both agree that in general we want to avoid having that logic as combinations of boolean conditionals in the view or the controller.

I think we are being pushed towards a permissions framework like cancan or being in a position where we need to roll one of our own.  Although I also worry that the creation of additional roles like this 'siteadmin' is pushing the project in the wrong direction.  At least I worry that it's complicating things when we might be asking broader questions about what the local charities and orgs are getting out of the system.  The site admin functionality helps the client with a piece of internal bureaucracy and that's all well and good, but I worry like we are adding tech here to support a problem that could be solved with sensible internal training? e.g. give volunteers full admin access.  Well actually as I say that I kind of convince myself in the other direction - it's important to maintain the security of the site at least so that volunteers don't accidentally do something they shouldn't.

So anyway, we should definitely finish this feature, but I think we need to push back to the client to get this system in front of more end users and to be getting back more from end users about the problems that they need solving.  It feels like we've added volunteering, but haven't really followed through, partly because there's a big national site doing volunteering that we can't easily integrate with at the moment.  There's talk of adding events, discussions etc. but what I don't feel too clear on is the issues being faced by the local organisations.  Although clearly the client is in contact with these organisations.  Then again, maybe one of the central values for this site is for the client internally for them to be tracking the organisations in their area, and I shouldn't worry ...

**Comment by mtc2013** [comment]
It merges in the unpublished fields by fetching them from the model and will overwrite the create params if they have them in it.

**Comment by mtc2013** [comment]
@tansaku I've experimented with two approaches to cleaning up the view logic... one is basically what you suggested:
https://github.com/mtc2013/LocalSupport/commit/78da048afa6997cfd2cf93939c54d1dddc874d74

The other is to use a presenter pattern (not sure if this is an abuse of that pattern as I don't know enough about it yet):
https://github.com/mtc2013/LocalSupport/commit/f53b0593fb04f34a4aa0fb33832112355fe3987c

Either can be extended to cover the show view in a similar manner.  What do you think?

**Comment by tansaku** [comment]
@mtc2013 fantastic that you've tried out two alternatives here!

ProposedOrganisationEditPresenter  is nice in that it is a small class with a single responsibility

in contrast 'non_public_fields_editable_by :siteadmin' is a nice readable addition to the ProposedOrganisationEdit model, although looking through the list of different decorations on ProposedOrganisationEdit it feels like the class is taking on a lot of responsibility:

```ruby
class ProposedOrganisationEdit < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :organisation
  belongs_to :editor, :class_name => "User", :foreign_key => "user_id"
  include ProposesEdits
  proposes_edits_to :organisation
  editable_fields :address, :name, :description, :postcode, :email, :website, :telephone, :donation_info
  publish_fields_booleans ->(f) {publish_fields_map(f)}
  non_public_fields_editable_by :siteadmin
  scope :still_pending, ->{where(archived: false)}
```

although it is doing it in a very rails fashion - it does generate what feels like very readable syntax in the view:

```ruby
@proposed_organisation_edit.editable?(:address, by: current_user)
```

compared to

```ruby
 @proposed_organisation_edit_presenter.can_propose_edit?(:address)
```

from the presenter side

however it adds complexity to the ProposesEdits module, although looking at the original module method editable?

```ruby
  def editable? field
    publish_field = self.class.publish_proc.call(field)
    if instance_to_edit.respond_to? publish_field
      instance_to_edit.send(publish_field) && self.class.fields_to_edit.include?(field)
    else
      self.class.fields_to_edit.include?(field)it 
    end
  end
```

it feels like the && is misplaced.  Couldn't this all be rewritten as:


```ruby
  def editable? field
    publish_field = self.class.publish_proc.call(field)
    instance_to_edit.send(publish_field) if instance_to_edit.respond_to? publish_field
    self.class.fields_to_edit.include?(field)
  end
```

in which case there would not be such a splurge in complexity here

If we think about it in terms of responsibility the ProposesEdits module currently provides a way of extracting the logic about which fields are editable into the module so that they don't clutter up the model.  The model is still responsible for indicating which fields are editable.  The addition in this iteration is to give the model more responsibility in terms of indicating which users can edit non-public fields, but again with the logic extracted into the module - the same module in this case - one could argue that the responsibility for the logic should go to a separate module, although the functionality is clearly intertwined, and given the existing module it's much easier to embellish it than to create an additional one that has to be mixed in.

It makes me think about how ActiveRecord itself arguably breaks the single responsibility principle.  The ActiveRecord Base itself makes available lots of modules that can do lots of different things, and the subclasses (the models) can then grab the ones they need easily without becoming too bloated and unreadable.  I guess we have there the difference between a class (or module) and a model, in that models are real world entities that may (as a function of the domain) have a number of responsibilities, or at least the need to perform a variety of functions, whereas classes and modules are programming entities which should be preferably be constrained in terms of their complexity ...

Anyhow, looking at the refactored and functionality boosted editable method:

```ruby 
  def editable? field, opts = {}
    usr = opts[:by]
    publish_field = self.class.publish_proc.call(field)
    if instance_to_edit.respond_to? publish_field
      (instance_to_edit.send(publish_field) || usr.try(self.class.user_type_who_edits_non_public_fields)) && self.class.fields_to_edit.include?(field)
    else
      self.class.fields_to_edit.include?(field)
    end
  end
```

It seems like this could be condensed to 


```ruby 
  def editable? field, opts = {}
    usr = opts[:by]
    publish_field = self.class.publish_proc.call(field)
    if instance_to_edit.respond_to? publish_field
      (instance_to_edit.send(publish_field) || usr.try(self.class.user_type_who_edits_non_public_fields)) 
    end
    self.class.fields_to_edit.include?(field)
  end
```

although I am now unsure.  I am not sure what calling 'instance_to_edit.send(publish_field)' after having already checked 'instance_to_edit.respond_to? publish_field' achieves.  Surely 'instance_to_edit.send(publish_field)' will always return true in this instance?  I guess I'm maybe missing something about the logic of all this.  It doesn't seem to me that these booleans are influencing the return value - it seems like the return value is always going to be the result of 'self.class.fields_to_edit.include?(field)' independently of anything else.

It leaves me feeling that we've extracted the logic of checking which are the editable fields into a module too soon.  It's lovely to play with this rails machinery, but now we're adding another layer of complexity to meet a client need, onto something which is already complex.  Ideally we wouldn't prematurely refactor - we'd let the functionality sit in the model for a bit - wait till the clients requirements for that area settle down and then refactor once the area was stable and we were seeing some benefits for re-use elsewhere ... of course I understand that one wants to try experiments with things, but it would be nice if that could be directed with more nuance.

On that note it feels like the presenter is better at managing the complexity of the situation here.

For my own peace of mind I'd like to see the functionality operating in the model in order to better understand the process that's happening when it's refactored into the module ...

**Comment by mtc2013** [comment]
@tansaku 
If we did this:
 def editable? field
    publish_field = self.class.publish_proc.call(field)
    instance_to_edit.send(publish_field) if instance_to_edit.respond_to? publish_field
    self.class.fields_to_edit.include?(field)
  end
Then the entire boolean returned would simply be whether the field to edit is included in the generally editable fields... ie, the 'decorator' editable_fields :address  and wouldn't take heed of whether the field had a publish boolean like publish_address.

The respond_to? method call makes sure that the thing returned by the proc which you can see as a mapping between a field and its publish field value, is actually defined... ie, 

the proc is defined here:

publish_fields_booleans ->(f) {publish_fields_map(f)}

And publish_fields_map is a function defined as this:
 private
  def self.publish_fields_map field
    if field == :telephone
      :publish_phone
    else
      ('publish_' + field.to_s).to_sym
    end
  end

It takes care of the corner case where the publish field for telephone is just publish_phone rather than publish_telephone.  And it will try to define other values like publish_name which isn't a real publish_field.

**Comment by mtc2013** [comment]
@tansaku so which do we ultimately prefer?

**Comment by tansaku** [comment]
Aha, thanks for the explanation, so how about:

```ruby
  def editable? field
    editable = self.class.fields_to_edit.include?(field)
    publish_field = self.class.publish_proc.call(field)
    editable &= instance_to_edit.send(publish_field) if instance_to_edit.respond_to? publish_field
    editable
  end
```

and that would mean that we could do something like this for mixing in the user criteria

```ruby
  def editable? field
    usr = opts[:by]
    editable = self.class.fields_to_edit.include?(field)
    publish_field = self.class.publish_proc.call(field)
    if instance_to_edit.respond_to? publish_field
      is_public = instance_to_edit.send(publish_field)
      user_can_edit_private_fields = usr.try(self.class.user_type_who_edits_non_public_fields)
      editable &= is_public || user_can_edit_private_fields
    end
    editable
  end
```

which makes me want to pull out a method

```ruby
  def editable? field, opts = {}
    editable = self.class.fields_to_edit.include?(field)
    editable &= can_user_edit_this_field_if_private? self.class.publish_proc.call(field), opts[:by]
    editable
  end

  def can_user_edit_this_field_if_private? publish_field, usr
    return true unless instance_to_edit.respond_to? publish_field
    is_public = instance_to_edit.send(publish_field)
    user_can_edit_private_fields = usr.try(self.class.user_type_who_edits_non_public_fields)
    is_public || user_can_edit_private_fields
  end

```

which is more comprehensible and gets the complexity under control I think, and would lead me to lean towards this approach so that we can get the nicer readability in the view ...

although if we called ProposedOrganisationEditPresenter a ProposedOrganisationEditUser, at least in the view, the view would be more readable, for example

```erb
 <% if @proposed_organisation_edit_user.can_propose_edit?(:address)%>
```

and then the two bits of logic stay separate - I've got to the point where I'd say 'your call' in order to get it merged in and shown to the client tomorrow.  I'd still like to see the un-moduled version at some point, but I'll leave that as an exercise for myself :-)

**Comment by mtc2013** [comment]
@tansaku I've pushed some changes that push the logic into the module.  It should be ready to be pulled in tommorow.

**Comment by tansaku** [comment]
Good show - final comment - case statement in proposed organisation edit spec could just be a hash? e.g.

```ruby
{regular_user: regular_user, siteadmin: siteadmin, superadmin: superadmin}
```

**Pull request merged**
