### PR TITLE
148842249 event show[WIP]

### PR DESCRIPTION
**Pull request by StlMaris123**
Work on the show page for events

### CODE REVIEW

**Comment by tansaku** [comment]
great start @StlMaris123 - wonderful to have you working on this :-)

**Comment by tansaku** [comment]
great to see you yesterday @StlMaris123 - don't hesitate to reach out if you need anything - or want to hook up with a pair partner :-)

**Comment by StlMaris123** [comment]
Hi Sam, pair programming is a great idea

**Comment by aniansson** [comment]
Hi Sam, 
We were wondering about the design. What is preferred or how should it look like? This is what it looks like so far :)
screenshot_from_2017-10-01_18-22-32_720

**Comment by tansaku** [comment]
@aniansson - probably the best model is the existing VolunteerOps or Organisation show pages: 





It'd also be nice to get the dates/times into a more human friendly display - have you chatted to @StlMaris123 about the feature?

**Comment by tansaku** [comment]
@aniansson @StlMaris123 did my comments make sense? how is everything going?

**Comment by StlMaris123** [comment]
@tansaku , based on the attributes that we have for the event, I think the format is okay. My issue is on the failing tests since they are passing locally(on my machine)

**Comment by tansaku** [comment]
thanks @StlMaris123 looks like we have some merge conflicts we need to fix first ... do you need help with that?

**Comment by tansaku** [comment]
great work @StlMaris123 !

**Pull request merged**
