### PR TITLE
118992581 fix vol op overlap

### PR DESCRIPTION
**Pull request by Maroo-b**
WIP addresses https://www.pivotaltracker.com/story/show/118992581

cleanup and refactoring is still in progress

Screenshot:

selection_029

### CODE REVIEW

**Comment by tansaku** [comment]
@Maroo-b great that you're working on this - do you have any screenshots ?

**Comment by tansaku** [comment]
I'll try to review the architecture shortly ...

**Comment by tansaku** [comment]
okay, and so the new icon is to indicate we have more ops there ... hmm, I think we might want to leave the color the same and add a number in it - or well we need to be careful here because currently different colour icons are indicating different sources of volops ...

**Comment by tansaku** [comment]
@Maroo-b I had a quick review and I'm not sure that it makes so much sense (in terms of the domain model) for Location to have a source.  I mean a location is kind of a separate abstract entity.  I know we're getting it by looking up an address or maybe just importing from do-it (so maybe that's actually a good thing for debugging).  Are you just storing the source for reference, or switching based on the source in the location class?

Also, I was imagining that location would be an AR backed model, but you're just using a PORO here and constructing on the fly right?

**Comment by Maroo-b** [comment]
@tansaku 

for the icons I updated the legend as you can check from this screenshot:

selection_029

for the moment I'm using the same icons for multiple volunteer ops from the same source
But I added the green one when we have both Do-it and local volunteer ops in same location ( mixed sources)

Adding a number to the marker is really a good idea, maybe we should plan it as optimization after.

I added the Location class to help refactor build of grouped volunteer op hash by location ( maybe it wasn't the best move)
So I'm using this class to manage coordinates of a location and I added `source` attribute to know the source of associated list of volunteer ops in a that location. I agree that in term of domain model it drifts from the original meaning).

For the moment, the Location instances are the hash keys to grouped volunteer ops ( that's why I build them on the fly)

**Comment by Maroo-b** [comment]
@tansaku I updated the PR to add a scroll for google maps info box
Screenshot:
selection_030

**Comment by tansaku** [comment]
@Maroo-b great start - will show to client  today

**Comment by Maroo-b** [comment]
@tansaku I checked the alternative of extracting location as separate model ( which have addresse, zip code, lat and long ) the drawback of this solution is that we have to customize geocoder gem 
So for the changes that I added, it's possible to group volunteer op by location and use a hash or array which was my original code but I refactored it with value object (Location PORO) to have more readable hash keys and extract the method of building the hash from VolunteerOp model.

In this case do you suggest to remove the Location PORO and use plain Hash keys ?

**Comment by Maroo-b** [comment]
@tansaku I fixed the acceptance tests and remove source attribute from Location class.
There is a failing test https://travis-ci.org/AgileVentures/LocalSupport/builds/160195493#L2646
which passes locally can you restart travis plz ?

**Comment by tansaku** [comment]
@Maroo-b restarted

**Comment by tansaku** [comment]
thanks @Maroo-b you might want to take a look at these code climate issues on your PR: https://codeclimate.com/github/AgileVentures/LocalSupport/pull/358 let me know if any don't make sense.  Also the hound issues. 

Of course hound and code climate are automated so they don't always say the sensible thing.

I think my main concern looking at the code so far is that you are testing the new functionality at a low level, and just adjusting existing acceptance tests to fall in line.

The idea of the acceptance tests is that they are explaining in english the intended functionality of the system.  Unit tests are great, but it's often difficult to derive intentions from them.  The approach we tend to prefer is going outside in, writing our acceptance tests first and then our unit tests to support them.  I'm sensing that that's not your way :-) which is fine in principle, but I'm really hoping to have the project continue to self-document through acceptance cucumber tests.

Does that make sense?  Maybe we could pair on creating some acceptance tests some time ...?

**Comment by Maroo-b** [comment]
@tansaku for hound and codeclimate, I didn't find a way to fix the last warnings.

Regarding the acceptance tests, you are right I was thinking only about fixing the existent ones ( sort of tunnel vision) , I should add new tests.

**Comment by Maroo-b** [comment]
@tansaku I added new acceptance tests, but I had this build failure issue:
https://travis-ci.org/AgileVentures/LocalSupport/builds/161026903#L2634
which related to the folowing model spec
https://github.com/AgileVentures/LocalSupport/pull/358/files#diff-66b45f7cea4c53abf0d834625db775acR185

I'm not sure what's the issue here because locally the tests are passing is it related to instances comparison in hash values ?

**Comment by tansaku** [comment]
hmm, @Maroo-b try merging develop so we can get @johnnymo87 's rerunner in here

**Comment by Maroo-b** [comment]
@tansaku PR updated and I squashed the commits
For the moment codeclimate has some warnings


And after adding the new tests, should we keep those tests or merge them to map.feature?

**Comment by Maroo-b** [comment]
@tansaku I did some refactoring to fix codeclimate warning but still some existing code that codeclimate doesn't accept like https://github.com/AgileVentures/LocalSupport/blob/develop/app/services/build_markers_with_info_window.rb#L23

**Comment by tansaku** [comment]
@Maroo-b I took a quick look and pushed up an example of refactoring away method complexity - take a look ...

**Comment by tansaku** [comment]
See what I did here:

```rb
  def self.local_vol_op_with_coordinates
    VolunteerOp.local_only.map &:lat_lng_supplier
  end

  def lat_lng_supplier
    if vol_op.latitude && vol_op.longitude
      vol_op
    else
      vol_op.send(:with_organisation_corrdinates)
    end
  end
```
by extracting the internal clause and giving it a method name we are effectively commenting it, but in a way where the comment is very tightly tied to the new method

**Comment by tansaku** [comment]
note also that `with_organisation_corrdinates` is spelled incorrectly - should be `with_organisation_coordinates `

**Comment by Maroo-b** [comment]
@tansaku thanks for the help much appreciated, I fixed the typo in method name.

**Comment by tansaku** [comment]
thanks @Maroo-b - so does that give you a way in to fix up the remaining codeclimate issues or you need more suggestions from me?

**Comment by Maroo-b** [comment]
@tansaku the current warnings are for building the marker method which is based on gem docs https://github.com/AgileVentures/LocalSupport/pull/358/files#diff-1a52ee2183a1b2f45583d673e084183cR23 
and the second one is related to volunteer_op controller, I admit the controller require refactoring but it shouldn't be in the scope of the current feature. 

so do you prefer to include the controller refactoring in this PR ?

**Comment by tansaku** [comment]
@Maroo-b aha - if they are methods that you didn't really make many changes to them perhaps you could just make a refactoring ticket for each code climate issue and then we can merge this - vote on the others and work on them separately if you're not inspired to work on them now.

**Comment by Maroo-b** [comment]
@tansaku I created two refactoring tickets:
- https://www.pivotaltracker.com/story/show/131062023 for the build marker service
- https://www.pivotaltracker.com/story/show/131061909 for the volunteer op controller

**Pull request merged**
