### PR TITLE
149069727 adjust homepage text explain volunteering directory

### PR DESCRIPTION
**Pull request by cesswairimu**
screenshot from 2017-09-08 23-26-12

### CODE REVIEW

**Comment by tansaku** [comment]
hi @cesswairimu - many thanks for this 

I think the text:

> Harrow Community Network is a service provided by Voluntary Action Harrow Cooperative to help local residents and organisations to discover volunteer opportunities in the Harrow area.

can't really change to 

> Harrow Volunteering Opportunities is a service provided by Voluntary Action Harrow Cooperative to help local residents and organisations to discover volunteer opportunities in the Harrow area.

unless we were changing the name of the entire site to "Harrow Volunteering Opportunities" - that's a possibility, but we'd need input from the client.

What would be really great is a hyperlink to the Pivotal tracker issue in the PR description as mentioned here:

https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#pull-requests

Great to see you have this PR from a branch with the ticket id - from that I was able to find:

https://www.pivotaltracker.com/story/show/149069727

Note that you can go back and edit the description of the PR at any time :-)

Apologies from our side as the ticket is underspecified.  

@lollypop27 wants the words "Harrow Community Network" on the page and in the description for SEO purposes, but maybe the way forward for your PR is to remove the following chunk of text:

> Harrow Volunteering Opportunities is a service provided by Voluntary Action Harrow Cooperative to help local residents and organisations to discover volunteer opportunities in the Harrow area.

So we just have the big "Harrow Volunteering Opportunities" and then how to search - with the client we suspect that might make more sense to the human users of the site.

In a different PR we could look at moving the text about HCN into another location ...

**Comment by cesswairimu** [comment]
@tansaku great. Makes more sense now.  thanks

**Comment by cesswairimu** [comment]
screenshot from 2017-09-11 23-57-58
@tansaku how does this look?

**Comment by tansaku** [comment]
@cesswairimu that looks great - I might just shorten the sentence to:

> Search using a keyword in the search bar below to refine the selection of opportunities or just scroll through the list below, which has the most recently posted opportunities at the top.

I have a meeting with the client on Thursday - will show her then and get further feedback

**Comment by tansaku** [comment]
@cesswairimu just spoke to client - she said we could completely drop the explanation text

**Comment by cesswairimu** [comment]
screenshot from 2017-09-18 21-14-02
we just have this instead? @tansaku

**Comment by tansaku** [comment]
@cesswairimu yes, that's what the client seems to be suggesting ...

**Comment by cesswairimu** [comment]
@tansaku its all fine now, no description. I think we should maybe adjust the ticket to remove 'the search and browse instructions' part

**Comment by tansaku** [comment]
@cesswairimu no need to remove from ticket - we want to preserve the history - just add a note about what the customer said they wanted ...

**Comment by cesswairimu** [comment]
Home page h1 mentions its a volunteering directory [Finishes #149069727]

**Comment by tansaku** [comment]
great work @cesswairimu let's merge this in :-)

**Pull request merged**
