### PR TITLE
refactor page title tag test

### PR DESCRIPTION
**Pull request by cesswairimu**
change  the title tag step definition from 'should have a page with a title'  to 'should have a page with a title tag'

### CODE REVIEW

**Comment by tansaku** [comment]
great start @cesswairimu !

this is just what we want.  There are some issues now with some other tests.  I can see this output from travis:

```
  Scenario: Meta Title and Description for about us show page               # features/admin/seo.feature:51
    Given I am on the show page with the "aboutus" permalink                # features/step_definitions/static_pages_steps.rb:22
    And I should have a page with a title: "About Us | Harrow volunteering" # features/admin/seo.feature:53
      Undefined step: "I should have a page with a title: "About Us | Harrow volunteering"" (Cucumber::Undefined)
      features/admin/seo.feature:53:in `And I should have a page with a title: "About Us | Harrow volunteering"'
    And I should see "We are a not-for-profit"                              # features/step_definitions/basic_steps.rb:336
    And it should have a Meta Description                                   # features/step_definitions/basic_steps.rb:578
  Scenario: Meta Title and Description for disclaimer show page               # features/admin/seo.feature:63
    Given I am on the show page with the "disclaimer" permalink               # features/step_definitions/static_pages_steps.rb:22
    And I should have a page with a title: "Disclaimer | Harrow volunteering" # features/admin/seo.feature:65
      Undefined step: "I should have a page with a title: "Disclaimer | Harrow volunteering"" (Cucumber::Undefined)
      features/admin/seo.feature:65:in `And I should have a page with a title: "Disclaimer | Harrow volunteering"'
    And I should see "Ensure the information accurate"                        # features/step_definitions/basic_steps.rb:336
    And it should have a Meta Description                                     # features/step_definitions/basic_steps.rb:578
```

now that we've changed the step definition I think there are a couple of other places that also need to be changed.  Can you fix those up?  Just let me know if you need help :-)

**Comment by cesswairimu** [comment]
Yeah i see the others i will fix them

**Comment by sigu** [comment]
Good job @cesswairimu :tada: :tada:

**Comment by tansaku** [comment]
great work getting this green @cesswairimu ! :-)

**Pull request merged**
