### PR TITLE
experiments with longer wait time

### PR DESCRIPTION
**Pull request by tansaku**
Addresses https://www.pivotaltracker.com/story/show/112902301

### CODE REVIEW

**Comment by tansaku** [comment]
@decareano - here's a test for a fix for that intermittent js failure ... what frustrates me is that we don't have a reliable way of replicating.

The best guess at the moment is that the CI runs slower and so we need a longer wait time for the javascript changes (hiding the signup form) to take effect ...

**Comment by tansaku** [comment]
okay, so this passed 5 times in a row on CI - worth a merge I guess

**Comment by tansaku** [comment]
I tried to refactor the step further from:

```ruby
Given /^I sign up as "(.*?)" with password "(.*?)" and password confirmation "(.*?)"( on the legacy sign up page)?$/ do |email, password, password_confirmation, legacy|
  if legacy
    within('#new_user') do
      fill_in "user_email", :with => email
      fill_in "user_password", :with => password
      fill_in "user_password_confirmation", :with => password_confirmation
      click_button "Sign up"
    end
  else
    within('.dropdown-menu') do
      fill_in "signup_email", :with => email
      fill_in "signup_password", :with => password
      fill_in "signup_password_confirmation", :with => password_confirmation
      click_button "Sign up"
    end
    using_wait_time(10) { expect(page).not_to have_css('#signup') } if @javascript
  end
end
```

to 

```ruby
Given /^I sign up as "(.*?)" with password "(.*?)" and password confirmation "(.*?)"( on the legacy sign up page)?$/ do |email, password, password_confirmation, legacy|
  within(legacy ? '#new_user' : '.dropdown-menu') do
    fill_in "signup_email", :with => email
    fill_in "signup_password", :with => password
    fill_in "signup_password_confirmation", :with => password_confirmation
    click_button "Sign up"
  end
  using_wait_time(10) { expect(page).not_to have_css('#signup') } if @javascript and not legacy
end
```

but that seemed to reintroduce intermittent failures locally!!!

```
  @javascript @billy
  Scenario: Unregistered User Who Fails Signin Once                                                                                           # features/individual_charity_pages/this-is-my-org.feature:69
    Given I click "This is my organisation" on the "Helpful Folk" page and stay there                                                         # features/step_definitions/basic_steps.rb:411
    When I click "toggle_link"                                                                                                                # features/step_definitions/navigation_steps.rb:127
    And I sign up as "newuser@myorg.com" with password "pppppppp" and password confirmation "qppppppp"                                        # features/step_definitions/authentication_steps.rb:27
      Unable to find css ".dropdown-menu" (Capybara::ElementNotFound)
      features/individual_charity_pages/this-is-my-org.feature:72:in `And I sign up as "newuser@myorg.com" with password "pppppppp" and password confirmation "qppppppp"'
    Then I should see "Password confirmation doesn't match Password"                                                                          # features/step_definitions/basic_steps.rb:332
    And I sign up as "newuser@myorg.com" with password "pppppppp" and password confirmation "pppppppp" on the legacy sign up page             # features/step_definitions/authentication_steps.rb:27
    And I should see "A message with a confirmation link has been sent to your email address. Please open the link to activate your account." # features/step_definitions/basic_steps.rb:332
    And I should be on the show page for the organisation named "Helpful Folk"                                                                # features/step_definitions/navigation_steps.rb:87
    Then I should see "You have requested admin status for Helpful Folk"                                                                      # features/step_definitions/basic_steps.rb:332
    And "newuser@myorg.com"'s request for "Helpful Folk" should be persisted                                                                  # features/step_definitions/basic_steps.rb:427
    And I click on the confirmation link in the email to "newuser@myorg.com"                                                                  # features/step_definitions/authentication_steps.rb:133
    When I sign in as "newuser@myorg.com" with password "pppppppp" on the legacy sign in page                                                 # features/step_definitions/authentication_steps.rb:81
    Then I should be on the show page for the organisation named "Helpful Folk"                                                               # features/step_definitions/navigation_steps.rb:87
    And an email should be sent to "superadmin@localsupport.org" as notification of the request for admin status of "Helpful Folk"            # features/step_definitions/email_steps.rb:25

Failing Scenarios:
cucumber features/individual_charity_pages/this-is-my-org.feature:69 # Scenario: Unregistered User Who Fails Signin Once
```

So damn sensitive!

**Comment by decareano** [comment]
@tansaku, are you running the whole suite of cukes or testing a particular test for this PR? you already merged into develop? testing in ISOLATION or ONLINE?

**Comment by tansaku** [comment]
@decareano I believe I've run both - how about for you?  are you still getting failures?

@mtc2013 did get a failure still though the other day, while CI has been stable - we could push the timeout here to 20 secs maybe ...

**Comment by decareano** [comment]
@tansaku, sorry I have not had time. I will run the tests tonite and report back.

**Comment by decareano** [comment]
@tansaku. My results below ONLINE and OFFLINE. As you can see the randomness continues....
I noticed this: Usually, it tends to be ALL green the first time I run the suites (cukes/rspec). After that, the errors appear. 
ONLINE:
CUKES:
1st Run: ALL green
2nd Run: 2 Failures
Failing Scenarios:
`A. cucumber features/individual_charity_pages/this-is-my-org.feature:54 # Scenario: Unregistered User`
`B. cucumber features/sign_in_sign_up/sign_in.feature:56 # Scenario: Check that login/register toggle works`
3rd Run: 1 Failure
`Failing Scenarios:
cucumber features/individual_charity_pages/this-is-my-org.feature:54 # Scenario: Unregistered User`

RSPEC:
1st Run: ALL green
2nd Run: ALL green

OFFLINE: 
CUKES:
1st Run: ALL green.
2nd Run: 18 Failures (these were the typical "js_errors: false" to setup capybara to ignore these errors)
3rd Run: 1 Failure (see below)
`And I sign up as "newuser@myorg.com" with password "pppppppp" `
`and password confirmation "qppppppp"  `                                      
`# features/step_definitions/authentication_steps.rb:27`
`Unable to find css ".dropdown-menu" (Capybara::ElementNotFound)`
RSPEC:
1st Run: All green
2nd Run: All green

**Comment by tansaku** [comment]
thanks @decareano - yes, I think those are the ones we usually have problems with - I think the javascript takes longer to run on slower machines - e.g. on the CI and older laptops.

the solution may just be longer timeouts or possibly deeper investigation and re-writing of these items to be more robust.

The CI seems to have passed reliably the last 5-10 times, but you and @mtc2013 have had failures locally ...

**Comment by tansaku** [comment]
I would also say that these tests are not being influenced by the ONLINE/OFFLINE issue (IMHO) which seems to have been addressed pretty much by your work with @ZmagoD before - however you never know ... :-)

**Pull request merged**
