### PR TITLE
continues refactor of base org and org code

### PR DESCRIPTION
**Pull request by tansaku**

### CODE REVIEW

**Comment by tansaku** [comment]
@mtc2013 there's something really weird here - when I convert `not_updated_recently?` to `not_updated_recently?` suddenly the `recently_updated_and_has_owner` method in `gmaps4rails_marker_attrs` doesn't work - do you know the relation between these?

**Comment by tansaku** [comment]
ah I think I found the issue:

```
  private
    def self.add_recently_update_and_has_owner_to_enumerable(organisations)
      organisations.each do |o|
        o.instance_eval %{
            def recently_updated_and_has_owner
              !not_updated_recently? && !self.users.empty?
            end
         }
      end
      return organisations
    end
  end
```

we have metaprogramming in the house ...

**Comment by mtc2013** [comment]
Ah, I forgot about that.  I am responsible for that.  Basically we needed to augment with that method if it wasn't generated database side.

**Comment by johnnymo87** [comment]
I'd be happy to help refactor that this weekend.

**Comment by tansaku** [comment]
is metaprogramming overkill here - do we really need it to get this job done?

**Comment by tansaku** [comment]
just did a bit more to get rid of some complex boolean stuff - see what you think.  If you want to carry on refactoring maybe start on another branch building on this?  Or knock off some more bugs/fixes whatever - I'm going to keep tapping away at this until I hopefully surface through the rspec layer into the cukes :-) but I won't look at it again till Monday ...

**Comment by tansaku** [comment]
@mtc2013 @johnnymo87 @marianmosley is this good so far? shall i merge in and we'll build on this?

**Comment by johnnymo87** [comment]
+1

**Comment by mtc2013** [comment]
Looks good.

**Pull request merged**
