### PR TITLE
adds test driven draft of ListOrganisationsWithVolunteerOps service

### PR DESCRIPTION
**Pull request by tansaku**
So this is a first step to have the do-it ops stored in the DB under active record, something that @ZmagoD and I have been talking about collaborating on via Github pong over a pull request, e.g. this one! :-)

This pull request starts with creating a CRUD service to list organizations with volunteer ops for use in the volunteer_ops controller (in the first instance).  The service is isolated from any dependencies using dependency injection, so its unit tests are fast, and the service can in principle be used outside rails (?)

Removing all the do-it components makes it feel that a service could be overkill here, but let's push forward that way and see.   The complexity of build_map_markers also makes me concerned.  It's unclear to me how to straighten that out.

Anyhow, focusing on refactoring the do-it volups to use AR the next steps are probably

* [x] create migration to add source and at least url(?) to the volunteer ops table
* adjust the vol ops index controller method to pass in the correct scope depending on the feature flag setting NOT CLEAR IF NEEDED
* [x] create a task to import some do-it volunteer ops into the database (and tests for that task) 
* [x] removing the extraneous ListVolunteerOps service
* [x] cukes passing (enable passing range to import service - stick to 0.5 miles for test)
* [x] model tests for VolunteerOp 
* [x] service test for new import feature
* [x] refactoring the volunteer_ops_controller

### CODE REVIEW

**Comment by tansaku** [comment]
@johnnymo87 @Proskurina - I'd also be very interested in your thoughts on this code

**Comment by johnnymo87** [comment]
I think the meta-programming with `local_variables` is a tad bit clever, but not a big deal.

I also prefer to integration test rather than isolation test services (i.e. test with factory girl), but this project tends to reserve that for when testing through the UI ... and since our UI is simple enough, that hasn't become a problem yet ... so I guess these kinds of tests are fine, just not my cup of tea.

Overall, I agree with the intention of pulling logic out of the controller and into service layer objects.

**Comment by tansaku** [comment]
thanks @johnnymo87 - I'm having second thoughts about that `local_variables` thing

interesting also about the unit vs integration test of service objects.  The Makers folks are all over unit-testing them.  I guess you've had bad experiences with that in larger projects with more complex UI?

**Comment by ZmagoD** [comment]
Hi @tansaku I had added the migration here with 4 fields. Is there more fields we should include in the volunteer ops model?

**Comment by tansaku** [comment]
hi @ZmagoD thanks - I think we might need the following:

```ruby
    add_column :volunteer_ops, :source, :string
    add_column :volunteer_ops, :address, :string
    add_column :volunteer_ops, :postcode, :string
    add_column :volunteer_ops, :ops_url, :string
    add_column :volunteer_ops, :ops_lng, :float
    add_column :volunteer_ops, :ops_lat, :float
```
where the source will say "doit" or something - there's also an issue about how/if we store the associated organisation ... we could put the do-it org id in source for a simpler life in the first instance, although to replicate what we currently have we need the org name, hmmm

If we look at the existing service we can see the following data being extracted from the API call:

```ruby
      doit_orgs.push(OpenStruct.new(latitude: op['lat'], longitude: op['lng'],
                                    opp_name: op['title'], id: id,
                                    description: op['description'],
                                    opportunity_id: op['id'],
                                    name: op['for_recruiter']['name'],
                                    org_link: op['for_recruiter']['slug'])
```

**Comment by tansaku** [comment]
@ZmagoD have been reflecting with @mtc2013 and we think actually maybe this is the way to go:

```ruby
    add_column :volunteer_ops, :source, :string
    add_column :volunteer_ops, :doit_op_link, :string
    add_column :volunteer_ops, :doit_op_id, :string
    add_column :volunteer_ops, :doit_org_link, :string
    add_column :volunteer_ops, :doit_org_name, :string
    add_column :volunteer_ops, :ops_lng, :float
    add_column :volunteer_ops, :ops_lat, :float
```

**Comment by tansaku** [comment]
@zmagod: @mtc2013 and I have been moving to a spike to work out a general flow as this has got more and more involved.  We've discarded the service for the moment and pulled all the functionality back into the controller just to get a better handle on what's happening:

```ruby
  def index
    @volunteer_ops = VolunteerOp.order_by_most_recent
    @volunteer_ops = Feature.active?(:doit_volunteer_opportunities) ? @volunteer_ops : @volunteer_ops.local_only

    @markers = Gmaps4rails.build_markers(@volunteer_ops) do |volop, marker|
      marker.lat volop.latitude
      marker.lng volop.longitude
      marker.infowindow render_to_string(partial: "popup_#{volop.source}", locals: { org: volop })
      marker.json(
        custom_marker: render_to_string(
          partial: 'shared/custom_marker',
          locals: { attrs: [ActionController::Base.helpers.asset_path("volunteer_icon_#{volop.source}.png"),
                            'data-id' => volop.id,
                            class: 'vol_op',
                            title: "Click here to see volunteer opportunities at #{volop.title}"]}
        ),
        index: 1,
        type: 'vol_op'
      )
    end.to_json
  end
```

this is not permanent, and we'll refactor out later, but we realised we need to move to having the vol ops controller actually return vol ops and have the map work with volops rather than organisations ... we're still in the middle of the spike.

Learning a lot, but utlimately we might want to restart this once done - at the very least squash all the commits into one ... :-)  Anyway, we're definitely interested in your comments if you can make sense of our commits and/or videos :-)

**Comment by tansaku** [comment]
To clean this up we need

* [ ] cukes passing
* [ ] model tests for VolunteerOp 
* [ ] service test for new import feature
* [ ] refactoring the volunteer_ops_controller

**Comment by johnnymo87** [comment]
@tansaku Sorry for the delayed response. I apologize for being nitpicky, please don't consider my concerns to be a blocking issue, because we agree on the big picture here. These service objects are a fantastic mechanism for organizing business logic. They expose simple interfaces, which are easy to understand and reuse. What I am suggesting is that we treat these interfaces as first class citizens, and write full integration tests for them as we do for the **user** interface (and perhaps as a consequence we write fewer integration tests for the user interface). I tend to do this in rspec, although it might be more in the spirit of this project if we did it in cucumber.

**Comment by tansaku** [comment]
great point @johnnymo87 and no need to apologise, I think it's a really interesting debate, although I'm told I should debate things less :-).   @mtc2013 and I were discussing this as we paired - some rough notes on that in:

https://github.com/AgileVentures/LocalSupport/pull/267 and https://docs.google.com/document/d/12LaxWuNTJgsVsjp5Y4M2UXX4rZVBYLp-F7i4ejqYitI/edit?pref=2&pli=1

Perhaps I should write up as a blog post ...

Cucumber integration, or even "acceptance", tests of services is a really interesting idea.  The question in my mind is then do we need unit tests of the services? Can they be discarded as we discard view specs?  Perhaps not ... obviously we don't want a protracted debate to prevent us making progress on the project, but I am really interested in getting to the bottom of the relative pros and cons (and establishing a shared terminology) in order to be efficient in the long term ...

**Pull request closed without merging**
