### PR TITLE
Skip puts when in test [Fix #112406067]

### PR DESCRIPTION
**Pull request by C9905557**
Simple change to skip the 'puts' in lib/tasks/email.rake when in test.

Pivotal ticket: https://www.pivotaltracker.com/story/show/112406067

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @C9905557 

I guess you didn't like any of the other options I mentioned:

1) [stubbing the puts operation with rspec](http://stackoverflow.com/questions/15430551/suppress-console-output-during-rspec-tests)
2) directing the output to a file
3) using some other logging approach
4) introduce some dependency injection?

Your solution seems reasonable - just trying to think if there might be any downsides ... if we were using a coherent logging solution that might make more sense for the production environment, although realistically this is not something we currently run with any frequency on production, so cleaning up the test log is the priority.

In the future we might be wanting to deploy the site for other locations, or pulling in data dynamically, but both those might well be YAGNIs, so I'm tempted to just merge your fix, unless anyway wants to add an opinion ...

**Comment by C9905557** [comment]
I have no problem with any option you mentioned. Looking at the code after reading the description of the problem, this very simple solution came to my mind and I tried to apply the principle: "Write the *simple possible* code that cause this test to pass..." (but I just learn that YAGNI acronym and it amounts to the same).

But let's now apply: "developers should continuously refine a working but incomplete prototype until the **customer is happy** with the result".

I will explore the stubbing of the puts operation, since it seems the simplest for me right now. Should we ignore the output or to put it in a file somewhere?

**Comment by C9905557** [comment]
I restaured lib/task/emails.rake to its former self and I added a stub for 'puts' for the import in the test step `And I import emails from "db/email_test.csv"`. The messages are now going to the test log instead of the console, for instance:
```
  [1m[36mOrganisation Load (0.5ms)[0m  [1mSELECT "organisations".* FROM "organisations" WHERE "organisations"."type" IN ('Organisation') AND "organisations"."deleted_at" IS NULL AND (UPPER(name) LIKE '%I LOVE PEOPLE%' )[0m
[IMPORT EMAILS] I love dogs was not found
[IMPORT EMAILS] I love Cats was found
[IMPORT EMAILS] I hate animals was found
[IMPORT EMAILS] I love people was not found
  [1m[35mOrganisation Load (0.4ms)[0m  SELECT  "organisations".* FROM "organisations" WHERE "organisations"."type" IN ('Organisation') AND "organisations"."deleted_at" IS NULL AND "organisations"."name" = $1 LIMIT 1  [["name", "I love dogs"]]
```

**Comment by tansaku** [comment]
cool @C9905557 

would it make more sense for the output to always go into the log perhaps?  we could replace the puts statement with a rails logger statement? and then we might not even need to stub?

**Comment by C9905557** [comment]
We can have it in the log (development, test or production) like shown in my previous comment, by modifying the `import_emails` call in `lib/task/emails.rake` like that:
```ruby
Organisation.import_emails(args[:file],1000).split("\n").each { |msg| Rails.logger.info("[IMPORT EMAILS] #{msg}") }
```
We can also tag all the log messages produced by the import, including the ones from the database, by putting the import in a tagged block:
```ruby
Rails.logger.tagged('IMPORT EMAILS') do
  Organisation.import_emails(args[:file],1000).split("\n").each { |msg| Rails.logger.info(msg) }
end
```
then we get:
```
[IMPORT EMAILS]   [1m[35m (0.1ms)[0m  COMMIT
[IMPORT EMAILS]   [1m[36mOrganisation Load (0.9ms)[0m  [1mSELECT "organisations".* FROM "organisations" WHERE "organisations"."type" IN ('Organisation') AND "organisations"."deleted_at" IS NULL AND (UPPER(name) LIKE '%YESHIVAS HARAN%' )[0m
[IMPORT EMAILS]   [1m[35m (0.1ms)[0m  BEGIN
[IMPORT EMAILS]   [1m[36m (0.1ms)[0m  [1mCOMMIT[0m
[IMPORT EMAILS] KENTON BAPTIST CHURCH was not found
[IMPORT EMAILS] Sangat Centre was not found
[IMPORT EMAILS] 45 AID SOCIETY LIMITED was not found
[IMPORT EMAILS] HAD was not found
[IMPORT EMAILS] HARROW BEEKEEPERS' ASSOCIATION was not found
```
I find that the idea of tagging all the log messages related to the `import_emails` is nice. What do you prefer? 

By the way, if you look at the logs mainly with a text editor (vi, emacs...), the escape codes for coloring the messages on the screen (eg [1m[36m) can make the output hard to read. Coloring can be disabled in the rails config. On the other hand, if you look at the logs mainly through `tail` and `less -R`, the colors (or *colours* in UK?) look nice in the terminal.

(would be nicer/faster to talk about this, but time zones...:alarm_clock:)

**Comment by tansaku** [comment]
@C9905557 yes, tagging and logging seems like the right way to go

**Comment by tansaku** [comment]
looks great @C9905557 - many thanks!

**Pull request merged**
