### PR TITLE
name validation

### PR DESCRIPTION
**Pull request by samover**
name is now required when creating a base_organisation
complete subtask 1/5

### CODE REVIEW

**Comment by tansaku** [comment]
@samover small but perfectly formed!

**Comment by tansaku** [comment]
let's consider: https://github.com/thoughtbot/shoulda-matchers#activemodel-matchers

**Comment by tansaku** [comment]
@samover I think the way I'd like to move forward is to get this pull request (and the description one) using shoulda and get those merged in as a base and then move on to the email one ... let me know what you think

**Comment by tansaku** [comment]
@samover ah, just had a thought - perhaps we need new feature stories to cover what happens when the validations are hit by the end user ... and in fact I'm noticing a failure when running a sanity check locally:

failure when creating org with no description

**Comment by samover** [comment]
hmm, how did that creep in?
feature stories that cover an informative message that a name is required?

**Comment by tansaku** [comment]
I think that all the features now insert data that meet the requirements - we should have ensured that one feature tests the user experience when that the requirements are not met ... but may just be some messy code - I'm reverting and we'll have another look, but this is a wonderful example of why starting small is good ... also manual sanity checks :-)

**Comment by tansaku** [comment]
and yes, the feature story should cover that informative message :-)

**Pull request merged**
