### PR TITLE
52112637 - Responsive devise forms

### PR DESCRIPTION
**Pull request by nisevi**
https://www.pivotaltracker.com/story/show/52112637

### CODE REVIEW

**Comment by tansaku** [comment]
lovely thanks @nisevi - it looks good for me locally - but I'm not sure particularly which effects you are going for.

Can you provide some screenshots of the changes you're seeing locally in the interface so I can compare with mine locally?

You should be able to drop files directly into these comments in the GitHub PR

many thanks in advance :-)

**Comment by nisevi** [comment]
Hey @tansaku sure thing I will upload some screenshots :+1:

**Comment by nisevi** [comment]
route -> /users/sign_in

image

image

**Comment by nisevi** [comment]
route -> users/confirmation/new

image

image

**Comment by nisevi** [comment]
@tansaku I think that maybe the size of the font for some cases could be improved, but that can be another task :+1:

**Comment by tansaku** [comment]
thanks for the screenshots @nisevi - that makes sense - great work!

**Pull request merged**
