### PR TITLE
62111296 Client side organisation url validation (WIP)

### PR DESCRIPTION
**Pull request by samover**
Work on https://www.pivotaltracker.com/story/show/62111296

### CODE REVIEW

**Comment by tansaku** [comment]
really appreciate you pushing this up @samover - great that you have the ticket number in the title.

We're also trying to consolidate on prefixing the branch with the ticket id, so if you could rename the branch:

62111296_client_side_organization_website_validation 

that would be great (Note to self, add that to our engineering docs)

I've added a direct hyperlink to the ticket in the description (always helpful for other developers), but perhaps you can add a couple of sentences in the description to explain where you've got up to, and where you are currently stuck, if you are stuck :-)

many thanks in advance

**Comment by tansaku** [comment]
a quick review of the error suggests that we're not handling validation failures when creating proposed organisation edits:

```
    And I press "Propose this edit"                                                                          # features/step_definitions/navigation_steps.rb:121
      No route matches {:action=>"show", :controller=>"proposed_organisation_edits", :id=>#<ProposedOrganisationEdit id: nil, organisation_id: 2, name: "Unfriendly", address: "124 Pinner Road", postcode: "HA8 7TB", email: "newemail@friendly.xx", description: "Mourning loved ones", website: "http://##", telephone: "88888888", donation_info: "http://www.pleasedonate.com", deleted_at: nil, user_id: 1, created_at: nil, updated_at: nil, accepted: false, archived: false>, :organisation_id=>#<Organisation id: 2, name: "Really Friendly", address: "34 pinner road", postcode: "HA1 4HZ", email: "superadmin@friendly.xx", description: "Bereavement Counselling", website: "http://friendly.org", telephone: "020800000", created_at: "2016-01-26 10:03:14", updated_at: "2016-01-26 10:03:14", latitude: 51.5814093, longitude: -0.343908, gmaps: nil, donation_info: "http://www.donate.com", publish_address: true, publish_phone: true, publish_email: true, deleted_at: nil, type: "Organisation", non_profit: nil>} missing required keys: [:id] (ActionController::UrlGenerationError)
      ./app/controllers/proposed_organisation_edits_controller.rb:14:in `create'
      ./features/step_definitions/navigation_steps.rb:122:in `/^I press "(.*?)"$/'
      features/individual_charity_pages/proposed_organisation_edits.feature:104:in `And I press "Propose this edit"'
    Then I should see "Please enter a valid URL"                                                             # features/step_definitions/basic_steps.rb:329

Failing Scenarios:
cucumber features/individual_charity_pages/proposed_organisation_edits.feature:94 # Scenario: Propose an edit with an invalid website
```

the quick fix might be switching to create! in ProposedOrganisationEditRepository ...

**Comment by tansaku** [comment]
also, upon review the code, it looks to me like we have more in here than just client side validations.  Looks like we have server side validations as well, which we do need, but I worry that's feature creep that's making this task more challenging than it was originally.

Here's the chore for that: 

https://www.pivotaltracker.com/story/show/61986126

Maybe we need to split these two things out?  Looking forward to discussing the relative merits of different approaches with you.

**Comment by samover** [comment]
I thought by making client-side validation depend on server-side validation to make it clearer what was happening. So I did add a regex url validation. Merits: easy to expand and add server side validation and instantly have client side validation.
I found this easier to implement than solely client side validation, because of the way the two relevant controllers handled the form submissions. This made it difficult to implement 'one' validation protocol... or so I experienced :-) comments always welcome

**Comment by tansaku** [comment]
yeah, they certainly make sense to look at together - just for simplicity I might drop the client side and get the server side only working first.  Not your fault at all - we had the server side ticket blocked when you started on the client side since some others were thinking about working on it.

However, since you've started work on that and the ticket is now free you should click  start on [that ticket](https://www.pivotaltracker.com/story/show/61986126), and maybe make a pull request specific to that ticket that does not include the client side validations.  The advantages of that are:

1) pull request simpler and easy to review
2) less to wrong
3) clear match between pull request and specific ticket

Of course, if the client side validations are a trivial addition to include, then perhaps it doesn't matter too much either way, but in my experience it's good to work hard to make things into as small and simple a thing as possible.

Either way perhaps more important is whether the current error and potential fix makes sense to you?

**Comment by samover** [comment]
Now all tests are green. I did not need to add the bang to create in `proposed_organisation_edit_repository.rb` after all.
I will do as you suggest. I understand the need for clean and simple pull requests. Will work on that and work in the coming days on the other validations (should be easy from now on).



On 26 January 2016 at 13:27:48, Sam Joseph 'notifications@github.com' via 33Mail (sender@mailer1.33mail.com) wrote:

This email was sent to the alias 'github@samover.33mail.com' by 'reply@reply.github.com',
and 33Mail forwarded it to you. To block all further emails to this alias click here
(Prefer no ads? Upgrade to Premium.)

yeah, they certainly make sense to look at together - just for simplicity I might drop the client side and get the server side only working first. Not your fault at all - we had the server side ticket blocked when you started on the client side since some others were thinking about working on it.

However, since you've started work on that and the ticket is now free you should click start on that ticket, and maybe make a pull request specific to that ticket that does not include the client side validations. The advantages of that are:

1) pull request simpler and easy to review
2) less to wrong
3) clear match between pull request and specific ticket

Of course, if the client side validations are a trivial addition to include, then perhaps it doesn't matter too much either way, but in my experience it's good to work hard to make things into as small and simple a thing as possible.

Either way perhaps more important is whether the current error and potential fix makes sense to you?

—
Reply to this email directly or view it on GitHub.


This email was sent to the alias 'github@samover.33mail.com' by 'reply@reply.github.com',
and 33Mail forwarded it to you. To block all further emails to this alias click here
(Prefer no ads? Upgrade to Premium.)

**Comment by tansaku** [comment]
oh cool - great work @samover - do leave an open WIP pull request up even if not finished so that we can all follow how you're tackling things.  Really appreciate all your efforts on this and look forward to merging some of your code in soon

p.s. I just removed 62111296 from the title - the key place to get the id is in a commit message with something like "blah blah blah [Fixes #62111296]" that will auto close the relevant ticket when we merge [ref](https://blog.pivotal.io/labs/labs/level-up-your-development-workflow-with-github-pivotal-tracker)

**Pull request closed without merging**
