### PR TITLE
Fix rake setup task

### PR DESCRIPTION
**Pull request by Maroo-b**
- Override the setup task 
- fix the email import task invocation

### CODE REVIEW

**Comment by tansaku** [comment]
hi @Maroo-b thanks for this - do we want a custom name for this task - or should we prefer to override the default setup operation?

**Comment by Maroo-b** [comment]
Hi @tansaku, it seems that's there is an issue with overriding the default setup task ( it executes the listed task except the migration). That's why I changed to a custom name to avoid additional complexity.

**Comment by tansaku** [comment]
yes, I understand that - but *can* we override the default setup?  and should we?  I'm not sure - I'd like at least to investigate the pros and cons.  I haven't had time to delve into it detail ... I'm just wondering if there's an alternative where we do override the default setup (or call the default as part of this setup), and then avoid creating a new name that others are unlikely to know ...?

**Comment by Maroo-b** [comment]
@tansaku I checked this blog http://metaskills.net/2015/02/08/customizing-rake-tasks-in-rails-41-and-higher/ and some Stackoverflow answers it seems the only way to override a task is to use `clear` method like `Rake::Task['db:setup'].clear`
Currently I update the PR to override the setup task and fix merge conflicts, I'm not sure if this is the right approach but I suggest to add some note in documentation about the setup task.

**Comment by tansaku** [comment]
what about using the `enhance` method: 

http://edgar.tumblr.com/post/52300664342/how-to-extend-an-existing-rake-task

or using `before` hooks?

http://stackoverflow.com/questions/15707940/rake-before-task-hook

here's a handy reference for all the different db tasks:

http://jacopretorius.net/2014/02/all-rails-db-rake-tasks-and-what-they-do.html

I guess the question is should we be overriding `rake db:setup` and maybe the answer is no ...

maybe all of the stuff in our custom "setup" should be done from rake db:seed, but I see the nub of the problem now (which you've described already, but it's properly going in my brain now), which is that our custom "setup" calls `rake db:migrate`, whereas the default setup called `rake db:schema:load`, so perhaps having the feature elements added to the db in migrate is wrong-headed, but as I say, we can't run `db:seed` on production.

Makes me think that over-writing the default db:setup is the way to go, although we run the risk of confusing developers who think it will do the default thing - but the upside is that we maintain a swifter process of deploying feature flags, and also our heroku PR deploys might start working (although we could also get them to work by having `db:custom_setup` and calling that as a post_install operation)

**Comment by tansaku** [comment]
related:

* http://railsguides.net/change-data-in-migrations-like-a-boss/
* https://robots.thoughtbot.com/data-migrations-in-rails

hmm, perhaps we should have a feature update task instead of having features added via migrations, but then that's a separate task for each new feature, unless we have creations fail silently ... hmmm ....

**Comment by Maroo-b** [comment]
@tansaku as you said the main issue is with Feature records creation. So I checked the Feature model it seems that the features are disabled by default, as a result it's safe to create the features as disabled from the seed file (If not existent). 
=> At this point the seed file will work properly after the original setup task
To improve the existent we have the custom setup task  from this PR I suggest to update the description and add a logger to inform the developer that this setup task runs additional tasks.

Now for managing features via a task is it on priority ?, if so I suggest to create a simple task that accepts an array of features names and option (activate | deactivate ). So should we create a PT ticket for this enhancement ?

**Comment by tansaku** [comment]
Yeah, we can create features from seed file, but we *cannot* run seed on the production db, so having feature creation is the seed file is great for developers setting up locally, but not much good for deployment to the live system which has a legacy DB we can't dump date into.

Managing features via a task is one approach here  - I'd like to sleep on it before making a decision - certainly with a thoughtbot article arguing against data manipulation in migrations I'm leaning that way, but I want to reflect a bit ...  It still seems we have two options

1) override the existing setup with clear or enhance
2) pull the feature creation elements out of migrations and into task 

it would be good to list the pros and cons of each ...

**Comment by Maroo-b** [comment]
@tansaku just to confirm the current custom setup task will be used for building a test instance ? 

I vote for option 2 because:
- We can group all features in one file vs spread on different migration file.
- Task edition is easier than creating migration files just to remove and existing feature
- We can use the task for the live system and also for some test instances and we keep the original setup task 

Those points are based from some experience I had previously with migration files nightmares. 
 If you agree I'll try to create a separate PR for the task just take some time to reflect of course :)

**Comment by tansaku** [comment]
hi @Maroo-b I'm not completely sure what you mean by "the current custom setup task will be used for building a test instance", but I can say that the current custom setup task is something that any new developer will run when setting up their development instance, and can be run by anyone (including heroku automated deploys) in order to get a working version of the system.

Sleeping on it, I agree, let's go with option 2.  Re-reading the two blogs it's clear to me that we should avoid any model manipulation in migrations.  Please do create the new chores and PRs whenever you have a moment and we'll take it from there.

I'll merge this, but we need to update the installation documentation, e.g. 

https://github.com/AgileVentures/LocalSupport/wiki/OSX-installation

actually it would be great if we could consolidate our installation documentation here:

https://github.com/AgileVentures/LocalSupport/tree/develop/docs

if you've got a moment to move individual markdown files over that's great - otherwise please just edit the wiki and ensure that we have documentation movement chores - I'll hope to hit those once I've finished transcribing all this material for the AV102 course ...

**Comment by RajeevHejib** [comment]
This really is very good work.  Guess once we get it on the Installation doco it will be more clear for users.

**Comment by Maroo-b** [comment]
@tansaku I updated the installations wiki can you check them to be sure ? 
* https://github.com/AgileVentures/LocalSupport/wiki/OSX-installation
* https://github.com/AgileVentures/LocalSupport/wiki/Installation

Also I added a ticket in PT https://www.pivotaltracker.com/story/show/119065159

**Comment by tansaku** [comment]
great work @Maroo-b !

**Pull request merged**
