### PR TITLE
150247799 layout of volunteer op form is crooked

### PR DESCRIPTION
**Pull request by NickSchimek**
This implements bootstrap classes to fix alignment issues on the vol ops form. 
Fixes issue [150247799](https://www.pivotaltracker.com/story/show/150247799)

### CODE REVIEW

**Comment by NickSchimek** [comment]
hmmm. perhaps this code can be improved so that it is more readable by removing the unnecessary divs

**Comment by NickSchimek** [comment]
Here is what it looks like for me on chrome and firefox browsers. Are there other browsers we test for?
screen shot 2017-11-29 at 1 21 24 am

**Comment by tansaku** [comment]
that looks great @NickSchimek - ideally we'd test on MS browsers too, but this is a huge improvement so I'm going to pull it in :-)

**Comment by tansaku** [comment]
https://saucelabs.com/ is a great option for cross-browser testing ...

**Comment by NickSchimek** [comment]
Thanks! I checked the layout on Microsoft Edge and it looks fine. The only difference is that it doesn't have the option in the bottom corner of the description text field in order to expand the box.
vol_ops_form

**Pull request merged**
