### PR TITLE
45392619_search_local_events

### PR DESCRIPTION
**Pull request by Octopinky**
Adding feature: https://www.pivotaltracker.com/story/show/45392619

1. add the file search_local_events.feature

### CODE REVIEW

**Comment by tansaku** [comment]
great start @Octopinky and @lizkca ! :-)

**Comment by tansaku** [comment]
@Octopinky @lizkca did you say you did some more coding? want to push it up into this branch so it shows in the PR?

**Comment by lizkca** [comment]
@tansaku yes, i think we have spent more than 8 hours pair programming time on it.and still do not know when we will complete it.

**Comment by tansaku** [comment]
hi @lizkca 8 hours is a fair chunk - do you want some help? do share with us how things are progressing - is there something in particular that is challenging for you at the moment?

**Comment by tansaku** [comment]
can either of you (@Octopinky or @lizkca ) attend the group meeting tomorrow at 3:30pm UTC?

**Comment by lizkca** [comment]
yes, i think we need some kind of help.
Below is something we do not understand:
1.When we type in events/search in browser, the code at events_controller,search function sees not execute at all.It should, since we have added a line of code at the routes.rb.
The line we have add at the routes.rb:
           match 'events/search' => 'events#search', via :[:get, :post]
2. We are not sure , search function should search an event's title, or it's description, or both.
3.We have write code at event_spec.rb, but it complain that, 
  Event is not valid without a start_date
             is not valid without a end_date
             is no valid without a title
             is valid with valid attributes
             is not valid without a description.
4.We have decided that,  add a search function in the model instead of in the controller. we are not sure, it's a right decision.
5.At the pivotaltracker description, it said, "so that I can find out what's going on locally",
it seems, an event does not have a attribute to tell us if it locally or not.

**Comment by tansaku** [comment]
hi @lizkca 

1. for the routes etc. why don't you try: `get 'events/search' => 'events#search'`
 no need to use match
2. please search event title AND description
3. you will need to add the appropriate event data to the event when you set it up in event spec
4. I think the best set up would be a RESTful approach where search was actually through the index so /events?keyword=concert would ensure that we avoided a custom search route (I know we have it in other controllers, but we should remove).  The search function should be one line of code so I think leaving it in controller is okay to start with.
5. all events are by definition local, so you don't have to worry about this at the moment

I could give you much more detailed help and support in a live session - check out our free pairing offer here: https://www.agileventures.org/premium-f2f-offer

**Comment by lizkca** [comment]
ok, thanks.

**Comment by vardyb** [comment]
@Octopinky I'm getting 2 rspec failures when I run your updated code locally.

```
rspec ./spec/models/event_spec.rb:82 # Event search should not contain event that not fixs the keywod
rspec ./spec/models/event_spec.rb:64 # Event search should only contain event that fixs the keyword
```

**Comment by tansaku** [comment]
@vardyb thanks for checking - I notice there were conflicts on this branch - I fixed those just now and wonder if that will help ...

**Comment by tansaku** [comment]
@vardyb @Octopinky @lizkca I believe we fixed these two rspec errors in today's Martin Fowler scrum - we've pushed up some new code.  You should take a look.  I think the search wasn't operating as you hoped, and the tests maybe weren't checking what you wanted ...

**Comment by lizkca** [comment]
@tansaku @vardyb ok, i will look at it to see if i still need some work to finish this feature. And very appreciate both of you for spending some time on it. i think i have learned lost of things  by doing this feature.

**Comment by lizkca** [comment]
@tansaku hi @tansaku i wonder, if there a way to get the new version code after you commit the code, except to type it.(and we have done that.)

**Comment by tansaku** [comment]
@lizkca you need:

```
git pull origin 45392619_search_local_events
```

**Comment by vardyb** [comment]
@tansaku , @lizkca  I will pull the latest commits down over the weekend once I have rebuilt my LocalSupport environment to see if they pass locally on my system too.

**Comment by lizkca** [comment]
@tansaku hi Sam, some questions.
1.if i search with the keyword "ol", it will show the events that contains "older", is't this the result our client want? i am not sure about it.(should it just show the events that contains "ol"?)
2.There are lots of cache file include.should i deal with it?
3.Where's the "arel_table" come from? from rails? or other gem? i have never seen it from any rails book.

**Comment by vardyb** [comment]
@tansaku , @lizkca  I'm still getting errors locally on the  `45392619_search_local_events` branch on `Octopinky/LocalSupport`.

```
expected to find text "Some other event" in "Search Text \"The event you have searched for does not exist. Try another key word and search again.\"" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/basic_steps.rb:525:in `block (3 levels) in <top (required)>'
./features/step_definitions/basic_steps.rb:524:in `block (2 levels) in <top (required)>'
./features/step_definitions/basic_steps.rb:523:in `each'
./features/step_definitions/basic_steps.rb:523:in `/^the index should( not)? contain:$/'
features/events/search_local_events.feature:16:in `Then the index should contain:'
```

**Comment by tansaku** [comment]
@lizkca please read about cache files here: https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#acceptance-testing--caching  - ideally you will only check in a minimum of cache files, but it is very confusing and tricky :-(

and yes, partial match on words please - why don't you just precisely copy the search functionality from the organisation or volunteer_op controllers?

**Comment by lizkca** [comment]
@tansaku ok, i will spent time to rewrite it.

**Comment by lizkca** [comment]
i don't understand.  the search function in the event model, is almost the same as organisation. why organisation can partial match, but event can not partial match?

**Comment by tansaku** [comment]
@lizkca can you join the team meeting today? or book a pairing session with me?

**Comment by tansaku** [comment]
or we can set you up to pair with another team member ...

**Comment by lizkca** [comment]
@tansaku
 1.i am not sure if i can join the team meeting today. i would like to if i have time.
2.i think i will book a pairing session with you in the next week. 
3.yes, that's a good idea,  i think octopinky is very busy these days, i can not contact with her for some days.

**Comment by nisevi** [comment]
Closing this PR since its being addressed here https://github.com/AgileVentures/LocalSupport/pull/558

**Pull request closed without merging**
