### PR TITLE
Change ambiguous language in admin notification mails

### PR DESCRIPTION
**Pull request by bryszard**
Fixes PT - https://www.pivotaltracker.com/story/show/113746563

### CODE REVIEW

**Comment by tansaku** [comment]
nice simple PR @bryszard - great work.

I think we have an rspec failure blocking it though:

```
  1) admin_mailer/new_user_waiting_for_approval.html.erb should render with org name
     Failure/Error: expect(render).to have_content("There is a user waiting for superadmin approval to Friendly")
       expected to find text "There is a user waiting for superadmin approval to Friendly" in "There is a user waiting for your approval on Friendly. Please log in to the superadmin interface in order to approve or decline their request. Approve/Decline Request"
     # ./spec/views/admin_mailer/new_user_waiting_for_approval.html_spec.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by bryszard** [comment]
Done :).

**Comment by tansaku** [comment]
thanks @bryszard 

note we have a hidden error, just as in @ZmagoD 's PR that's only seen through the coverage drop:

```
  Scenario: Propose an edit with no website or donation info initially                                               # features/individual_charity_pages/proposed_organisation_edits.feature:45
    Given I visit the home page                                                                                      # features/step_definitions/navigation_steps.rb:49
    And I sign in as "registered_user-2@example.com" with password "pppppppp"                                        # features/step_definitions/authentication_steps.rb:69
    And I visit the show page for the organisation named "No website"                                                # features/step_definitions/navigation_steps.rb:89
    And I click "Propose an edit"                                                                                    # features/step_definitions/navigation_steps.rb:129
    When I propose the following edit:                                                                               # features/step_definitions/proposed_organisation_edit_steps.rb:30
      | website         | donation_info      | postcode |
      | www.newness.org | www.new.org/donate | HA1 4HZ  |
    And I press "Propose this edit"                                                                                  # features/step_definitions/navigation_steps.rb:125
    And "No website" should have the following proposed edits by user "registered_user-2@example.com":               # features/step_definitions/proposed_organisation_edit_steps.rb:46
      | website         | donation_info      | postcode |
      | www.newness.org | www.new.org/donate | HA1 4HZ  |
    Then I should be on the show organisation proposed edit page for the organisation named "No website"             # features/step_definitions/navigation_steps.rb:72
    And an email should be sent to "superadmin@harrowcn.org.uk" as notification of the proposed edit to "No website" # features/step_definitions/email_steps.rb:30
      expected `[].empty?` to return false, got true (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/email_steps.rb:10:in `/^an email should be sent to "(.*?)" as notification of the proposed edit to "(.*?)"$/'
      features/individual_charity_pages/proposed_organisation_edits.feature:58:in `And an email should be sent to "superadmin@harrowcn.org.uk" as notification of the proposed edit to "No website"'
    And the following proposed edits should be displayed on the page:                                                # features/step_definitions/proposed_organisation_edit_steps.rb:57
      | field         | current value | proposed value     |
      | donation_info |               | www.new.org/donate |
      | website       |               | www.newness.org    |
      | postcode      |               | HA1 4HZ            |
Failing Scenarios:
cucumber features/individual_charity_pages/proposed_organisation_edits.feature:45 # Scenario: Propose an edit with no website or donation info initially

```

**Comment by bryszard** [comment]
@tansaku Done again :).

**Comment by tansaku** [comment]
great work @bryszard - if you look at anything this weekend, would be great if we could sort out this confusing rake output issue: https://www.pivotaltracker.com/story/show/119350175

**Pull request merged**
