### PR TITLE
Refactored invite deleted user bug

### PR DESCRIPTION
**Pull request by Aleks4ndr**
I tried to do some refactoring of code and tests:  
1. Moved responsibiliity to purge deleted users from batch_invite_job#purge_deleted_users  to User.purge_deleted_users_where(query) model and cover it with tests (I'm not sure about tests, maybe they need mocks or using simple User models rather than FactoryGirl)
2. Refactored test in batch_invite_job to isolate it from database and User model.
3. I think that batch_invite_job#result_of_inviting  also should be moved to another class, probably to User.

### CODE REVIEW

**Comment by tansaku** [comment]
this looks pretty good @Alexs4nder - I think you just want to remove empty lines, ensure that we have a few more spaces around braces, e.g. 

```ruby
@invites.flat_map{|org_id, email| email.downcase}
```

should be

```ruby
@invites.flat_map { |org_id, email| email.downcase }
```

and get rid of that pending test.

I think factories are fine for the moment as long as the speed of the test suite is not killing us.  Using factories essentially makes things integration tests where we have a watch on whether the active record API changes out from under us.

**Comment by tansaku** [comment]
Hi @Aleks4ndr 

Thanks for this and a couple of comments

1) don't blow away your commit history with push -f - I'd much prefer that you left this history intact so others can see the full changes related to the comments
2) I think your methods might be slightly more convoluted than they need to be?

e.g. in BatchInviteJob

```ruby
  def purge_deleted_users
    User.purge_deleted_users_where(email: @invites.flat_map{ |org_id, email| email.downcase })
  end
```

could be

```ruby
  def purge_deleted_users
    User.deleted.delete(email: @invites.flat_map{ |org_id, email| email.downcase })
  end
```

or things like ```User.where(age: 20).destroy_all```, http://stackoverflow.com/questions/4177686/how-do-you-delete-in-active-record

see https://github.com/ActsAsParanoid/acts_as_paranoid#real-deletion

**Comment by tansaku** [comment]
@Aleks4ndr any thoughts on my last comment above ^^^ ?

**Comment by Aleks4ndr** [comment]
Thanks Sam. I'll change the commit

**Comment by Aleks4ndr** [comment]
Sorry for delay. I just very busy for last two weeks.
I put extracted logic in User.purge_deleted_users_where(query) because I think that there it is easier to test and modify. If all is good I'll try to do another task.

**Comment by tansaku** [comment]
this looks @Aleks4ndr

There's just a couple of minor refactorings and tweaks to the language I might make.  What do you think of the following:

```ruby
  describe '.purge_deleted_users_where' do
    subject(:do_purge) { User.purge_deleted_users_where(email: 'yes@hello.com') }
    it 'purge deleted user when user match query' do
      user = FactoryGirl.create :deleted_user, email: 'yes@hello.com'
      expect{ do_purge }.to change(User.deleted, :count).by(-1)
    end
    it 'does not delete users that is not match query' do
      user = FactoryGirl.create :deleted_user, email: 'no@hello.com'
      expect{ do_purge }.to change(User.deleted, :count).by(0)
    end
    it 'does not affect undeleted users' do
      user = FactoryGirl.create :user, email: 'yes@hello.com'
      expect{ do_purge }.to change(User, :count).by(0)
    end
  end
```

and

```ruby
  subject(:do_batch_invite) { BatchInviteJob.new(params, current_user).run }

  context 'success' do
    let(:user) { User.find_by_email org.email.downcase }

    it 'a new user is persisted' do
      expect{ do_batch_invite }.to change(User, :count).by(1)
    end

    it 'warning: email may be mutated' do
      do_batch_invite
      expect(user.email).to_not eq org.email
      expect(user.email).to eq org.email.downcase
    end

    it 'associations can be set' do
      do_batch_invite
      expect(user.organisation_id).to eq org.id
    end

    it 'sends a custom email' do
      do_batch_invite
      email = ActionMailer::Base.deliveries.last
      expect(email.from).to eq ['support@harrowcn.org.uk']
      expect(email.reply_to).to eq ['support@harrowcn.org.uk']
      expect(email.to).to eq [user.email]
      expect(email.cc).to eq ['technical@harrowcn.org.uk']
      expect(email.subject).to eq 'Welcome to Harrow Community Network!'
    end

    it 'example response for invites with duplicates' do
      expect(do_batch_invite).to eq(
        {org.id => 'Invited!',
         (org.id+1) => 'Error: Email has already been taken'}
      )
    end

    it 'resend invitations to a deleted user' do
      deleted_user = FactoryGirl.create(:deleted_user, email: 'YES@hello.com')
      valid_user = instance_double('User', errors: [])
      expect(User).to receive(:purge_deleted_users_where).with(email: ['yes@hello.com', 'yes@hello.com'])
      allow(User).to receive(:invite!).and_return(valid_user)
      do_batch_invite
    end
  end
```

hope to see you in a hangout to find a new task for you to work on :-) or just say hi in slack and we can chat there ...

**Comment by tansaku** [comment]
thanks @Aleks4ndr - looking good - something a little strange with all the dates of the commits coming after the comments - but hey - we'll look at that next time.  See you on slack ...

**Pull request merged**
