### PR TITLE
White-label root path

### PR DESCRIPTION
**Pull request by mattwr18**
- Make it possible to sprecify which part of the site we start on

Co-authored-by: Stella Njage <stellamarisnjage@gmail.com>
Co-authored-by: Cire Dia <ciremoussadia@gmail.com>

Addresses https://www.pivotaltracker.com/n/projects/742821/stories/164910558

### CODE REVIEW

**Comment by mattwr18** [comment]
works for me locally @tansaku, but it is failing the build with this output
```
ActiveRecord::NoDatabaseError: FATAL:  database "ls_test" does not exist
```
seems unrelated, but it is passing that part of the build in a subsequent `PR` I put in... :confused:

**Comment by tansaku** [comment]
hmm, so it seems like we can't easily refer to the database directly in the routes.rb file except perhaps using a [constraint based approach](https://guides.rubyonrails.org/routing.html#advanced-constraints), but that looks like it might not do what we want.

It seems like we might have to create a separate HomeController that would route the way we want I think ...

**Comment by mattwr18** [comment]
well I think using an `ENV` variable is a nice compromise

**Comment by ciremoussadia** [comment]
@mattwr18 @tansaku I feel like we're postponing the problem. Now we've some attributes related to the Setting model and another that we've to hard code on ENV vars.

**Comment by mattwr18** [comment]
I think we would like to be able to give the control of where the site roots to to the admin, but it seems that we can't create the database if set the route dynamically like `Setting.root_path`

I'm sure there are other alternatives, if you have any other ideas, let's discuss them, but also, if the person deploying  the site wants to use a different root_path, it's not unreasonable to expect they set it in the environment variables. At least, it doesn't seem like it to me.

Open to discussion though.

**Comment by ciremoussadia** [comment]
@mattwr18 what's the problem with what we did yesterday? I was working right.

**Comment by tansaku** [comment]
@ciremoussadia it worked locally, but failed in CI and we also discovered that it wouldn't work on Heroku

It works locally for us because we already have the databases in place, but it seems that accessing the database from routes.rb is going to create problems for us down the line.

The immediate need is that we can set a different home page for different instances running on different servers - an ENV variable supports that fine.

A nice to have would be a setting that could be changed by anyone with admin access, but that's not essential for our current KCSC project, so an ENV variable is just fine for now

**Comment by ciremoussadia** [comment]
@mattwr18 ok I got it.

**Pull request merged**
