### PR TITLE
[WIP] 87194714 maintain pos org list

### PR DESCRIPTION
**Pull request by enkanba**
Added attribute target='_blank' to each organization link so that it opens in new tab(or window, depending on browser used).

### CODE REVIEW

**Comment by tansaku** [comment]
@enkanba I think this is the way to go - we could also have a feature test?  not essential perhaps, but a good exercise - I think here a capybara cucumber test could express the intent well - this was a request from a real user so nice to encode that in cucumber tests

**Comment by enkanba** [comment]
@tansaku Agree, let me look into this

**Comment by enkanba** [comment]
@tansaku seems to be ready. My concern however is the use of instance variable in step definitions. Seems awkward to me. And I had to use webkit driver as default driver (selenium) doesn't support multiple window handles.

**Comment by tansaku** [comment]
@anar the test is a little brittle with the driver - we could instead test that the actual html attribute `target='_blank'` it set - that's what I usually do

**Comment by enkanba** [comment]
@tansaku Added cucumber test for target HTML attribute

**Comment by tansaku** [comment]
great work @anar !

**Pull request merged**
