### PR TITLE
extracted org_owner? logic to user model [fixes #132104697] 

### PR DESCRIPTION
**Pull request by ArbazSajid**

### CODE REVIEW

**Comment by ArbazSajid** [comment]
@enkanba I actually didn't include the superadmin condition inside the org_owner? method, it is being checked externally where the  org_owner? method is being called. I am very sorry I didn't realized that you have already worked on this, it was my first try so I was trying to go for the simplest tracker I could find.

**Comment by enkanba** [comment]
@ArbazSajid no problem, every effort is welcome here. There are plenty of things to do :) I just wanted you to know that there were some things done by @tansaku and Michael in PR#407. I guess Sam will just need to look through both and perhaps merge them.

**Comment by tansaku** [comment]
@ArbazSajid thanks and as @enkanba says we'd done some work on this already, but all effort very welcome! :-) The trick to avoid duplicated effort in future is to choose unstarted tasks from the backlog rather than those in the current column.

Notice that the ticket requesting this refactoring has been started by Anar: https://www.pivotaltracker.com/story/show/132104697  You can work on tickets in "current" but it always a good idea to reach out to whoever has started them to get the latest on what's happening with the issue :-)

You can still use this PR for your MOOC assignment of course.  And please don't hesitate to ask if you'd like additional help with the codebase or making pull requests.

**Comment by tansaku** [comment]
@ArbazSajid great work on this - I've merged in the other piece of work that @enkanba @mtc2013 and myself did previously as it highlights some of the reasons why this logic was convoluted - specifically that we have a combination of nested and non-nested routes.  That maybe something we need to address to make things simpler.

There's also the question of whether we should be using the existing `can_edit?` method or a new one like `org_owner?`.  There might be an argument for further refactorings ...

In the meantime I'll close this out, but will be very pleased to have you submit more :-)

**Pull request closed without merging**
