### PR TITLE
Increase DoIt Ops Radius Refactoring

### PR DESCRIPTION
**Pull request by tansaku**
Addresses https://www.pivotaltracker.com/story/show/113613673

* [x] refactor controller
* [x] create task for test of map icon tooltip

### CODE REVIEW

**Comment by tansaku** [comment]
Hi @ZmagoD apologies if you were hoping to work on this more - @mtc2013 and I kind of had a binge and we've kind of done it.   We also rebased the spike.  That means you're commit isn't in there per se.  We set it to @mtc2013 is the author and I am the committer - we could rebase again and pull your single commit back in so you get credit.

Sorry we weren't thinking about that as we ran through the rebase the first time.  Could sort that for you, but have just got to the end of the week and wanted to get the whole thing up in a single clean form.

Your eyes and thoughts on the code would be very much appreciated :-)

**Comment by tansaku** [comment]
aha @ZmagoD was able to pull in your commit via cherry picking - so you get credit yay!

**Comment by ZmagoD** [comment]
No problem @tansaku I was more or less offline for the last two weeks and when start to working on this I didn't know where to start. It will be really nice to pair with somebody on that.

**Comment by tansaku** [comment]
@ZmagoD yeah, with this as a base several subsequent features should be much more straightforward - hoping we can find you some pairing time with @mtc2013 @marianmosley or anyone else with time @decareano? @RajeevHejib ?

**Comment by tansaku** [comment]
also some notes arising from some of the things @mtc2013 and I were discussing when working on this, particularly the concept of **"Only Mock what you Own"**:

some interesting links I was reading:

* http://stackoverflow.com/questions/1906344/should-you-only-mock-types-you-own
* https://blog.8thlight.com/eric-smith/2011/10/27/thats-not-yours.html
* http://stackoverflow.com/questions/4277818/should-rails-units-tests-hit-database-or-not
* http://david.heinemeierhansson.com/2014/slow-database-test-fallacy.html
* https://blog.pivotal.io/labs/labs/testing-strategies-with-rspec

After reading all these I was thinking, we do own VolunteerOp, we created it and the service.  We didn't create the find_by method though ...

Here's the text from "Growing OOS":

> When we use third-party code we often do not have a deep understanding of how it works. Even if we have the source available, we rarely have time to read it thoroughly enough to explore all its quirks. We can read its documentation, which is often incomplete or incorrect. The software may also have bugs that we will need to work around. So, although we know how we want our abstraction to behave, we don’t know if it really does so until we test it in combination with the third-party code. We also prefer not to change third-party code, even when we have the sources. It’s usually too much trouble to apply private patches every time there’s a new version. If we can’t change an API, then we can’t respond to any design feedback we get from writing unit tests that touch it. Whatever alarm bells the unit tests might be ringing about the awkwardness of an external API, we have to live with it as it stands. This means that providing mock implementations of third-party types is of limited use when unit-testing the objects that call them. We find that tests that mock external libraries often need to be complex to get the code into the right state for the functionality we need to exercise. The mess in such tests is telling us that the design isn’t right but, instead of fixing the problem by improving the code, we have to carry the extra complexity in both code and test. A second risk is that we have to be sure that the behavior we stub or mock matches what the external library will actually do. How difficult this is depends on the quality of the library—whether it’s specified (and implemented) well enough for us to be certain that our unit tests are valid. Even if we get it right once, we have to make sure that the tests remain valid when we upgrade the libraries.

I'm not sure if when they say "types" that extends to objects and methods, or just objects ...

p.s. perhaps we should be simplifying our services interaction with VolunteerOp with:

```ruby
VolunteerOp.find_or_create_by(doit_op_id: volop[:id])
```

**Comment by tansaku** [comment]
@mtc2013 interesting that we lost some coverage here - possibly the loss of that view spec, but maybe something else.  I wonder if we should have our acceptance tests contributing to code coverage ...

**Pull request merged**
