### PR TITLE
deleting a user causes a problem with edits they may have proposed

### PR DESCRIPTION
**Pull request by ZmagoD**
https://www.pivotaltracker.com/story/show/112145095

I added the check if the @proposed_organisation_edit.editor exists.

### CODE REVIEW

**Comment by tansaku** [comment]
excellent @ZmagoD you've got a minor error in the commit message - do you want to use `git commit --amend` to fix that and perhaps add [Fixes #112145095] to the end of the commit message, which will automatically finish the pivotal tracker story when we merge?

Also we're following a new pattern of prefixing all branches with the pivotal ticket ID - don't worry about that for this one, but a good habit to get into --> I really need to write up some LocalSupport engineering practices ...

**Comment by ZmagoD** [comment]
@tansaku Ok!

**Comment by tansaku** [comment]
@ZmagoD do you want to use git commit --amend to fix that and perhaps add [Fixes #112145095] to the end of the commit message, which will automatically finish the pivotal tracker story when we merge?

**Comment by ZmagoD** [comment]
@tansaku done

**Comment by tansaku** [comment]
great work @ZmagoD !

**Pull request merged**
