### PR TITLE
Remove Pages Helper

### PR DESCRIPTION
**Pull request by rachaelkiteme**
The module app/helpers/pages_helper.rb was created but is not being used anywhere and it should be removed.

### CODE REVIEW

**Comment by nisevi** [comment]
@rachaelkiteme hi there would you like to give me your email in order to add you to Pivotal Tracker? :+1:

**Comment by rachaelkiteme** [comment]
Hi,

Yes @nicolassebastianvidal I would really appreciate that, My email is
rachaelrirrie@gmail.com

Thanks in advance.

Regards
Rachael

**Comment by nisevi** [comment]
@rachaelkiteme I have added you as a member on Pivotal Tracker :+1:

**Comment by rachaelkiteme** [comment]
Thank you so much Nicolas I appreciate.

Regards
Rachael

**Comment by sigu** [comment]
@rachaelkiteme I would appreciate it also if you joined our slack instance for ease of communication.  Visit our website at agileventure.org and sign up for an account, you will receive an email inviting you to our slack. If this does not work then we are happy to send you an invite directly using your email address

**Comment by rachaelkiteme** [comment]
Hello Nicolas,
Got this notification ..You were added as a story owner to remove expedited
SSL logo as no longer used
<https://www.pivotaltracker.com/story/show/153282531> , and therefore I
need your help.
Where specifically can I find file containing that expedited SSL logo. Will
be grateful for your assistance.


Regards
Rachael

**Pull request merged**
