### PR TITLE
Fixed problem with dissapearing categories [Fixes #113527215]

### PR DESCRIPTION
**Pull request by bryszard**
Works with the issue - https://www.pivotaltracker.com/story/show/113527215.

The work is still in progress. Especially because there are some specs that are failing (how do I label pull request as Work in Progress?).

I tried not to change the code too much. Nevertheless, I'm not sure if some parts of the code from views and controller shouldn't be moved to the lower level (from views to controller or model).

On my local page though it is working (at least on new template) - categories don't dissapear when user enters invalid data and validation doesn't pass.

### CODE REVIEW

**Comment by bryszard** [comment]
I should be able to brush up on this tomorrow (I think I know what to do), unless you want me to change it totally :).

**Comment by tansaku** [comment]
hi @bryszard - great work getting a spike of this working!  That's awesome :-)

for marking as work in progress you can put "WIP" as a prefix on the title - or you can ask me to add a WIP tag (which I've done).

Great idea not changing too much code - although I think you are right that there is refactoring required - as you say, pulling logic out of views/controllers and into models/services.

I've reviewing your code locally, and part of the solution here may be simply deleting view and controller specs, since I am now convinced that they are an excuse to leave logic in views and controllers and are not adding much benefit over our high level acceptance tests.

More seriously a bunch of acceptance tests, but they seem to be related to the same things that the specs are failing on, e.g.

```
undefined local variable or method `slctd' for #<#<Class:0x007fc88b2c11a8>:0x007fc88e5406d8>
Did you mean?  select (NameError)
./app/views/organisations/_form.html.erb:1:in `_app_views_organisations__form_html_erb___1657042475436161041_70249704626720'
./app/views/organisations/edit.html.erb:1:in `_app_views_organisations_edit_html_erb__1913434589097540628_70249704610060'
features/admin/admin_edit_charity.feature:21:in `And I update "Friendly" charity address to be "30 pinner road"'
```

I can confirm that the spike works for me locally, i.e. organisations that fail validations maintain the user category selections (I note we need a similar fix for proposed organisations).  You're working with the grain of the bigger category hack, which is fair enough.  There's still the open question of whether there's a cleaner rails solution to the whole multiple category with associated model thing ...

Locally I've been able to fix all the tests with a couple of minor changes - if you give me access to your repo I could push those over to you - or would you like to try figure them out for yourself?  :-)

Either way do have a look at the houndci suggestions.  You're not required to do everything it says since it's an automated system and not to be 100% trusted as regards code quality, and sometimes it's picking up on things that you didn't introduce, but still good to understand where it's coming from.

Let's see if we can knock this into shape and then look at a refactoring strategy.

**Comment by bryszard** [comment]
Sure, with your help it will be faster, that's my repos url - https://ide.c9.io/bryszard1/local-support.

**Comment by tansaku** [comment]
thanks - I didn't mean your c9 - I meant you giving me collaborator access to https://github.com/bryszard/LocalSupport so that I can push my local fixes directly to your branch - does that make sense?

https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by bryszard** [comment]
@tansaku: Sorry, I misunderstood :).

Anyway, I don't quite understand the decrease in test coverage - I didn't change anything in files that are shown as red.

**Comment by tansaku** [comment]
yes, we can look at test coverage together - will you join the standup today? it's in 30 mins ...

The other thing that we will need is an acceptance test that will actually test t his new functionality - that may help with test coverage ...

**Comment by bryszard** [comment]
Yes, I'll be on the standup. See you there!

**Comment by tansaku** [comment]
actually it looks like there was a js fail in the build (which travis didn't pass on) which will screw with the test coverage output - I've restarted the build ...

**Pull request closed without merging**
