### PR TITLE
adds support for gmaps api key

### PR DESCRIPTION
**Pull request by tansaku**
addresses https://www.pivotaltracker.com/n/projects/742821/stories/127408139

### CODE REVIEW

**Comment by tansaku** [comment]
so some complications here in that we are relying on the .env for airbrake config, which is not ideal - @Maroo-b we should probably move airbrake config into a rails settings setup like we have on WebSiteOne and leave .env not checked in so that developers can have their own API keys in there - at least that's the usual pattern I've been used to ...

happy to consider the various pros and cons

**Comment by Maroo-b** [comment]
@tansaku I was checking dotenv gem docs and the author suggest to commit development ENV keys only (https://github.com/bkeepers/dotenv#should-i-commit-my-env-file) 

I remember that I told you about Figaro gem (https://github.com/laserlemon/figaro) I have used it in all my production projects, the advantage of choosing this gem is that it offers a simple command to export all the ENV keys to Heroku ( which helps to organize ENV keys)

**Comment by kenshinji** [comment]
@Maroo-b So do you think Figaro gem is the right way we should follow?

**Comment by tansaku** [comment]
@kenshinji it's certainly something to try I think

**Comment by tansaku** [comment]
there even seems to be a ruby rogues reading of the dotenv source! https://www.youtube.com/watch?v=lKmY_0uY86s

**Comment by tansaku** [comment]
@kenshinji perhaps you could start on this by doing a bit of research of the Figaro gem and letting us know what you think - @Maroo-b has used it before so should be able to help with questions ...

**Comment by kenshinji** [comment]
@tansaku Which environment do we use airbrake for? production or development? I found that the author of figaro have mentioned the [similarities and differences between figaro and dotenv](https://github.com/laserlemon/figaro#is-figaro-like-dotenv), but I should figure out in what context we use airbrake and gmap api key first.

**Comment by tansaku** [comment]
@kenshinji so in principle airbrake operates on both develop and production, although it's more important in production.  Superficially I think we don't need the GMAPs api key on production, because ours is a legacy side that doesn't need a key, although that may change.

I see from your link that figaro is a potential replacement for dotenv?  I had been thinking it was something we would add on top.  Replacing dotenv is a bigger step.

There's an alternate approach which we have in the WSO project where we use a rails config gem https://github.com/railsconfig/config to have config vars that need to be checked in, be checked in - that maybe doesn't actually solve our problem in this case since airbrake or what have you is tied directly to ENV vars ...?

So after some more research the key thing will be to work out the simplest possible intervention that addresses the issue - perhaps not having the GMAPS_API_KEY in .env, but just adding some instructions to the documentation about how to set it up, and adjusting the code in this current PR to just not set a key at all if none is set in the ENV.

I realise there are lots of moving parts here - feel free to ask lots of questions; and I'll be back in the UK in a week and maybe we can set up a hangout to look at any really complex issues

**Comment by tansaku** [comment]
closing this as @kenshinji and I are working on another branch for this fix

**Pull request closed without merging**
