### PR TITLE
Fix codeclimate issue by using && and ! instead of "and" and "not"

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes https://www.pivotaltracker.com/story/show/146844951

### CODE REVIEW

**Comment by tansaku** [comment]
this is an interesting one @lokeshh - I think `and not` reads better, although there is the issue that these do different things.  Avdi Grimm talks about that here: 

http://www.virtuouscode.com/2010/08/02/using-and-and-or-in-ruby/

we've had other places where switching to && actually breaks things in Rails.

I'm wondering here whether we should be adjusting codeclimate to ignore this issue ... there are situations where the control flow operators (and, not, or) should be preferred and codeclimates rubocup blanket always use the boolean operators might be seen as counter-productive ...

**Comment by lokeshh** [comment]
Ok then I will withdraw this PR for now.

**Comment by tansaku** [comment]
@lokeshh ah, well I was thinking we might update the PR to include changing the config ... or at least open a ticket in PT about changing the config?

**Comment by lokeshh** [comment]
@tansaku Ok I've opened a ticker here: https://www.pivotaltracker.com/story/show/146910579

**Pull request closed without merging**
