### PR TITLE
White label locality name

### PR DESCRIPTION
**Pull request by ciremoussadia**
White label Locality bob using Site title.

Addresses: https://www.pivotaltracker.com/story/show/164910567

### CODE REVIEW

**Comment by ciremoussadia** [comment]
Capture d’écran 2019-05-20 à 14 49 16

Found some error related to rubocop.

@tansaku or @mattwr18 can u review this?

**Comment by tansaku** [comment]
thanks @ciremoussadia :-)

can you see the rubocop issues here? https://codeclimate.com/github/AgileVentures/LocalSupport/pull/1076

It looks like they are a combination of line length and single vs double quote issues.  



Do they make sense?

**Comment by ciremoussadia** [comment]
@tansaku yeah that make sense but when i run rubocop command on local I get those errors so cant verify what I'm doing before pushing it to to the PR.

**Comment by tansaku** [comment]
@ciremoussadia sure - so you can try and fix locally and just push and see to get feedback, which is a bit slow, but you should get the same output if you run rubocop locally and ensure that you are using the .rubocop.yml file committed in the project root ...

**Comment by tansaku** [comment]
@ciremoussadia admittedly it is pretty tricky to run locally on just the changes you've made, but it can be done.  I just did it with the following:

```
git diff-tree -r --no-commit-id --name-only develop@\{u\} head | xargs ls -1 2>/dev/null | grep '\.rb$' | xargs rubocop --force-exclusion
```

following suggestions here: http://www.red56.uk/2017/03/26/running-rubocop-on-changed-files/

It did require me to set the upstream for develop which I did via:

```
git branch -u origin/develop develop
```
but you probably have a different value for origin locally.  I also had to fix some issues in the rubocop file, so maybe let me take care of all this for you  ...

**Comment by tansaku** [comment]
I just ran the autofix option locally (added `-a`) and we're down to just 4 issues:

```
git diff-tree -r --no-commit-id --name-only develop@\{u\} head | xargs ls -1 2>/dev/null | grep '\.rb$' | xargs rubocop -a --force-exclusion
```

```
app/mailers/admin_mailer.rb:23:91: C: Metrics/LineLength: Line is too long. [96/90] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)
    mail(subject: "A new organisation has been proposed for inclusion in #{Setting.site_title}",
                                                                                          ^^^^^^
app/mailers/custom_devise_mailer.rb:24:91: C: Metrics/LineLength: Line is too long. [100/90] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)
    mail(subject: "Your organisation has been approved for inclusion in the #{Setting.site_title}!",
                                                                                          ^^^^^^^^^^
app/mailers/org_admin_mailer.rb:11:91: C: Metrics/LineLength: Line is too long. [98/90] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)
    mail(subject: "You have been made an organisation administrator on the #{Setting.site_title}",
                                                                                          ^^^^^^^^
app/mailers/org_admin_mailer.rb:17:91: C: Metrics/LineLength: Line is too long. [98/90] (https://github.com/bbatsov/ruby-style-guide#80-character-limits)
    mail(subject:"Your Organisation has been accepted for inclusion on the #{Setting.site_title}",
                                                                                          ^^^^^^^^
```
I guess I'll just pull out some vars here

**Comment by tansaku** [comment]
@ciremoussadia looks like I've been able to fix all locally so I've pushed up, along with some updates to the .rubocop.yml file ...

assuming the build passes, we can get this merged in - thanks so much for your effort here :-)

**Comment by tansaku** [comment]
loads of weird fails in the build - first two are green when I run locally ... very strange:

```
/navigation_steps.rb:52
    And I should see 10 markers in the map                                      # features/step_definitions/volunteer_op_steps.rb:133
      expected to find visible css ".vol_op" 10 times, found 1 match: "" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/volunteer_op_steps.rb:134:in `/^I should see (\d+) markers in the map$/'
      features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:29:in `And I should see 10 markers in the map'
Failing Scenarios:
cucumber -p second_try features/admin/import_email.feature:20 # Scenario: import email addresses
cucumber -p second_try features/admin/organisation_reports/without_users.feature:95 # Scenario: Invited user email is out of date
cucumber -p second_try features/admin/user_reports/manage_charity_admins.feature:29 # Scenario: Adding non-existent user as charity superadmin invites said user
cucumber -p second_try features/admin/user_reports/manage_charity_admins.feature:38 # Scenario: Adding non-existent user as charity superadmin invites said user
cucumber -p second_try features/admin/user_reports/manage_charity_admins.feature:42 # Scenario: Successfully add existent user as charity superadmin
cucumber -p second_try features/events/map.feature:22 # Scenario: Show all events in map on events page map
cucumber -p second_try features/events/map.feature:28 # Scenario: Infowindow appears when clicking on map marker
cucumber -p second_try features/events/search_local_events.feature:20 # Scenario: Find out what's going on locally
cucumber -p second_try features/individual_charity_pages/propose_new_organisation.feature:49 # Scenario: Unregistered user proposes new organisation
cucumber -p second_try features/individual_charity_pages/propose_new_organisation.feature:63 # Scenario: Unregistered user proposes new organisation without checking confirmation box
cucumber -p second_try features/individual_charity_pages/propose_new_organisation.feature:78 # Scenario: Signed in user proposes new organisation
cucumber -p second_try features/organisations/map.feature:25 # Scenario: Show all charities in map on organisations index page map
cucumber -p second_try features/organisations/map.feature:31 # Scenario: Infowindow appears when clicking on map marker
cucumber -p second_try features/organisations/map.feature:43 # Scenario Outline: Organisation map has small icon for organisations updated more than 365 days ago, Examples (#1)
cucumber -p second_try features/organisations/map.feature:44 # Scenario Outline: Organisation map has small icon for organisations updated more than 365 days ago, Examples (#2)
cucumber -p second_try features/organisations/map.feature:45 # Scenario Outline: Organisation map has small icon for organisations updated more than 365 days ago, Examples (#3)
cucumber -p second_try features/organisations/map.feature:46 # Scenario Outline: Organisation map has small icon for organisations updated more than 365 days ago, Examples (#4)
cucumber -p second_try features/organisations/map.feature:47 # Scenario Outline: Organisation map has small icon for organisations updated more than 365 days ago, Examples (#5)
cucumber -p second_try features/organisations/map.feature:48 # Scenario Outline: Organisation map has small icon for organisations updated more than 365 days ago, Examples (#6)
cucumber -p second_try features/organisations/map.feature:51 # Scenario: Organisation map has large icon for organisation with no users
cucumber -p second_try features/organisations/map.feature:56 # Scenario: Changing address on the map changes the map coordinates
cucumber -p second_try features/organisations/map.feature:71 # Scenario: Changing postcode changes the map coordinates
cucumber -p second_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:16 # Scenario: See a map of current doit and harrow volunteer opportunities
cucumber -p second_try features/volunteer_opportunities/map_volunteer_opportunities.feature:60 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#1)
cucumber -p second_try features/volunteer_opportunities/map_volunteer_opportunities.feature:61 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#2)
cucumber -p second_try features/volunteer_opportunities/map_volunteer_opportunities.feature:62 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#3)
cucumber -p second_try features/volunteer_opportunities/map_volunteer_opportunities.feature:63 # Scenario Outline: See a list of do-it and local volunteer ops with same coordiantes in same maker popup, Examples (#4)
cucumber -p second_try features/volunteer_opportunities/map_volunteer_opportunities.feature:65 # Scenario: Imported "reachskills" volunteer ops with nil coords are assigned default coords
cucumber -p second_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:12 # Scenario: See a map of current reachskills volunteer opportunities
cucumber -p second_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:16 # Scenario: See a map of current reachskills and harrow volunteer opportunities
30 scenarios (30 failed)
235 steps (30 failed, 24 skipped, 181 passed)
1m27.064s
Coverage report generated for Cucumber Features, RSpec to /home/travis/build/AgileVentures/LocalSupport/coverage. 1969 / 2076 LOC (94.85%) covered.
The command "bundle exec rake cucumber:second_try" exited with 1.
```

**Comment by tansaku** [comment]
for example running that last one:

```
$ be cucumber features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:16 

Using the default profile...
@vcr @javascript @billy
Feature: Reachskills volunteer opportunities
  As a member of the public
  So that I can see where organisations with volunteer opportunities are located
  I would like to see a map of reachskills volunteer opportunities

  Background:                                                          # features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:7
    Given that the reachskills_volunteer_opportunities flag is enabled # features/step_definitions/volunteer_op_steps.rb:109
    And I run the import reachskills service                           # features/step_definitions/volunteer_op_steps.rb:76
Capybara starting Puma...
* Version 3.12.1 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:55643
    And cookies are approved                                           # features/step_definitions/authentication_steps.rb:98

  Scenario: See a map of current reachskills and harrow volunteer opportunities # features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:16
    Given the following organisations exist:                                    # features/step_definitions/factory_steps.rb:78
      | name                      | description          | address        | postcode | website       |
      | Cats Are Us               | Animal Shelter       | 34 pinner road | HA1 4HZ  | http://a.com/ |
      | Indian Elders Association | Care for the elderly | 64 pinner road | HA1 4HZ  | http://b.com/ |
    Given the following users are registered:                                   # features/step_definitions/factory_steps.rb:88
      | email                         | password | organisation | confirmed_at         |
      | registered_user-1@example.com | pppppppp | Cats Are Us  | 2007-01-01  10:00:00 |
    Given the following volunteer opportunities exist:                          # features/step_definitions/factory_steps.rb:97
      | title              | description                     | organisation              |
      | Litter Box Scooper | Assist with feline sanitation   | Cats Are Us               |
      | Office Support     | Help with printing and copying. | Indian Elders Association |
    And I visit the volunteer opportunities page                                # features/step_definitions/navigation_steps.rb:52
    And I should see 10 markers in the map                                      # features/step_definitions/volunteer_op_steps.rb:133

1 scenario (1 passed)
8 steps (8 passed)
0m9.519s
Coverage report generated for Cucumber Features to /Users/tansaku/Documents/GitHub/AgileVentures/LocalSupport/coverage. 640 / 922 LOC (69.41%) covered.
```

**Comment by tansaku** [comment]
hmm, although I notice some geocoded stuff being stored in my local VCRs which might be part of the issue ...

**Comment by ciremoussadia** [comment]
@tansaku I just made minor changes why all this?

**Comment by tansaku** [comment]
@ciremoussadia I don't know - not your fault - this is the general problem with flaky acceptance tests ... particularly in CI.

develop seems to be green.  It might be all fixed just by merging in develop, or maybe there's something deeper ... these corner cases are usually pretty tricky - thing to check is that you can run `bundle exec cucumber` and that the majority of the tests pass.

if things are failing in the CI but passing locally that's usually a sign that our acceptance tests are brittle or our CI configuration has a problem ...

it's an ongoing problem that makes us question the value of acceptance tests in CI - we do have all sorts of checks in place (like excluding some particularly flaky tests and a repeat run on any individual fails from the batch run) but there always seems to be something new to burn time on ...

**Comment by tansaku** [comment]
@ciremoussadia - @mattwr18 has flagged that @StlMaris123 seems to be having a similar issue with her PR - I'm merging in develop here to see if that helps ... does seem like we have some systemic issue here ...

**Comment by tansaku** [comment]
ah, so merging in develop seems to have helped ...

**Pull request merged**
