### PR TITLE
White label banner

### PR DESCRIPTION
**Pull request by ciremoussadia**
Moves banner background properties to a css erb file.

Now Background can be set with Setting.large_banner_path for large screens and Setting.small_banner_path for smaller screen.

### CODE REVIEW

**Comment by ciremoussadia** [comment]
This a first solution for white labelling the banner. 

Some drawbacks are:
- image should be in assets pipeline
- size should be predefined to fit the actual size of the placeholder.

@tansaku @mattwr18 i propose to extract the image. I mean instead of making it a background-image, it can be an image tag. We can so have control of the sizing, and also be able to refer to images as ulrs.

**Comment by tansaku** [comment]
hi @ciremoussadia - big thanks for this, much appreciated.

You are probably right in the long term that we should extract the image.  In the ideal case for an white-label system we should provide the admin with the ability to upload an arbitrary image, and so control over sizing would be important - and then we get in to where that image gets hosted?  AWS?  recently I've loved the way netlfyCMS allows us to add images directly to git, but that's for static sites :-/

In the short term we need to have a system that continues to support the default images, and at the minimum that they can be switched off, or possibly switched for others that we've dropped into the asset folder.

I was just running your branch locally and the images are missing as shown:



I also notice the contents of the asset compiled `page_logo_background...css` is empty.  One thing that we need for each of these features is the inclusions of defaults that allow the system to operate as it did before we adding the setting changes.   So I think we need the following:

```rb
  DEFAULTS = {
    latitude: '51.5978',
    longitude: '-0.3370',
    site_title: 'Harrow Community Network',
    meta_tag_title: 'Harrow Community Network',
    meta_tag_site: 'Harrow volunteering',
    meta_tag_description: 'Volunteering Network for Harrow Community',
    open_graph_site: 'Harrow Community Network',
    large_banner_path: 'HCN-long.png', # <--- ADD default image 
    small_banner_path: 'HCN-small.png' # <--- ADD default image 
  }
```
in the `Settings` model, to ensure that if no settings are present that the system defaults to the original behaviour.   

I did add those defaults locally, but still the `page_logo_background...css` was empty and the logo was not displayed.  Without the logo is actually looks pretty good and simply removing the logo is great for the demo we are putting together for KCSC, but I wonder if there is something else going wrong here?

I played around a little and found that if I remove `page_logo_background.css.erb` and I make `application.css` into `application.css.erb` and put the erb sprinkles there then it does work given that the default settings are in place.

```erb
@media (min-width: 980px) {
    #page-logo {
        background: url(<%= Setting.large_banner_path %>) no-repeat;
        display: inline-block;
        height: 72px;
        width: 1200px;
        line-height: 0;
        font-size: 0;
        color: transparent;
    }
```

It's not ideal as switching `application.css` to `application.css.erb` means that I lose all the nice css styling for the entire file in vscode (maybe there's a way to apply a secondary editor syntax style?), but at least with this change I can get the critical functionality that we want, i.e. the ability to remove the current banners, but also to support them by default.

I also note that since the build passed on this PR it's clear that none of our tests are checking that the images are displayed.  Maybe we should add tests, or maybe the absence/presence of images if so obvious to our eyes it's not worth even creating tests?

Anyhow I also discovered that in order to see the effect of changes to the image settings we need to clear the asset cache:

```
rake tmp:cache:clear
```

so quite a few wrinkles to this ticket beyond what we imagined.  I don't know why the `page_logo_background.css.erb` was generating an empty `page_logo_background.css` for me - can you check in your browser to see what the contents are for you locally?

**Comment by tansaku** [comment]
a little further follow up here - it seems to me like when the settings are empty that the `page_logo_background...css` file in the browser is empty - almost like the asset pipeline is clever enough to realise it's not contributing anything and so leaves it empty ... or is it that an empty string causes an error somewhere in the pipeline and that causes the file to be empty?  if I put a dummy string in (e.g. "no image") then the whole file appears in the browser.

I think the caching of the asset pipeline makes this whole thing super confusing.  I've now got everything working with just the changes you made (i.e. `page_logo_background.css.erb`) so I'm going to push up the addition to the defaults.

**Comment by ciremoussadia** [comment]
Yeah @tansaku there's something to care about the asset pipeline, that's why I propose the second proposition which is extracting the background image to an image tag.

**Comment by tansaku** [comment]
@ciremoussadia indeed - thanks for this great start - I've merged it in as it is all we need for the moment - we could create a new ticket for the switch to an image tag, but it is not a huge priority - maybe something to discuss and vote on in the next localsupport meeting.

**Comment by ciremoussadia** [comment]
@tansaku absolutely. I will create it on Pivotal tracker.

**Pull request merged**
