### PR TITLE
Adjusts settings to have PR demo deploys use free dynos

### PR DESCRIPTION
**Pull request by tansaku**
Addresses: https://www.pivotaltracker.com/story/show/116276111

### CODE REVIEW

**Comment by tansaku** [comment]
@Maroo-b - this is your previous pull request re-opened against the new stable develop branch (thanks so much for this BTW) - your original was at #333 - I really appreciate how you consistently put a link to the relevant pivotal ticket in the PR description, and how you remember to add the [fixes #id] in the github commit message (something I often forget).

Just to save you the extra work, I think we probably don't need the PT id in the title of the pull request, and also, I think it's only a single # mark.

Lastly it's probably me being obsessive :-) but I'm trying to standardize on feature branch names like the one I've used here, e.g. 116276111_use_free_dyno_for_review_app, i.e. starting with the PT id and then the english description.

This doesn't have any functional purpose here (unlike in GitHub tracked projects where it is interpreted by tools like waffle to assign a developer to a ticket), but I think it's useful approach to take as we can easily see (and sort) all the feature branches that are related to a particular ticket.

I think I've got all these things specified in https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md but I'll review, and if you can help me with the language/organisation of that doc so that we can help all new developers get on the same page, I'll be very grateful indeed :-)

Many thanks for you many and great contributions to the project - hope that you're deriving value for your professional development journey and let me know if there is anything I can do to help ...

**Comment by johnnymo87** [comment]
+1

**Comment by MLT-Test** [comment]
+1

**Comment by decareano** [comment]
+1

**Comment by Maroo-b** [comment]
@tansaku I suggest to check PR format of Osra project. Here is an example ( https://github.com/AgileVentures/osra/pull/411). You can note that:

- add a link to ticket is very helpful
- add bullet point to describe news changes
- add screenshot if there is UI changes.

I think also we should improve the commit message I'll try to create a draft for the updated contribution guideline.

**Comment by tansaku** [comment]
@Maroo-b yeah, that's a good set.

As a PM, the minimum I'm looking for is the link to the ticket.  A list of changes and screenshots are a bonus, but very welcome.  Although often the set of changes are described in the git commits, and if we have automatic deploys we can go to the running app to see the UI - but a screen shot of the expected change is really helpful ...

**Pull request merged**
