### PR TITLE
Fix frozen event page on update request when invalid params are provided

### PR DESCRIPTION
**Pull request by vikasvr**
Addresses: https://www.pivotaltracker.com/story/show/159646331

### CODE REVIEW

**Comment by tansaku** [comment]
Thanks for this @vikasvr - do we have a corresponding pivotal tracker ticket?

**Comment by vikasvr** [comment]
@tansaku I didn't got the option to add this as a story since i have a viewer access to local support stories.

**Comment by tansaku** [comment]
@vikasvr oh sorry, you're a member now - please feel free to add :-)

**Comment by vikasvr** [comment]
@tansaku  Great Thanx

**Comment by tansaku** [comment]
great work @vikasvr - many thanks!

**Pull request merged**
