### PR TITLE
Refactoring persist_reach_skills_vol_ops to fix "Metrics/MethodLength…

### PR DESCRIPTION
**Pull request by rehan-work**
Refactored persist_reach_skills_vol_ops to deal with codeclimate TooManyLines issue. Renamed find_coortinates to find_coordinates.

### CODE REVIEW

**Comment by tansaku** [comment]
great work @rehan-work 

Only other thing I'd ask is that you provide a link to the pivotal tracker issue in the PR, and if you can, add [Finishes #xyz] in the commit so that when I merge the PR it will auto close the ticket - are you just working against https://www.pivotaltracker.com/story/show/144123041 or did you create separate sub-tickets?

See https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#git-comments for more info on the format for git commits to close PT issues

**Comment by rehan-work** [comment]
ok great, noted. I'm working against https://codeclimate.com/github/AgileVentures/LocalSupport/pull/421 but I'm still figuring out this workflow. By tickets/sub-tickets, does that refer to stories, github issues or PRs? Unsure where to split the task into multiple ones

**Comment by tansaku** [comment]
tickets for this project are all Pivotal tickets - all work should correspond to a PT ticket - we don't use GitHub issues in this project - but there are others that do like WebsiteOne and MetPlus

**Comment by rehan-work** [comment]
got it, will split the PT issue into multiple tickets and reference the one this solves

**Comment by rehan-work** [comment]
added the story to the tracker https://www.pivotaltracker.com/n/projects/742821/stories/144599851

**Comment by Maroo-b** [comment]
thanks @rehan-work for the PR.

+1

**Pull request merged**
