### PR TITLE
Update libidn url

### PR DESCRIPTION
**Pull request by NickSchimek**
The url to download the idn library was pointing to an invalid endpoint.
Updated URL

### CODE REVIEW

**Comment by sigu** [comment]
@NickSchimek Will review once in the house and merge in

**Comment by nisevi** [comment]
@sigu  @NickSchimek I used your updated link for the installation, it works :+1:

**Comment by sigu** [comment]
It works!!!
screenshot from 2018-03-22 22-40-08

**Comment by NickSchimek** [comment]
@nisevi Thanks for the feedback. I added a line mentioning that the command may need to be ran with sudo.

**Pull request merged**
