### PR TITLE
[WIP] add edit button to event show page

### PR DESCRIPTION
**Pull request by Xiaohong-Deng**
Addresses: [need to allow editing of existing events](https://www.pivotaltracker.com/n/projects/742821/stories/156008299)

@tansaku I have two questions at the moment
1. If a `@editable` variable is desired, what authorization level a user should have to edit the event?
2. Is it ok to put the tests in `features/events/show.feature`? if `@editable` is desired I think I should test against users with each of the authorization levels? these should all be done in cucumber right?

### CODE REVIEW

**Comment by tansaku** [comment]
@Xiaohong-Deng thanks for this - at the moment we could just start with having events editable by any logged in user, and then we could have a separate ticket for adjusting access once we've been able to discuss that with the client.

I would be tempted to put editing cukes in features/events/edit.feature

**Comment by tansaku** [comment]
hi @Xiaohong-Deng - need any help on this? :-)

**Comment by Xiaohong-Deng** [comment]
sorry @tansaku 

I'll get back to this ticket in a week.

**Comment by Xiaohong-Deng** [comment]
@tansaku I have been caught up in a project that will keep me occupied for another 2 or 4 week period. I think I can finish this ticket in 3 days or so once I get back.

Is that ok? I have to work on the other project first because I have a dealine to catch.

**Comment by tansaku** [comment]
that's fine @Xiaohong-Deng - although any longer than that and we'll need to re-assign

**Pull request closed without merging**
