### PR TITLE
jquery validation library added as also org_validation js file

### PR DESCRIPTION
**Pull request by Icicleta**
So far, I've just added the jquery validation code file and created a new one to add the custom code for this plugin. 
Last added require both files in application.js

### CODE REVIEW

**Comment by tansaku** [comment]
hi @Icicleta thanks for this :-)  this is for this chore right? https://www.pivotaltracker.com/story/show/62111296

**Comment by Icicleta** [comment]
it is @tansaku :) Still needs validations. I already created them and I'm very close to make them pass :)

**Comment by tansaku** [comment]
hi @Icicleta any update on this? :-)

**Comment by tansaku** [comment]
hi @Icicleta I'm sure you're really busy :-) So no worries if you can't get back to me, but if I don't hear from you in the next week I'll probably go ahead and close this up ...

**Pull request closed without merging**
