### PR TITLE
Extract login code from other branch, leaving out basscss

### PR DESCRIPTION
**Pull request by johnnymo87**
This is for @maciejk77 to consider. This is a continuation of [Login form react](https://github.com/AgileVentures/LocalSupport/pull/258), without the basscss changes. 

Without the css, it looks fairly strange. This is what it used to look like: http://quick.as/a1nziky94

For now, I'll throwing this component in the wrong place on the page.

### CODE REVIEW

**Comment by tansaku** [comment]
this looks interested @johnnymo87 - is it staged somewhere?

Sorry the automated heroku staging is not working - we have some kind of issue with our database needing to be available early that's preventing the automated staging from working ...

**Comment by tansaku** [comment]
@maciejk77 any thoughts on this?

**Comment by tansaku** [comment]
@johnnymo87 I guess if we don't hear from @maciejk77 in a week or so we should close this out, or can we build on it?

**Comment by maciejk77** [comment]
Hi @johnnymo87 & @tansaku 

It looks I am pretty tied up with work, so I won't be able to contribute in the coming weeks.
Apologies for that

**Comment by tansaku** [comment]
no worries @maciejk77 - thanks for letting us know; @johnnymo87 let me know if it's worth keeping this open

**Comment by decareano** [comment]
@tansaku, @johnnymo87. I am learning React (beginner level) and I would like to keep working at it time permitting though. I could pair on weekends if somebody is interested.

**Comment by tansaku** [comment]
@decareano I guess you couldn't find anyone to pair with? :-(  I guess we'll close this for the moment ...

**Comment by tansaku** [comment]
@decareano btw, did you see http://www.agileventures.org/pricing - with premiumplus we can get you guaranteed pairing time ...

**Pull request closed without merging**
