### PR TITLE
Change ambiguous language in admin notification mails (#338)

### PR DESCRIPTION
**Pull request by tansaku**
Addresses: https://www.pivotaltracker.com/story/show/113746563

* increases devise token duration to 7 days

* increases devise token duration to 7 days

* Change ambiguous language in admin mails [Fixes #113746563]

* Fix spec

* Refactor over Hound comments

* Adjusted feature tests

### CODE REVIEW

**Comment by johnnymo87** [comment]
What are the bullet points in the PR description about?

+1

**Comment by tansaku** [comment]
@johnnymo87 - I think that's from an earlier rebase commit ...

**Comment by Maroo-b** [comment]
+1

**Comment by decareano** [comment]
+1

**Pull request merged**
