### PR TITLE
update Faker deprecated methods

### PR DESCRIPTION
**Pull request by pjbelo**
`rails db:seed` aborts with errors:
`NameError: uninitialized constant Faker::DrWho`
`NameError: uninitialized constant Faker::Robin`
(also when running `bundle exec rails db:seed` )

because these methods were deprecated in [v1.9.2 (2019-02-11) PR 1504 1431](https://github.com/stympy/faker/blob/master/CHANGELOG.md).

This PR replaces these methods with:
`Faker::TvShows::DrWho.quote` and `Faker::Quote.robin` respectively.

Corrects issue #1134 

What do you think @tansaku @mattwr18 ?

### CODE REVIEW

**Comment by tansaku** [comment]
@pjbelo have you tired `bundle exec rails db:seed`? 

Is this happening on develop, or just for these change?

**Comment by aonomike** [comment]
Hi @pjbelo the failing ci tests have been fixed by a from @Maroo-b . Would you please pull from develop and see if tests pass on your branch? I am thinking that could be the reason we hadn't merged this one. Thanks

**Comment by pjbelo** [comment]
Hi @aonomike 

All is green :-)

I also did a change to keep `DrWho.quote` method.

Thanks

**Comment by aonomike** [comment]
Thanks @pjbelo Looks good to me

**Pull request merged**
