### PR TITLE
Support search by self care, location and activity categories

### PR DESCRIPTION
**Pull request by tansaku**
So this supports an additional feature requested by the KCSC folks, which is supporting search by self care, location and activity categories.  It's a follow on to https://www.pivotaltracker.com/story/show/165189614

### CODE REVIEW

**Comment by aonomike** [comment]
Hi @tansaku any directions on what we should do after this? :)

**Comment by tansaku** [comment]
hi @aonomike sorry I missed your message here - I'm afraid that I only have slivers of time to work on this each day -  I'm currently working from a little local list:

```
--> review kcsc site and do migrations  --> look at current categories
--> do we want service_categories?  or adjust existing categories table?
--> maybe SelfCareCategory ?  new object would help us populate drop down for search ...
------> three existing drop downs: Type of Activity, Location, Self-care service categories (new table for last - other two could be fields with Enums?)

--> cucumber for search by category?
- individual marker not showing for service DONE?
- other clear up on service page ... DONE?
- popups not looking great
- centre map on service
- need services in nav bar
- search for all categories not working DONE?
- not maintaining selection for categories DONE
- search needs to work for activity type and location DONE
```
and I'm just slicing off bits as I work on them - just trying to get the app to a state where it has the minimum KCSC has asked for.

If I had more time I could write up each thing as a ticket and parcel out the work, but not sure that's practical with a client waiting - hope to be finished within a week or so ...

**Comment by tansaku** [comment]
actually @aonomike as it happens with what I've just pushed up we're almost there.  One thing that you could help with is getting a services tab in the nav bar, wrapped in a feature flag, if you know what I mean.  I think we already have that for the volunteer ops, so if you just looked at the code for that.   When I say the nav bar I mean the set of links to each type of object in the right of the image below:

Screenshot 2019-07-25 08 48 51

**Comment by tansaku** [comment]
ah @aonomike - looks like @StlMaris123 has already added

**Comment by tansaku** [comment]
so funny thing is that it looks like the build passes, but we get a fail:



maybe from code climate?

**Pull request merged**
