### PR TITLE
Vcr billy cucumber

### PR DESCRIPTION
**Pull request by ZmagoD**
* This is my addition  Vcr_cucumber_only #190 PR @decareano @tansaku

### CODE REVIEW

**Comment by ZmagoD** [comment]
@decareano @tansaku @mtc2013 @marianmosley  do anyone know what is this and why the test fail in Travis 
252 scenarios (1 undefined, 251 passed)

1982 steps (1 undefined, 1981 passed)

1m41.301s

stack level too deep (SystemStackError)

/home/travis/build/AgileVentures/LocalSupport/vendor/bundle/ruby/2.0.0/gems/gherkin-2.12.2/lib/gherkin/i18n.rb:169

The command "bundle exec rake test_with_coveralls" exited with 1.

9.13s$ USE_JASMINE_RAKE=true bundle exec rake jasmine:ci

Waiting for jasmine server on 59913...

[2015-11-23 21:29:00] INFO  WEBrick 1.3.1

[2015-11-23 21:29:00] INFO  ruby 2.0.0 (2014-11-13) [x86_64-linux]

[2015-11-23 21:29:00] INFO  WEBrick::HTTPServer#start: pid=27584 port=59913

Waiting for jasmine server on 59913...

jasmine server started.

..............................[2015-11-23 21:29:03] ERROR invalid body size.

30 specs, 0 failures

[2015-11-23 21:29:03] INFO  going to shutdown ...

[2015-11-23 21:29:03] INFO  WEBrick::HTTPServer#start done.

The command "USE_JASMINE_RAKE=true bundle exec rake jasmine:ci" exited with 0.

Done. Your build exited with 1.

**Comment by tansaku** [comment]
@zmagoD thanks for this - Not immediately sure - is everything running locally for you?  The command that failed is:

"bundle exec rake test_with_coveralls"

I added coveralls support recently - maybe that is playing badly with puffing billy?

**Comment by ZmagoD** [comment]
Yes locally all tests pass and if I run "bundle exec rake test_with_coveralls" also all tests pass

**Comment by tansaku** [comment]
@ZmagoD thanks - can you merge this to develop, check the error still occurs and submit support tickets to coveralls/travis/puffing_billy posting links to those issues/tickets here?

**Comment by johnnymo87** [comment]
I believe this needs further tuning. In this PR, if I switch to `files changed`, and search for "Sinatra", I get 424 hits. This is our `FakeGoogleGeocode` [sinatra app](https://github.com/AgileVentures/LocalSupport/blob/develop/test/fake_google_geocode.rb) being intercepted.

**Comment by tansaku** [comment]
thanks @johnnymo87 - maybe we shouldn't be using vcr  ... we need puffing billy on just the browser proxy ...

**Comment by tansaku** [comment]
and critically we need to test on a small subsection of the app, or a smaller app to be clear what is going on

**Comment by decareano** [comment]
@tansaku; @ZmagoD; @johnnymo87. I tested a subsection of the app in PR #198 only to realize later I broke other tests. So, I am sure about the approach. But I agree with Jon. The PR needs some work. I am going to look at the sinatra issue.

**Comment by tansaku** [comment]
@decareano testing on a portion goes hand in hand with then checking the rest.  You can't check a single portion and then ignore the rest;  but when working to understand what is going on it's critical to work with a subset.

**Comment by decareano** [comment]
@tansaku, @johnnymo87, @ZmagoD. I read article about how to setup the FakeGoogleGeocode app to stub external services (the one we have  deployed in LS) and now understand what Jon was indicating to us. I turned off `VCR`. I am running the proxy server with `@puffing-billy`. I am getting lots of failures with this error: `"No implicit conversion of symbol into integer"`. I googled this issue and came up with this: http://billpatrianakos.me/blog/2013/09/29/rails-tricky-error-no-implicit-conversion-from-symbol-to-integer. But I need help debugging this issue.

**Comment by tansaku** [comment]
hi @decareano - it's difficult to help with an error without a stacktrace, or a unconflicted branch.  Maybe you don't have a stacktrace?

Either way, perhaps you can get an unconflicted branch by merging develop, or branching a fresh of develop; close the old pull requests and open a new one, where the CI will run and how us the error?

I think this might also take starting with a simpler system that correctly uses puffing billy.  It might be a good idea to spike up a quick rails project, through in a feature test with a google map, and check we can get a clean test run from that ..., and make sure we are using puffing billy correctly before trying to get the whole thing working with our full LS project ...

**Comment by ZmagoD** [comment]
@decareano @tansaku @johnnymo87 Ok I will close that PR.

**Comment by tansaku** [comment]
thanks @ZmagoD do take a look at what Yana and JPB are doing with the do-it api - they are creating a little test rails app that will need VCR (or webmock) on the server and puffing billy for the client.  I think that part of the trick here might be to set these things up correctly on a smaller test project to get clear what's happening and then scale up to LS

**Comment by decareano** [comment]
@zmagoD, @tansaku, @johnnymo87. Yes, please close all the PR's we have open for tests in isolation. Sam, that's a good idea. I was looking at a simple google map: http://www.sitepoint.com/use-google-maps-rails to play with (other suggestions?) but if Yana and JPB have something going, we can work with that. I take it they are using Gmaps4Rails?

**Comment by tansaku** [comment]
@decareano thanks and yeah - check out the slack channel for LocalSupport, @Proskurina and JPB have been chatting there.  Here's Yana's repo https://github.com/Proskurina/doit_rails  - I'm not sure what they are using - chat with them.  I believe their plan is to start adding some feature tests to that code starting simple and working their way up - see if you can catch up with them in slack :-) If you can coordinate with them great - if not - don't worry :-)

BTW, I'm avoiding slack and hangouts this week and next for a bit of a break, but you can get me on pull requests like this :-)

**Pull request closed without merging**
