### PR TITLE
Invitation link failure 

### PR DESCRIPTION
**Pull request by Maroo-b**
Writing regression test for token expiration

### CODE REVIEW

**Comment by tansaku** [comment]
Great start @Maroo-b ! 

I wonder - can we explicitly test for the specific error message that we expect here?

Or are we not getting an error message?

**Comment by Maroo-b** [comment]
Thank you @tansaku 
With the current configuration for devise I didn't manage to replicate the error msg

**Comment by tansaku** [comment]
understood @Maroo-b - so in this case the test should be failing - our inability to replicate it is something that should be flagged with a failure rather than a success I think ...

Perhaps you can edit the scenario like so:

```gherkin
 Scenario: Invited user clicks through on email link after confirmation token expiration
    Given I check email for "superadmin@another.org" after confirmation token expiration
    And I click on the invitation link in the email to "superadmin@another.org"
    Then I should see "The invitation token provided is not valid!"
```

**Comment by tansaku** [comment]
thanks @Maroo-b - so this is now correctly seeing the token expire?  If so that's great 

note also you should set your global git email to get credit for your commits: https://help.github.com/articles/setting-your-email-in-git/

http://stackoverflow.com/questions/1746562/github-shows-name-instead-of-a-linked-username-in-commits

**Comment by tansaku** [comment]
@Maroo-b great - so perhaps can we add the fix for this, i.e. a change to the devise config to pull the secret from an env var?

**Comment by Maroo-b** [comment]
@tansaku currently the secret_key from devise config check for and ENV var and if not existent it will generate a random Hex

**Comment by tansaku** [comment]
@Maroo-b I think we should prioritize getting a simple manual fix out and then reviewing automation as a next step.

We have a bleed here so we should do the simplest thing to get it fixed

**Comment by Maroo-b** [comment]
@tansaku PR updated to make the tests pass

**Comment by tansaku** [comment]
thanks @Maroo-b - let's get this merged and deployed - do you have pivotal access?

**Comment by Maroo-b** [comment]
@tansaku  I have pivotal account but should I be invited to access the project ?

**Comment by tansaku** [comment]
@Maroo-b I invited you - but possibly not on the email associated with your PT account. 

Also, I was reflecting on this and I guess the critical chore is actually to set a devise secret key on production which I've now done, which gives us more room to refactor this PR if we wanted - are you interested in investigating the figaro or rails_config gems?

**Comment by Maroo-b** [comment]
@tansaku sure I'll check both gems and I'll do some tests in a demo Heroku app to be sure.

**Comment by tansaku** [comment]
thanks @Maroo-b - we were having quite a few ENV related issues on WSO yesterday - I think both WSO and LS could benefit from a more rigorous coordinated approach to ENV vars ...

**Comment by tansaku** [comment]
I'm starting to think that what we should have here is it set to that error is thrown if the environment variable isn't set ...

**Comment by tansaku** [comment]
@Maroo-b on reflection I think we should throw an error if the DEVISE_SECRET_YML is not set, and avoid any hard coding of key or random behaviour.

Let me know if you are free to work on this or if I should assign to someone else

**Comment by Maroo-b** [comment]
@tansaku that's interesting. If the task is in high priority it will be better if someone else will take the charge.

**Comment by tansaku** [comment]
@Maroo-b sure thing - leave it with me

**Comment by tansaku** [comment]
Just talking with @mtc2013 - thinking we might just close this pull request and replace with something like the following in the devise.rb file:

```ruby
def devise_secret_key_not_set_in_production?
  ENV['RAILS_ENV'] == 'production' && !ENV['DEVISE_SECRET_KEY']
end

NO_DEVISE_SECRET_KEY_MESSAGE = %q(
Please set a DEVISE_SECRET_KEY in environment vars for your production server
Consider using `SecureRandom.hex(64)` to ensure security
)

raise(NO_DEVISE_SECRET_KEY_MESSAGE) if devise_secret_key_not_set_in_production?
```

**Pull request closed without merging**
