### PR TITLE
changes to create_and_validate method in organisation.rb

### PR DESCRIPTION
**Pull request by RajeevHejib**
This change fixes the errors we get when we run db:seed first time when setting up environment first time.  This addresses https://www.pivotaltracker.com/story/show/113736889

The erros appear as below

```
➜ bundle exec rake db:seed                                                                                              [develop *]
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Description can't be blank
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/validations.rb:43:in `save!'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `block in save!'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `save!'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/persistence.rb:51:in `create!'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/models/organisation.rb:89:in `create_and_validate'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/services/create_organisation_from_array.rb:19:in `create'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/services/create_organisation_from_array.rb:6:in `create'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/models/organisation.rb:85:in `create_from_array'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/models/organisation.rb:99:in `block in import_addresses'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/models/organisation.rb:110:in `block in import'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/models/organisation.rb:106:in `import'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/app/models/organisation.rb:97:in `import_addresses'
/Users/rajeevhejib/Projects/AgileVentures/LocalSupport/db/seeds.rb:9:in `<top (required)>'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/Users/rajeevhejib/.rvm/gems/ruby-2.3.0@localsupport/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

rajeevhejib@MacBook-Pro [03:40:50] [~/Projects/AgileVentures/LocalSupport]
```

### CODE REVIEW

**Comment by RajeevHejib** [comment]
Getting these two (below) failures on CI.  Replacing null or empty with 'NO INFORMATION RECORDED'

Do we need changing these tests now that the validation don't allow null or empty.
```
Failures:
  1) Organisation Creating of Organisations from CSV file must be able to handle no address in text representation
     Failure/Error: expect(org.address).to eq('')
       
       expected: ""
            got: "NO INFORMATION RECORDED"
       
       (compared using ==)
     # ./spec/models/organisation_spec.rb:266:in `block (3 levels) in <top (required)>'
  2) Organisation Creating of Organisations from CSV file must be able to handle no postcode in text representation
     Failure/Error: expect(org.postcode).to eq('')
       
       expected: ""
            got: "NO INFORMATION RECORDED"
       
       (compared using ==)
     # ./spec/models/organisation_spec.rb:255:in `block (3 levels) in <top (required)>'
```

**Comment by tansaku** [comment]
@RajeevHejib thanks for this - great work

It's a good question - one which I'm also looking at in https://github.com/AgileVentures/LocalSupport/pull/259

I think even though we add validations it makes sense to test for situations in which legacy data in the database is the wrong format.

We also don't want big import jobs to fail suddenly due to these validations issues.  To be honest this all needs a more detailed review, but if this fixes the issue I will be tempted to pull it in as this issue is blocking people from getting set up.

What we might want is a test of rake db:seed (or some version of it) in the test suites ...

I'm going to start checking out this branch on my new laptop as part of reviewing the entire onboarding process.

**Comment by tansaku** [comment]
@RajeevHejib - this works on my fresh laptop install - this is a blocker for new devs so I'm going to merge and focus on the related tasks after:

https://www.pivotaltracker.com/story/show/113909345

We also seem to have some ticket duplication:

https://www.pivotaltracker.com/story/show/112885105
https://www.pivotaltracker.com/story/show/113736889

**Comment by RajeevHejib** [comment]
Thanks @tansaku.

The ticket https://www.pivotaltracker.com/story/show/113736889 you mentioned above is the current one (#266)

And you are right.  The other one is a duplicate.  Sorry, not sure how I created that.
And https://www.pivotaltracker.com/story/show/112885105 is duplicate and was solved by https://www.pivotaltracker.com/story/show/112492939.

Also spotted https://www.pivotaltracker.com/story/show/112453709 which also is a duplicate.  This was solved under https://www.pivotaltracker.com/story/show/112453577.

Should I close both duplicates?  Not sure how we go about closing a ticket.  Never done one before.

**Comment by tansaku** [comment]
no worries @RajeevHejib I think someone else created one too.  You can just click finish on the duplicates to close them out I think, or you could click the trash can (delete) button on https://www.pivotaltracker.com/n/projects/742821/stories/112885105 since that doesn't have any more info than the others ...

**Pull request merged**
