### PR TITLE
RFC: Propose and moderate edits to orgs

### PR DESCRIPTION
**Pull request by mtc2013**
PT Story https://www.pivotaltracker.com/story/show/85076386

### CODE REVIEW

**Comment by mtc2013** [comment]
Changing this to a request for comment since it is potentially done.

**Comment by tansaku** [comment]
Some quick notes:

* I'm a little worried about inconsistent indentation and spacing in spec files
* I also wonder what value we are getting from our request specs?
* Not sure I understand what proposed edit module is doing ..., but burden is probably on me to investigate further

**Comment by mtc2013** [comment]
Which spaces in particular?

The one request spec for proposed edit moderation is about testing security that we can't properly test in capybara.  The other one is me being a bit lazy and using it like an acceptance test rather than setting up the situation in cucumber because I thought it would be faster that way.

Proposed edit module basically defines instance level methods like editable? and accept which are tested by integration in the proposed_organisation_edit spec.

**Comment by decareano** [comment]
It would be nice if the user proposing an edit gets a flash message informing him/her that the edit has been proposed and will be reviewed by the administrator.

**Comment by tansaku** [comment]
good point @decareano - although perhaps that could be a separate feature request.  I'm continuing to go through the code as lack of tethering allows.  I've seen a possible refactoring:

```ruby
def setup_proposed_organisation_edit(proposed_organisation_edit)
    proposed_organisation_edit.name = proposed_organisation_edit.organisation.name
    proposed_organisation_edit.description = proposed_organisation_edit.organisation.description
    proposed_organisation_edit.address = proposed_organisation_edit.organisation.address
    proposed_organisation_edit.postcode = proposed_organisation_edit.organisation.postcode
    proposed_organisation_edit.email = proposed_organisation_edit.organisation.email
    proposed_organisation_edit.website = proposed_organisation_edit.organisation.website
    proposed_organisation_edit.donation_info = proposed_organisation_edit.organisation.donation_info
    proposed_organisation_edit.telephone = proposed_organisation_edit.organisation.telephone
    proposed_organisation_edit.donation_info = proposed_organisation_edit.organisation.donation_info
    proposed_organisation_edit
  end
```

to 

```ruby
%w{name description address postcode email website donation_info telephone}.each do |field|
  proposed_organisation_edit.send("#{field}=".to_sym,proposed_organisation_edit.organisation.send(field.to_sym))
end
```

more soon ...

**Comment by tansaku** [comment]
some more notes:

* #TODO dependent destroys & validations ?? in ProposedOrganisationEdit - is that comment dry
* tooltips/placeholders in proposed_organisation_edits feel a little unDRY
* why do we need AddDeletedAtIndexToProposedOrganisationEdit ?

* so proposed_organisation_edit model gets ProposesEdits module mixed in for convenience

--> why do we have both attr_reader :instance_to_edit AND def instance_to_edit


--> pending spec:

    context 'editabilty has changed' do
      pending
    end

--> do we really need to be using factory girl?

if we look at:

```ruby
  describe '::still_pending' do
    let(:archived_edit){FactoryGirl.create(:proposed_organisation_edit, :organisation => org, :archived => true)}
    it 'returns non archived edits' do
      expect(ProposedOrganisationEdit.all).to include archived_edit
      expect(ProposedOrganisationEdit.still_pending).to eq [proposed_edit] 
    end
  end
```

this checks that our 'still_pending' scope filters out those edits with :archived set to true - should we perhaps just be trusting that scoping works in rails, and that we should instead check that the scope is present and checking for the correct field - that said with factory girl this is checking the desired behaviour and will catch issues such as the database migration not having been set up correctly - I guess the question is are our tests to slow at the moment? I haven't run them recently ...

text for describe and then undoc'd it block feels odd:

```ruby
  describe 'soft delete of associated edits when org is soft deleted' do
    it do
      org.destroy
      expect(ProposedOrganisationEdit.all).not_to include proposed_edit
      expect(ProposedOrganisationEdit.with_deleted).to include proposed_edit
    end
  end
```

I'm not following '#non_published_editable_fields' ...

more soon

**Comment by mtc2013** [comment]
Sorry, can't respond to everything.

The Todo comment is out of date.  The index for deleted_at is recommended by paranoia gem docs.  In ProposedEdit module we should simply get rid of the attr_reader since the def makes it readable.

**Comment by tansaku** [comment]
thanks @mtc2013 and no worries about not responding to everything - I haven't finished my pass, and I need to get the whole thing working on my new laptop so that I can make some of the simple changes and send them back to you as pull requests

**Comment by mtc2013** [comment]
@tansaku had a chance to make any more progress on reviewing this pr?

**Comment by tansaku** [comment]
@mtc2013 looking through this I'd like to take a more detailed sweep of the cucumber, but I can't see anything there that should hold this up - and I can save that for later.

The only thing to finish up is just the proposed_organisation_edit_spec ... I've converted a lot of it to ensure that the format documentation is actually readable, e.g. 

```sh
ProposedOrganisationEdit
  should soft delete associated edits when org is soft deleted
  #accept
    update with params
      should change #archived from false to true
      updates the name attribute
      should change #accepted from false to true
  ::still_pending
    should return all edits that are not yet archived
  #non_published_editable_fields
    all fields are private
      returns email, telephone and address but nothing else
    address is public
      returns email, and telephone but not address
  #editable?
    should indicate editable for email
    should indicate editable for donation_info
    should indicate NOT editable for address
    should indicate editable for name
    should indicate editable for description
    should indicate NOT editable for telephone
    should indicate editable for postcode
    should indicate editable for website
    when publish field settings are changed
      should indicate NOT editable for email
      should indicate editable for address
      should indicate editable for telephone
  #has_proposed_edit?
```

I've run out of time this week - but if you could finish that off, i.e. these;

```sh
  #has_proposed_edit?
    editabilty has changed
      example at ./spec/models/proposed_organisation_edit_spec.rb:112 (PENDING: Not yet implemented)
    when an edit to :name has not been proposed
      should equal false
    when an edit to :name has been proposed
      should equal true
```

so that they read like English, i.e. updating the code in that spec:

```ruby

  describe '#has_proposed_edit?' do
    context 'when an edit to :name has not been proposed' do
      let(:proposed_edit){FactoryGirl.create(:proposed_organisation_edit, :organisation => org, :name => 'Harrow Bereavement Counselling' )}
      it{expect(proposed_edit.has_proposed_edit?(:name)).to be false }
    end
    context 'when an edit to :name has been proposed' do
      let(:proposed_edit){FactoryGirl.create(:proposed_organisation_edit, :organisation => org, :name => 'Harrow Bereavement Counseling' )}
      it{expect(proposed_edit.has_proposed_edit?(:name)).to be true }
    end
    context 'editabilty has changed' do
      pending
    end
  end
```

so that the output is readable (as I've done for the majority of the file), then I'd be happy to pull this in - assuming you can take care of that pending spec (remove or implement as appropriate).

If that's done I'll pull in on Monday and get along to production to show client on Thursday.  Apologies for delay.

**Comment by mtc2013** [comment]
@tansaku updated as requested

**Pull request merged**
