### PR TITLE
scaffold service solves #165189344 [WIP]

### PR DESCRIPTION
**Pull request by StlMaris123**
This pr references https://www.pivotaltracker.com/n/projects/742821/stories/165189344

### CODE REVIEW

**Comment by mattwr18** [comment]
@tansaku we spent quite a bit of time working on this cause we were not sure about several things.
In the end, we decided to put in a `PR`, knowing that it might never get merged, but to further conversation about this ticket. 

I don't pretend to be able to speak to all the concerns that were expressed in the pairing session, but some of the things we discussed were:
1) The name of the model being `Service` caused confusion for people familiar with services like the `ImportOrganisations` service.
2) Whether we should be having a separate model, controllers, etc.. or joining the services to the Organisations, similar to how we are doing with `/charities` and `/charity_objects`.... so that an Organisation would show it's Services
3) Should we be copying the questionable naming of the attributes for the `Services` table, or shortening/trying to improve the names

@StlMaris123 @ciremoussadia @aonomike @abdellani... if there is anything I misrepresented or that you would like to add to, please comment here

**Comment by tansaku** [comment]
HI @mattwr18 - great questions

1) a valid concern - rails uses the term "services" one way, and the stakeholders are using the term "services" to mean something different.  Domain Driven Design (DDD) argues that we should do our best to accurately reflect the real terms being used by the stakeholders in the domain.  It's not ideal, but in the first instance I think we might need to prioritize stakeholder terminology over developer/framework terminology

2) My intuition is that there should be a separate model and controllers - I mean we could be referring to them as "organisation services" or "community services" (sorry I'm thinking about naming again) but that seems long winded.  With charities and charity_objects the joining is simply the name?  Each "service" should indeed have a relationship with one or more organisations (just one for starters), but they need to be listed as a separate directory, so a separate model/controller etc seems cleanest and more flexible

3) We could, but I wouldn't see that as a priority, particularly at this stage.  We can always refactor later, or throw away and start again as you've mentioned.  Ultimately the key thing will be the phrasing the stakeholders use, and at the moment it's not clear where these particular field names sit.  What might be interesting is to look through https://www.kcsc.org.uk/self-care-directory and https://www.kcsc.org.uk/kcsc-directory working out what terminology in the current interface corresponds to the fields we have here, but I'd say the important things are really to work out how to get the "services" to sit nicely in the tabs, inherit geocodes from the organisations they are related to, i.e. everything we need to do to make "services" fit into the existing UI layout

Hope that helps.

**Comment by StlMaris123** [comment]
Thanks for the clarity @tansaku . @mattwr18 , I suggest we have a to do list since the tasks at hand seem a bit many. What do you think?

**Comment by mattwr18** [comment]
@StlMaris123  I agree! I think @tansaku  was talking of turning it into an epic with sub-tasks
I think he mentions a few things :point_up: that need to be done, for example there is a ticket to allow admins to show the Services or Volunteer tab, if they want.
Also, we have tickets for importing services, which should include the geocoding he mentioned :point_up:

**Comment by StlMaris123** [comment]
I  should close this since we already have a similar request

**Pull request closed without merging**
