### PR TITLE
Keep search result after admin login [Fixes #116115077]

### PR DESCRIPTION
**Pull request by Maroo-b**
This PR solves the issue mentioned in this ticket https://www.pivotaltracker.com/story/show/116115077

### CODE REVIEW

**Comment by tansaku** [comment]
great work @Maroo-b interesting slight drop of coverage here: https://coveralls.io/builds/6120800/source?filename=app%2Fcontrollers%2Fapplication_controller.rb#L99

**Comment by Maroo-b** [comment]
@tansaku I added a unit test for ApplicationController#set_flash_warning_reminder_to_update_details method

**Comment by tansaku** [comment]
thanks @Maroo-b - I might push some suggested refactorings for those hound comments.

I'm also wondering if we shouldn't be getting this coverage from our acceptance tests - I need to investigate our setup further ...

**Comment by Maroo-b** [comment]
@tansaku I wonder how we can fix hound comments because the reminder msg is considered long.

**Comment by tansaku** [comment]
@Maroo-b there's a number of ways to write Ruby multiline strings that we could use:

http://stackoverflow.com/questions/2337510/ruby-can-i-write-multi-line-string-with-no-concatenation

**Comment by Maroo-b** [comment]
@tansaku thanks for sharing, but actually hound in complaining about the length of the expectation line, I know it's possible to extract the method name to a variable but it will impact the readability factor.

**Comment by tansaku** [comment]
don't worry too much @Maroo-b but one approach there is to extract what you are passing to expect into an RSpec named subject: 

https://www.relishapp.com/rspec/rspec-core/docs/subject/explicit-subject

**Comment by Maroo-b** [comment]
@tansaku should I update the PR or it's ok for merging ?

**Comment by tansaku** [comment]
@Maroo-b I just updated locally to show you what I mean:

```ruby
    context '#set_flash_warning_reminder_to_update_details' do
      before(:each) do
        @org = FactoryGirl.create(:organisation, slug: 'my-org')
        @user = FactoryGirl.create(:user, organisation: @org)
        allow(@org).to receive(:has_been_updated_recently?).and_return(false)
      end

      subject(:set_flash) do
        controller.send(:set_flash_warning_reminder_to_update_details, @user)
      end

      context 'With existing warnings' do
        it 'appends reminder msg to existing flash warning' do
          flash[:warning] = 'Existing warning !'
          msg = 'Existing warning ! You have not updated your details in over a year!'\
            ' Please click <a href="/organisations/my-org/edit">here</a> to update now.'\
            "\n"
          expect(set_flash).to eq(msg)
        end
      end

      context 'Without existing warnings' do
        it 'returns reminder msg' do
          msg = 'You have not updated your details in over a year!'\
            ' Please click <a href="/organisations/my-org/edit">here</a> to update now.'\
            "\n"
          expect(set_flash).to eq(msg)
        end
      end

    end
```

I'll push into the branch I guess

**Comment by tansaku** [comment]
there are further refactorings that I'm thinking about here, but I think let's get this pulled in.

For reference my concerns (related to the broader project, not your work) are

1. string internationlisation - would be nice if the string constants were pulled out to i18n files
2. could the logic for the flash be made simpler?
3. should we perhaps prefer to test this kind of thing with an acceptance test where the description of the top level behaviour will be more readable ...

Anyway, we can made chores for the above, or reflect in retro about whether they are really necessary or helpful ...

**Pull request merged**
