### PR TITLE
152117874 add click through tracking

### PR DESCRIPTION
**Pull request by vardyb**
https://www.pivotaltracker.com/story/show/152117874

Tasks:

- [x] Database: Update user_id to be integer field in table click_throughs
- [x] Implement Tests
- [x] Update embedded map to use `link_to_and_track` helper
- [x] Fix code climate issues

### CODE REVIEW

**Comment by vardyb** [comment]
@tansaku  I've taken this as far as I can for now, but needs some further discussion with someone who knows LocalSupport code base better than I do, and also who has more rails knowledge than myself.

**Comment by tansaku** [comment]
great start here @vardyb 

it just occurred to me that we might also be able to outsource this work to google analytics:

https://www.theparticlelab.com/how-to-track-traffic-exiting-your-site/

but perhaps easier to do in-house as we are trying here.  Surprises me that Google Analytics doesn't just provide us with all this info by default ...

**Comment by vardyb** [comment]
@tansaku - hope you are having a great Christmas Break with your family.  Once you are back online in the new year can you please review this PR, at your convenience. I'm happy the new click through feature is working as expected and has sufficient tests.  All checks are passing.

**Comment by tansaku** [comment]
wonderful @vardyb - thanks so much - will review ASAP :-)

**Comment by tansaku** [comment]
A quick first pass over the code and this is looking good, although I do have one concern.   I note that the acceptance tests are checking that the correct link format appears and not that a ClickThrough has actually been stored, or am I misinterpreting the tests?

**Comment by vardyb** [comment]
@tansaku yes you are correct re the acceptance tests. However the rspec controller trsts do check that an entry is added to the database.

**Comment by tansaku** [comment]
aha, interesting division of labour - so the acceptance test is operating like a view spec and just checking the presentation layer, while the controller spec is an integration test (or request spec) checking that a change is made to the database ...

**Comment by vardyb** [comment]
@tansaku I've updated the cucumber tests to also check that the database is being updated as we discussed.  The new test pass on my local system but seem to be failing on Travis CI. I've run the builds a couple of times but still failing with:

```
cucumber -p second_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:47 # Scenario: Doit volunteer opportunities are opened in a new page
cucumber -p second_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:41 # Scenario: Reachskills volunteer opportunities are opened in a new page
```

Any ideas?

**Comment by tansaku** [comment]
hi @vardyb oops - sorry - missed this - looks like they're passing now ...?

**Comment by vardyb** [comment]
@tansaku thanks for the merge.  In yesterday's scrum you mentioned that on first look at the update you thought there were some things you would do differently.  Would be interested to understand more about this?  May be in today's scrum if we have time?

**Pull request merged**
