### PR TITLE
Email org admin when granted org admin rights

### PR DESCRIPTION
**Pull request by mtc2013**
PT: https://www.pivotaltracker.com/story/show/82318134

I interpreted this as applying only to users who already exist in the system since the other route is by invitation email which explains that they can administer their organisation after completing the invitational process.

Consider pulling this in after https://github.com/AgileVentures/LocalSupport/pull/172

### CODE REVIEW

**Comment by mtc2013** [comment]
@tansaku ready for review

**Comment by tansaku** [comment]
@mtc2013 more great work here - much appreciated.

More notes:

* feature looks good - some room for refactoring in email_steps.rb, maybe, not urgent for the set of changes in this specific pull request, but see #171

* update_attributes_with_superadmin gets even longer! :-)

* Room to extract the following into a parent class or a default method somwhere ... given it's presence across multiple mailers, e.g. org_admin_mailer.rb, admin_mailer.rb

```
      from: "support@harrowcn.org.uk",
      cc: "technical@harrowcn.org.uk",
      reply_to: "support@harrowcn.org.uk"
```

**Comment by mtc2013** [comment]
@tansaku merged with https://github.com/AgileVentures/LocalSupport/pull/172

**Comment by tansaku** [comment]
thanks @mtc2013 `update_attributes_with_superadmin` in organisation.rb looks much cleaner.  Would still like to know if we really need the transaction or not.  Ideally wouldn't we have a test checking whether all the functionality was correct and then we could try removing the transaction and see if it all still worked?

I also wonder about the class method on BatchInviteJob.  I see that's a convenience method for using the service, but I wonder if there is a best practice here regarding how we call services ...

**Comment by mtc2013** [comment]
@tansaku I had looked at some blog posts on services actually before writing it.  I'm not fully sure.  Most will cite the PORO with an initializer and then either a specifically named method, such as #deliver_email_to_client, or failing a specific name the generic #call.

But I did run across a blog post suggesting that people can and do use class methods, though the author didn't advocate for that, but I cannot find it again now.

**Comment by mtc2013** [comment]
@tansaku with some refactoring i was able to extract the utility method to its own service, create  result object for it, check for the error condition explicity, add a new spec for an error condition, and deal with the error without the transaction block anymore.

Look good to pull in?

**Comment by tansaku** [comment]
great effort here @mtc2013 

overall I'm getting a little confused between the pull requests - feels like refactoring that should be happening on #172 is being done on #173 - my fault for commenting on wrong pull request - not being able to respond faster to each individual pull request ...

Some thoughts anyway

SingleInvite --> SingleInviteJob?  or adjust BatchInviteJob to BatchInvite

if SingleInvite is a service it's `invite_user` method should be renamed `call` (or `run`)

http://brewhouse.io/blog/2014/04/30/gourmet-service-objects.html

relation between single invite and batch invite seems odd - shouldn't batch invite be re-using the single operation rather than the other way round?  I guess we can say inviting one person is a special case of batch inviting many, but it feels strange ...

**Pull request merged**
