### PR TITLE
email validation

### PR DESCRIPTION
**Pull request by samover**
Failing tests

### CODE REVIEW

**Comment by tansaku** [comment]
interesting, the failures are related to tests that invalid emails are handled correctly:

```
 AcceptProposedOrganisation proposed organisation has invalid email returns a notification sent result
     Failure/Error: let!(:proposed_org){FactoryGirl.create(:orphan_proposed_organisation, email: "invalidemail.com")}
     ActiveRecord::RecordInvalid:
       Validation failed: Email is invalid
     # ./spec/services/accept_proposed_organisation_spec.rb:96:in `block (3 levels) in <top (required)>'
```

**Comment by samover** [comment]
Both rspec and cucumber tests fail and have their root in `AcceptProposedOrganisation` which depends in turn on `InviteUnregisteredUserFromProposedOrg` and the `devise_invitable` gem (https://github.com/scambra/devise_invitable) 

This is one of the failing tests in cucumber `admin_moderate_proposed_organisations.feature:49` :
```Ruby
Scenario: Invalid email garners message when superadmin accepts proposed organisation
Given the following proposed organisations exist:
 | name       | description             | address        | postcode | telephone | website               | email    | donation_info        | non_profit |
| Unfriendly | Mourning loved ones     | 30 pinner road | HA5 4HZ  | 520800000 | http://unfriendly.org |  xyt     | www.pleasedonate.com | true       |
And having accepted the proposed organisation named "Unfriendly", I see "No invitation email was sent because the email associated with Unfriendly, xyt, seems invalid"
```
With email validation in place for base_organisation, it follows that this tests fails:
```bash
Scenario: Invalid email garners message when superadmin accepts proposed organisation                                                                                     # features/admin/admin_moderate_proposed_organisations.feature:49
    Given the following proposed organisations exist:                                                                                                                       # features/step_definitions/factory_steps.rb:1
      | name       | description         | address        | postcode | telephone | website               | email | donation_info        | non_profit |
      | Unfriendly | Mourning loved ones | 30 pinner road | HA5 4HZ  | 520800000 | http://unfriendly.org | xyt   | www.pleasedonate.com | true       |
      Validation failed: Email is invalid (ActiveRecord::RecordInvalid)
      ./features/step_definitions/factory_steps.rb:16:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/factory_steps.rb:3:in `each'
      ./features/step_definitions/factory_steps.rb:3:in `/^the following proposed organisations exist:$/'
      features/admin/admin_moderate_proposed_organisations.feature:50:in `Given the following proposed organisations exist:'
    And having accepted the proposed organisation named "Unfriendly", I see "No invitation email was sent because the email associated with Unfriendly, xyt, seems invalid" # features/step_definitions/moderate_proposed_organisation_steps.rb:9
```

A possible solution - I thought - is to force the registration of orgs with invalid emails in these specific tests (`validate: false`). This leads to a following error: 
```bash
And having accepted the proposed organisation named "Unfriendly", I see "No invitation email was sent because the email associated with Unfriendly, xyt, seems invalid" # features/step_definitions/moderate_proposed_organisation_steps.rb:9
      Validation failed: Email is invalid (ActiveRecord::RecordInvalid)
      ./app/models/proposed_organisation.rb:5:in `accept_proposal'
      ./app/services/accept_proposed_organisation.rb:24:in `run'
      ./app/controllers/proposed_organisations_controller.rb:12:in `update'
      ./features/support/helpers.rb:76:in `press_acceptance_for_proposed_organisation'
      ./features/step_definitions/moderate_proposed_organisation_steps.rb:11:in `/^having accepted the proposed organisation named "(.*?)", I see "(.*?)"$/'
      features/admin/admin_moderate_proposed_organisations.feature:53:in `And having accepted the proposed organisation named "Unfriendly", I see "No invitation email was sent because the email associated with Unfriendly, xyt, seems invalid"'
```

Any thoughts?

**Comment by tansaku** [comment]
you're exploring in a good way - I'd be tempted to get the other pull requests sorted with "shoulda" before spending more time on this one ...

**Comment by samover** [comment]
yes. did that this morning

**Comment by tansaku** [comment]
@samover awesome - apologies I missed those updates - have just merged in

**Comment by tansaku** [comment]
so back to emails - I like your approach "A possible solution - I thought - is to force the registration of orgs with invalid emails in these specific tests (validate: false). " - can you push that into the branch so I can look at the error in more detail - I think we may have to restructure the flow of one the feature tests ... and as this gets deeper it might be easier to pair to make progress compared to working through the medium of pull requests, but let's see ...

**Comment by tansaku** [comment]
@samover we'll come back to this once we've sorted the name and description validations

**Comment by tansaku** [comment]
@samover for this one I guess you're waiting for the URL validation to be merged first?

**Comment by samover** [comment]
This one remains. I removed what I believe to be superfluous tests, but second opinion is requested.
Furhter, the remaining failing cucumber tests I don't understand. When I run them indiviuduall they pass, but when I run the whole testfile they fail ?!

**Comment by tansaku** [comment]
@samover want to try rebasing first - this branch is in conflict ...

**Comment by samover** [comment]
why is CI is not running on this pull request?

**Comment by tansaku** [comment]
@samover because it has unresolved merge conflicts

**Comment by tansaku** [comment]
hey @samover let me know if you can merge this or if I should sort it out.

Also I guess we didn't get to any client side validations?  Not a problem - just checking if we need to release this related ticket back into the available pool:

https://www.pivotaltracker.com/story/show/62111296

**Comment by samover** [comment]
I don't have much time this week + I don't know what is wrong. I tried rebasing but it doesn't seem to work. If you can do it quickly, please go ahead.

Client-side validations: are they necessary or feature creep? Seems like server side validation does the job with flash notifications.

**Comment by tansaku** [comment]
will do it now

and yes, maybe client side validations are feature creep - the client has not explicitly requested them and the original ticket was created by @johnnymo87 with the text:

> After server side validation is implemented, it will be important to have client side validations too so that we don't throw out user data without informing them.

which is true in the general sense, but I'm not sure about it's relative priority, or how it will interact with the legacy browsers we hope to support, or distract us from other things that might be more important.

But since you started on that side of things I wondered if you had some code from getting that working previously that might be of use.  At least it would be good to see it before it gets thrown away.

We don't have a strong emphasis from client insisting on their being validations on either client or server side; although she's perfectly happy with the idea of having them and perhaps this is all important stuff to get in place ...   Can you tell I'm conflicted? :-)

There's a bigger HCI story here I could tell you over a beer sometime ... :-)

**Comment by tansaku** [comment]
@samover I'm going to go ahead and close this now we have #259  - feel free to re-open if you want to post any outstanding code you have ...

**Pull request closed without merging**
