### PR TITLE
Popup fix

### PR DESCRIPTION
**Pull request by mtc2013**
This will make the popups on the organisation map come out the bottom rather than the top so that they are consistent.  On production, we have a situation where organisations with long names take up two lines and so the popup icon obscures the organisation marker.

By making the marker come out the bottom, we can get a more uniform look for the time being until we figure out a better solution to make it come out the top, if that is indeed what is wanted.

Staged here:
https://marian-localsupport.herokuapp.com/

### CODE REVIEW

**Comment by mtc2013** [comment]
Perhaps the vertical adjustment should differ between volops, large orgs and small orgs.

**Comment by mtc2013** [comment]
Changes pushed to better control offsets.  It's arguable if we need a factory now that the type doesn't affect two places of code but it also internalizes the switching logic into the factory rather than its client code.  

Changes also staged for preview on same link above.

**Comment by tansaku** [comment]
can't argue much with any of this - is this still RFC or ready to go?

**Comment by mtc2013** [comment]
It's ready to go now!

**Comment by tansaku** [comment]
out of interest are we using coffeescript out of preference? or just that it's to hand?

**Pull request merged**
