### PR TITLE
default org solves#157115605

### PR DESCRIPTION
**Pull request by StlMaris123**
This pr provides the default organization if current user has one on event creation
Link to story: https://www.pivotaltracker.com/n/projects/742821/stories/157115605

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @StlMaris123 this is great :-)

Would you be willing to adjust the PR according to our contribution guidelines? https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#pull-requests so that we have a link to the Pivotal Tracker ticket in the PR description?

Also if you're finished it would be great to include a commit message that will ensure the relevant PT ticket will close when we merge: https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#git-comments

Many thanks in advance :-)

**Comment by tansaku** [comment]
I also made some minor formatting updates

**Comment by StlMaris123** [comment]
Hi @tansaku , you changed the class name organization into lower case, might that be a typo?

**Comment by tansaku** [comment]
thanks for fixing that @StlMaris123 

btw would you be willing to adjust the PR according to our contribution guidelines? https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#pull-requests so that we have a link to the Pivotal Tracker ticket in the PR description?

You can edit the PR description directly ... let me know if you need help working out what to do :-)

Many thanks in advance

**Comment by tansaku** [comment]
great work @StlMaris123 - thanks for this :-)

**Pull request merged**
