### PR TITLE
add changes for successful setup

### PR DESCRIPTION
**Pull request by okothkongo1**
Making changes on docker file by specifying exact ruby version(2..5.1)
add a new file  app/assets/javascripts/google_maps/google-infobox.js
made changes on map.js file

related to https://www.pivotaltracker.com/story/show/162410923 ?

### CODE REVIEW

**Comment by okothkongo1** [comment]
thank you guys let me look into the issues raised

**Comment by okothkongo1** [comment]
@mattwr18  create a ticket for removing mentions of bower and removing npm

**Comment by tansaku** [comment]
@mattwr18 @okothkongo1 how are we doing here? what are the next steps?

**Comment by mattwr18** [comment]
I have not pulled it down locally to see if it's working... there are still some changes unrelated to the ticket, the documentation changes @FedericoEsparza made, but I'm not sure why they are showing up here since they have been merged in, right @tansaku?

**Comment by tansaku** [comment]
there presence may be a function of rebasing and the way @okothkongo1 has updated his local branches

**Comment by tansaku** [comment]
@okothkongo1 closing this as I think you've replaced with https://github.com/AgileVentures/LocalSupport/pull/934

**Pull request closed without merging**
