### PR TITLE
Upgrade to ruby 2.3.0

### PR DESCRIPTION
**Pull request by johnnymo87**
```
$ \curl -sSL https://get.rvm.io | bash -s stable
$ rvm reload
$ rvm install ruby-2.3.0
$ mv .rvmrc .rvmrc.backup
$ echo "rvm use 2.3.0@localsupport --create" > .rvmrc
$ cd ../LocalSupport
<Accept prompt from RVM>
$ gem install bundler
$ bundle install
```

### CODE REVIEW

**Comment by tansaku** [comment]
@johnnymo87 thanks - for the CI to pass I think the .travis.yml needs to change as well

**Comment by tansaku** [comment]
@johnnymo87 this looks good now - at least tests are green - have you tested manually?

I guess we should get this out and deployed soon ...

**Comment by tansaku** [comment]
@C9905557 notes that 2.2.1 is the default ruby version on c9 - maybe we should go there first?

**Comment by johnnymo87** [comment]
OK, let's go with 2.2.1 then. Updated.

**Comment by C9905557** [comment]
Hem, I am somewhat embarassed because I told Sam about the Ruby version on Cloud9. But this was the version available in my workspace for LocalSupport that I created a few month ago. I had a second tought: are the version updated for the existing C9 workspaces? To verify, I just created this morning a new ruby workspace, and must conclude that they are not updated in existing workspaces. I have the following list of available ruby versions in the new workspace:

````
c9905557:~/workspace $ rvm list
rvm rubies
   ruby-1.9.3-p551 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.2.4 [ x86_64 ]
=* ruby-2.3.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
c9905557:~/workspace $ 
```

Ruby version 2.2.1 is no longer pre-installed in a new workspace. Current version is 2.3.0. Better stick to it and revert back this upgrade to 2.3.0.

I apologize for this confusion, and any extra work it may have caused.

**Comment by tansaku** [comment]
back to 2.3.0 then @johnnymo87 ?

**Comment by johnnymo87** [comment]
OK, I set it back to 2.3.0

**Comment by tansaku** [comment]
now we have the volops code pulled in - hoping to ensure this gets pulled in this week ...

**Comment by tansaku** [comment]
interesting some new STDOUT warnings with ruby 2.3:

```/Users/tansaku/Documents/Github/AgileVentures/LocalSupport/app/views/organisations/_form.html.erb:85: warning: key :rows is duplicated and overwritten on line 85```

**Comment by tansaku** [comment]
aha, looks like an easy fix:

```ruby
      <%= text_field_tag 'organisation_superadmin_email_to_add', value = nil, {:size => 100, class: 'wide_form', :cols => "10", :rows => "3", :placeholder => 'You may add an organisation administrator email here', :rows => "3" } %>
```

thanks Ruby 2.3!

**Comment by tansaku** [comment]
@johnnymo87 I note I don't have a .rvmrc file - what do you have in yours?

**Comment by johnnymo87** [comment]
I have what is echoed in there. I'm doing the `mv` step just as a
precaution. If it fails, everything else will still work.

**Comment by tansaku** [comment]
ah, okay, sorry I should have looked more closely - you are working with a specific gemset for localsupport?

**Comment by johnnymo87** [comment]
Yeah, I always scope my gemsets to project.

**Comment by tansaku** [comment]
@johnnymo87 cool - I've seen that functionality but never used in projects - what benefits have you found?

**Comment by dcorking** [comment]
@tansaku I used project-scoped gemsets to blow away the gems from discarded and upgraded projects, and reclaim gigabytes of disk space.

**Comment by johnnymo87** [comment]
Adding to what @dcorking said, I sometimes want to nuke a gemset and rebuild it if my dependencies are acting strangely, and it's nice to know that this won't have an impact on any of my other projects.

**Comment by tansaku** [comment]
interesting points @johnnymo87 and @dcorking

So this command is sufficient to create the gemset then:

```
rvm use 2.3.0@localsupport --create
```

and having it in the .rvmrc ensures it's use - and if we had that in version control then everyone would have their own gemset automatically as a sideeffect ...?

**Comment by johnnymo87** [comment]
I've never had `.rvmrc` in version control, but I don't see why we shouldn't. (I like how we have our `config/database.yml` in version control.) I'll add it to the PR. We can always remove it if we discover it's causing issues for devs.

**Pull request merged**
