### PR TITLE
[WIP] First try spiking initial button

### PR DESCRIPTION
**Pull request by mtc2013**
Staged here:
https://small-icons.herokuapp.com/

Sign in as blah@blah.org and password asdf1234.  Navigate to an org other than the one you are associated with and see the new "Propose an edit" button in lieu of an edit button.

### CODE REVIEW

**Comment by tansaku** [comment]
good start - have we looked at the acts_as_versioned gem

**Comment by mtc2013** [comment]
@tansaku No, we'll have to investigate it.

**Comment by tansaku** [comment]
@mtc2013 not sure which is the best option with rails 4 now: https://www.ruby-toolbox.com/categories/Active_Record_Versioning

**Comment by mtc2013** [comment]
Closing this since the commit history got weird.

**Pull request closed without merging**
