### PR TITLE
Search feature on each organization page (Jongmin & Yana)

### PR DESCRIPTION
**Pull request by jongmin141215**
As @tansaku suggested (#205), I tried to send this pull request from my feature branch. Maybe I should have sent it to the search_feature branch in AgileVentures. Also, I added a feature flag for search feature on each organization page. 

To activate the search feature on each organization page, you need to add it to the database in your rails console (or your Heroku or ninefold console):
```
$ Feature.create(:name => :search_input_bar)
```
When you add it, it remains off by default. To turn it on, run:
```
$ Feature.activate(:search_input_bar)
```
Then you can see the search feature on each organization page like below. 

screen shot 2015-12-09 at 1 07 24 pm

If you want to remove the feature, run: 
```
$ Feature.deactivate(:search_input_bar)
```
screen shot 2015-12-09 at 1 14 02 pm

### CODE REVIEW

**Comment by tansaku** [comment]
great work @jongmin141215 - this is just right - sending from your feature branch to the main develop branch - I'll look at this in more detail soon

**Comment by tansaku** [comment]
working good for me locally - two tips:

1) perhaps we should call the feature :search_input_bar_on_org_pages since that more accurately reflects the feature
2) perhaps we should add a migration that adds the feature to the database, so there is one less manual step for deployment?

**Comment by jongmin141215** [comment]
Thank you for your feedback. I'll change the feature name and add a migration.

**Comment by jongmin141215** [comment]
1) Changed the feature name to :search_input_bar_on_org_pages. 
2) Added a migration that adds the feature to the features table. 

To activate the feature, run: 
```
$ Feature.activate(:search_input_bar_on_org_pages)
```
You can skip this step below.
```
$ Feature.activate(:search_input_bar_on_org_pages)
```

**Pull request merged**
