### PR TITLE
Undo delete

### PR DESCRIPTION
**Pull request by mtc2013**
This will allow the client to undo any accidental deletions of users

https://www.pivotaltracker.com/story/show/85129162

### CODE REVIEW

**Comment by tansaku** [comment]
cool - LGTM?

makes me want to get back to the refactoring of the user reports controller

**Comment by mtc2013** [comment]
Rachel said she liked the look of this.

**Comment by tansaku** [comment]
great - ah LGTM - looks good to me :-) is this then ready to be pulled in?

**Comment by mtc2013** [comment]
yes

**Pull request merged**
