### PR TITLE
162410923 google infobox

### PR DESCRIPTION
**Pull request by okothkongo1**
created vendor/assets/javascripts/google-infobox.js 
modified app/assets/javascript/maps.js

### CODE REVIEW

**Comment by tansaku** [comment]
hi @okothkongo1 - so @mattwr18 and I were reviewing this yesterday and noticed that it is failing the front end jasmine tests.  You can see those failures via [this link](https://travis-ci.org/AgileVentures/LocalSupport/builds/467571323?utm_source=github_status&utm_medium=notification) but here's a summary for your convenience:

```
 USE_JASMINE_RAKE=true bundle exec rake jasmine:ci
Puma starting in single mode...
* Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
* Min threads: 0, max threads: 16
* Environment: test
* Listening on tcp://0.0.0.0:41922
Use Ctrl-C to stop
Waiting for server on 127.0.0.1:41922...
jasmine server started
......................FF.*..
Failures:
Organisation map when hovering the pointer over an organisation and the organisation have valid coordinates gets organisation coordinates
  Message:
      ReferenceError: Can't find variable: InfoBox in http://127.0.0.1:41922/assets/maps.self-b52c11138b8dc30a68a564f9871a998bfae82dc93789c1dae294b8c95e7903e6.js?body=1 (line 29)
  Stack:
      initMap@http://127.0.0.1:41922/assets/maps.self-b52c11138b8dc30a68a564f9871a998bfae82dc93789c1dae294b8c95e7903e6.js?body=1:29:25
      http://127.0.0.1:41922/__spec__/organisation_map_spec.js:5:28
      <Jasmine>
  Message:
      Error: <toHaveBeenCalled> : Expected a spy, but got Function.
Usage: expect(<spyObj>).toHaveBeenCalled() in http://127.0.0.1:41922/__jasmine__/jasmine.js (line 4412)
  Stack:
      <Jasmine>
      http://127.0.0.1:41922/__spec__/organisation_map_spec.js:31:69
      <Jasmine>
Organisation map when hovering the pointer over an organisation and the organisation have invalid coordinates does not get organisation coordinates
  Message:
      ReferenceError: Can't find variable: InfoBox in http://127.0.0.1:41922/assets/maps.self-b52c11138b8dc30a68a564f9871a998bfae82dc93789c1dae294b8c95e7903e6.js?body=1 (line 29)
  Stack:
      initMap@http://127.0.0.1:41922/assets/maps.self-b52c11138b8dc30a68a564f9871a998bfae82dc93789c1dae294b8c95e7903e6.js?body=1:29:25
      http://127.0.0.1:41922/__spec__/organisation_map_spec.js:5:28
      <Jasmine>
  Message:
      Error: <toHaveBeenCalled> : Expected a spy, but got Function.
Usage: expect(<spyObj>).toHaveBeenCalled() in http://127.0.0.1:41922/__jasmine__/jasmine.js (line 4412)
  Stack:
      <Jasmine>
      http://127.0.0.1:41922/__spec__/organisation_map_spec.js:20:73
      <Jasmine>
Pending:
	gem bootstrap_sortable_rails when clicking on the tableheader sorts Z-A
	  Temporarily disabled with xit
28 specs, 2 failures, 1 pending spec
Randomized with seed 60225 (rake jasmine:ci[true,60225])
The command "USE_JASMINE_RAKE=true bundle exec rake jasmine:ci" exited with 1.
```

**Comment by tansaku** [comment]
we'll need these to pass before we can merge - I'm not sure how familiar you are with jasmine - please reach out if you need some help.

Maybe start by running it locally to replicate the errors.

@mattwr18 and I were wondering if we need the function wrapping you've used and maybe that's part of the problem?

It's great that you've got the code in vendor (which is the right place for it) but Matt was saying the build passed if it was the assets directory.  In the last resort we can move it back, but the cleaner fix is probably to make sure that jasmine can load in files from the vendor directory.

**Comment by tansaku** [comment]
@okothkongo1 I guess you've given up on this and we'll pass on to someone else?

**Comment by okothkongo1** [comment]
@tansaku let me take a look at it locally, am not that conversant with
jasmine I  may need @mattwr18 help with that

**Comment by okothkongo1** [comment]
@tansaku let me take a look at it locally, am not that conversant with
jasmine I  may need @mattwr18 help with that

**Pull request merged**
