### PR TITLE
Post our volunteer ops to Do-it via API key

### PR DESCRIPTION
**Pull request by Maroo-b**
Addresses: https://www.pivotaltracker.com/story/show/139801559

- add new model for tracing published vol ops to Doit
- add 2 services to interact with Doit API
- add form object to manage posting to Doit
- implement active_job with sucker_punch as backend to avoid extra cost from Heroku

### CODE REVIEW

**Comment by tansaku** [comment]
Great start @Maroo-b - wonderful to see the cucumber scenarios :-)

**Comment by tansaku** [comment]
all good here @Maroo-b ? want to direct my attention to anything?

**Comment by Maroo-b** [comment]
@tansaku I added the reeequired implementation (check the PR description for a quick list of changes) 
for the moment I need maybe 1 or 2 extra commit for refactoring.

Also we have to manage the ENV variables for sharing with developers and making the build CI pass.

**Comment by tansaku** [comment]
thanks @Maroo-b  - I'll try to take a closer look very soon

**Comment by tansaku** [comment]
@Maroo-b I get the following failure locally:

```
    And I fill additional fields required by Doit                                             # features/step_definitions/volunteer_op_steps.rb:112
      undefined method `strip' for nil:NilClass (NoMethodError)
      ./app/services/doit/get_managed_organisations.rb:43:in `block in each'
      ./app/services/doit/get_managed_organisations.rb:42:in `loop'
      ./app/services/doit/get_managed_organisations.rb:42:in `each'
      ./app/services/doit/get_managed_organisations.rb:27:in `find_all_accross_pages'
      ./app/services/doit/get_managed_organisations.rb:13:in `call'
      ./app/services/doit/get_managed_organisations.rb:9:in `call'
      ./app/controllers/doit_organisations_controller.rb:5:in `index'
      features/volunteer_opportunities/post_to_doit.feature:26:in `And I fill additional fields required by Doit'
    And I press "Publish to Doit"                                                             # features/step_definitions/navigation_steps.rb:125
    Then I should see "Volunteer opportunity was published successfully to Doit" in the flash # features/step_definitions/navigation_steps.rb:191

  Scenario: Organisation admin can't publish to Doit                           # features/volunteer_opportunities/post_to_doit.feature:30
    Given I am signed in as a charity worker related to "Cats Are Us"          # features/step_definitions/authentication_steps.rb:1
    And I visit the show page for the volunteer_op titled "Litter Box Scooper" # features/step_definitions/navigation_steps.rb:89
    Then I should not see a link with text "Publish to Doit"                   # features/step_definitions/basic_steps.rb:310

Failing Scenarios:
cucumber features/volunteer_opportunities/post_to_doit.feature:22 
```

**Comment by tansaku** [comment]
got the interface up locally - great work getting this far: 



you'll need to talk me through the options we have for authentication ...

**Comment by Maroo-b** [comment]
@tansaku I'll check the failing test locally, maybe it's related to missing ENV keys.

For the authentication we are using X-API-KEY for admin users only ( no need to submit email and password)

**Comment by Maroo-b** [comment]
@tansaku I did some refactoring and improved the form of posting to Doit

There is a conflict with db/schema.rb should we use the web editor to fix it ?

Regarding the impact of this features:
- we should think how we pull volunteer op from Doit to avoid pulling local vol ops (synchronization)

In general:
- A refactoring on authorization should be considered 
- The flash alert for bootstrap should be checked.

**Comment by tansaku** [comment]
great progress @Maroo-b - I'll try to review ASAP

**Comment by tansaku** [comment]
huge load of great work here @Maroo-b - I've reviewed as part of my daily blog draft - apologies if this is difficult to follow, but the details are here:

https://github.com/AgileVentures/av-static-website/blob/pullrequest_feedback_by_blog/source/blog_articles/2017-03-23-pullrequest-feedback-by-blog.html.markdown

I'm thinking that maybe the two forms should be integrated rather than a separate one for doit and for volops updating - see my (very rough) mockup at the end of the blog - what do you think?

And apologies for not providing a mockup earlier in the process ...

**Comment by Maroo-b** [comment]
@tansaku thank you for the review, I went through the notes on the blog draft. 

Regarding the utility of some new files, I'll explain using the implemented scenario:
1- Admin click on "Publish to Doit"
-> the form will be loaded with a spinner for the list of managed organisations.
-> doit_volunteer_ops.js will be activated on this form only via a config learned from [blog](http://brandonhilkert.com/blog/page-specific-javascript-in-rails/) 
-> doit_volunteer_ops.js will send an async request to DoitOrganisationsController which in response update the form with a dropdown  of managed orgs and enable the submit button via (oit_orgs index.js.erb )
2- admin fill form and click submit button
-> the form validation will be done via DoitVolunteerOp form object used mainly for validation, create new trace and start the post job


Regarding the new mockup, I understand that to post to Doit the admin should visit update form then check box "Publish to Doit" to see the new required fields. If the client prefers using a single form for both updating and publishing to Doit it will require some additional modification on the form object.

So about travis-ci I saw that it's possible to add encrypted env keys to travis.yml file ([source](https://docs.travis-ci.com/user/environment-variables/)) did you try another approach before ?

**Comment by Maroo-b** [comment]
@tansaku develop branch merged :)

**Comment by tansaku** [comment]
hi @Maroo-b sorry for delay on this - really busy with NHS project - hope to catch up soon - but am off next week so might be another 10 days or so ...

**Comment by tansaku** [comment]
hi @Maroo-b - encrypted vars in travis.yml is good, but we've also put them in through the Travis interface I think ... probably travis.yml is best?

I think I need to show the interface options to the client - hopefully in the next week.  I have a feeling she won't mind either way, but I suspect that a single form rather than multiple will be easier for end users.  It's my fault - I should have given you an interface mockup to work off.

In the meantime do you want to have a look through the 33 codeclimate issues and see if any of them are easy fixes?

**Comment by Maroo-b** [comment]
Hi @tansaku thank you for the update.

Probably setting vars through Travis interface will be optimal :) 

I'll check the code climate issues and I'll try to submit a fix this weekend.

**Comment by tansaku** [comment]
@Maroo-b thanks so much :-)

I also met with client on Friday and she would prefer a single page form, and also it needs to be the case that only an org can submit to doit for their org, e.g. only VAH admins can submit VAH org (on Doit) volops to doit.  Only Hope Harrow admins can submit Hope Harrow org (on Doit) volops to doit etc.

Will try to give you more info on monday - client meeting video should be in slack channel assuming it recorded correctly

**Comment by Maroo-b** [comment]
@tansaku the recording was interrupted after 12 mn :/ 

Anyway the dropdown displays only the organisations that the admin ( based on X-API-Key) can manage on Doit (it's possible that a Doit user manage multiple organisations )

This PR addresses only the case of admin posting to Doit, so to display the related organisations for each logged in users we need to have their Doit credentials (as we discussed before there is no OAuth authentication from Doit side).

**Comment by Maroo-b** [comment]
@tansaku I was thinking about using [Mechanize](https://github.com/sparklemotion/mechanize) gem as alternative or other solutions to auto fill the creating form on Doit side. But it seems that it's not possible to create an account on QA server. 
Do you have other suggestions or should we ask if users are willing to share their Doit credentials ?

**Comment by tansaku** [comment]
@Maroo-b shall we focus on just setting this up for the admin of VAH to post their ops to VAH do-it account in the first instance?  If we can hard code it for our one main client, then we can see where to go from there.

DoIt aren't providing any Oauth or similar?

**Comment by Maroo-b** [comment]
@tansaku thank you for the feedback,

From the API [documentation ](http://docs.doit.apiary.io/#reference/authentication) there is only 2 authentication mode, for this PR we are using the X-API-KEY to identify the admin account.

So for this PR, I assume that the client wants to access the post to Doit function from the edit form ? Do you have any other notes to add because the record was broken :/ 

Could you please add the shared ENV keys to travis dashboard ? 

thanks :)

**Comment by tansaku** [comment]
@Maroo-b sorry for not following up with this - super busy with NHS project

I keep failing to wrap my head around all this ...

Can you send me a link on slack DM to the place I need to go to get the shared ENV keys ...? thanks :-)

**Comment by tansaku** [comment]
@Maroo-b I added those env vars on travis - what's the next step?

**Comment by Maroo-b** [comment]
thanks  @tansaku for updating the env vars on travis, I did integrate the post to Doit to volunteer op form for both create and update actions, I need to do some checks before updating the PR.

**Comment by Maroo-b** [comment]
@tansaku PR updated, it seems there is an issue with env var on travis.

**Comment by tansaku** [comment]
@Maroo-b that's strange - they're all set:

travis ENV vars

**Comment by tansaku** [comment]
I see the specific errors are:

```
 1) Doit::PostToDoit.call create a volunteer op in Doit
     Failure/Error: http_adapter.post("#{ENV["DOIT_HOST"]}#{doit_volonteer_op_resource}", options)
     
     NoMethodError:
       undefined method `strip' for nil:NilClass
     # ./app/services/doit/post_to_doit.rb:22:in `call'
     # ./app/services/doit/post_to_doit.rb:13:in `call'
     # ./spec/services/doit/post_to_doit_spec.rb:13:in `block (3 levels) in <module:Doit>'
  2) Doit::GetManagedOrganisations.call returns list of managed organisation from Doit
     Failure/Error: response = http.get("#{ENV['DOIT_HOST']}#{organisations_resource}", options)
     
     NoMethodError:
       undefined method `strip' for nil:NilClass
     # ./app/services/doit/get_managed_organisations.rb:44:in `block in each'
     # ./app/services/doit/get_managed_organisations.rb:43:in `loop'
     # ./app/services/doit/get_managed_organisations.rb:43:in `each'
     # ./app/services/doit/get_managed_organisations.rb:30:in `find_all_accross_pages'
     # ./app/services/doit/get_managed_organisations.rb:16:in `call'
     # ./app/services/doit/get_managed_organisations.rb:12:in `call'
     # ./spec/services/doit/get_managed_organisations_spec.rb:13:in `block (3 levels) in <module:Doit>'
```

**Comment by tansaku** [comment]
do these all pass locally?  I notice some odd spellings, e.g. `doit_volonteer_op_resource` volunteer is usually spelt with a "u".  Could you confirm that these all pass locally, and if they do, open a support ticket with travis themselves?  they are usually pretty good at supporting those:

https://github.com/travis-ci/travis-ci/issues/new

**Comment by Maroo-b** [comment]
@tansaku the tests are passing locally, I did some tests and I can confirm that the issue is related to `ENV['X-AUTH-TOKEN']` [link](https://github.com/AgileVentures/LocalSupport/pull/427/files#diff-0412348f5f1daa1c1d01bb166a471e00R19)
with fake value the tests are passing, is it possible to check if there is extra whitespace for `ENV['X-AUTH-TOKEN']` value ?

**Comment by tansaku** [comment]
@Maroo-b I can't review, but I can delete and replace, which I've done

**Comment by tansaku** [comment]
and ideally you'd be able to edit these things yourself ... maybe if I give you admin rights to the LocalSupport repo?

**Comment by tansaku** [comment]
Hmm, you already have admin rights ... can you not access https://travis-ci.org/AgileVentures/LocalSupport/settings ?

maybe you need to be some sort of AV admin?

**Comment by tansaku** [comment]
if you can't maybe open a ticket at: https://github.com/travis-ci/travis-ci/issues/new

**Pull request closed without merging**
