### PR TITLE
164910543 white label banner wip

### PR DESCRIPTION
**Pull request by ciremoussadia**
@mattwr18  i moved some logic out of css. Now the problem is between large screen and mobile. Can u test this in production or staging first?

Addresses https://www.pivotaltracker.com/n/projects/742821/stories/164910543

### CODE REVIEW

**Comment by tansaku** [comment]
thanks for this @ciremoussadia  - testing locally I get the following:



and this error in the log:

```
Started GET "/images/no%20image" for ::1 at 2019-05-06 15:02:41 +0100
  
ActionController::RoutingError (No route matches [GET] "/images/no%20image"):
```

I think rather than putting something in the application helper @mattwr18 and I had been thinking that we would put some inline css in the layouts as we were reading about on stackoverflow:

https://stackoverflow.com/a/13944275/316729

and that might allow us to maintain the mobile support?

**Comment by ciremoussadia** [comment]
ok @tansaku let me try that and see.

**Comment by tansaku** [comment]
how's this going @ciremoussadia ?

Looking through it we will need some change to the banner for the current project.  When I was saying in the scrum that mobile wasn't critical I meant for the new client.  We do need to be able to at least remove the banner, and support the old mobile banner for the existing site.

**Comment by ciremoussadia** [comment]
@tansaku I'm still struggling to find the best way to support it. I also don't understand why it didn't work for you. Maybe if u have time we can pair and try to figure it out?

**Comment by mattwr18** [comment]
could you upload a couple screen shots @ciremoussadia?

**Comment by ciremoussadia** [comment]
@mattwr18  here they are.

Capture d’écran 2019-05-10 à 17 32 23
Capture d’écran 2019-05-10 à 17 32 35

**Pull request merged**
