### PR TITLE
Add more users linked to organisations to seeds

### PR DESCRIPTION
**Pull request by tansaku**
Addresses: https://www.pivotaltracker.com/n/projects/742821/stories/120210043

### CODE REVIEW

**Comment by tansaku** [comment]
so weird here, we get one of the two Travis builds failing and not the other - one of them is the build of the branch and the other is the build of the merge to develop apparently.  The failure we are getting is:

```
    When I sign up as "normal_user@myorg.com" with password "pppppppp" and password confirmation "pppppppp"                                    # features/step_definitions/authentication_steps.rb:27
      expected not to find css "#signup", found 1 match: "" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/authentication_steps.rb:42:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/authentication_steps.rb:42:in `/^I sign up as "(.*?)" with password "(.*?)" and password confirmation "(.*?)"( on the legacy sign up page)?$/'
      features/individual_charity_pages/this-is-my-org.feature:57:in `When I sign up as "normal_user@myorg.com" with password "pppppppp" and password confirmation "pppppppp"'

Failing Scenarios:
cucumber features/individual_charity_pages/this-is-my-org.feature:54 
```

which I've seen before - that's an intermittent js failure ... hmm

**Comment by tansaku** [comment]
In the first instance I'll restart the build ...

**Comment by tansaku** [comment]
that fixed it, but now coverage is down - that used to be an indicator that we have a concealed fail ... although not this time - maybe just coveralls being weird ...? only change here is to seed file - that shouldn't affect coverage ...

**Comment by Maroo-b** [comment]
@tansaku maybe we should pull the last changes to this PR to verify the coverage ?

The PR seems good except we are requiring to have organisations count to be >= 5 * users count, for the moment it's ok because we seed more than 1000 organisations.

**Comment by tansaku** [comment]
@Maroo-b sorry - not sure what you mean by 

> we should pull the last changes to this PR to verify the coverage

I re-ran the CI and the coverage stayed stable this time, although one of the builds failed with an intermittent js failure ...

**Comment by tansaku** [comment]
regarding that `i*5` yeah, we could make that `Organisation.all.sample.id` instead to make it more robust

**Comment by Maroo-b** [comment]
So restarting the build was enough to fix the coverage :) 
I thought that the branch submitted does not have the last changes merged in develop branch.

**Comment by tansaku** [comment]
I wonder if we need some sort of acceptance test for this. Here's a related ticket on that: https://www.pivotaltracker.com/story/show/113909345

**Pull request merged**
