### PR TITLE
changes to migration scripts for adding feature flags during migration

### PR DESCRIPTION
**Pull request by RajeevHejib**
These changes cover adding existing feature flags during migration [Fixes #98374700].

### CODE REVIEW

**Comment by RajeevHejib** [comment]
Travis CI was failing on 20140507165854_create_features.rb migrate script.  While doing rollback it first dropped the table and then tried deleting features - which failed as it dropped table first and then tried deleting its contents!  At the moment I have commented out the part where it delete features as I think in rollback when it removes the table then deleting features is redundant.

**Comment by tansaku** [comment]
@RajeevHejib thanks for this - you need to point the pull request to the AgileVentures develop branch - not the feature branch.  Makes sense?

**Comment by RajeevHejib** [comment]
@tansaku redone the pull request.  Hope its the right way this time.

**Comment by tansaku** [comment]
great thanks - I'll close this on then ...

**Pull request closed without merging**
