### PR TITLE
[WIP] 68370622 Update twitter-bootstrap-rails

### PR DESCRIPTION
**Pull request by bryszard**
Refers to PT - https://www.pivotaltracker.com/story/show/68370622

### CODE REVIEW

**Comment by bryszard** [comment]
@Maroo-b We can work on bootstrap upgrade here then :).

**Comment by Maroo-b** [comment]
@bryszard the best approach is that @tansaku create a new branch from develop to handle the bootstrap migration in the repo and we can all collaborate on the task.

**Comment by bryszard** [comment]
@Maroo-b I don't understand - what is the difference in creating that by @tansaku?

**Comment by Maroo-b** [comment]
@bryszard the difference is that developers who wants to collaborate have to send PR to your github repo instead of AgileVenture ones.

It's just a suggestion, I'm curious about @tansaku recommendation for this case.

**Comment by bryszard** [comment]
@Maroo-b I see. So I guess you're right, maybe it's better to have it created by Sam. @tansaku what do you think?

**Comment by tansaku** [comment]
I think with the new functionality for protecting branches we could all start collaborating more closely on branches in this repo ...

**Comment by bryszard** [comment]
@tansaku What do you mean? What is the new functionality? What do you mean by 'collaborating more closely'?

I guess the answer to Marouen's question is yes? Then will you open a new branch for this problem? We could start working on it :).

**Comment by tansaku** [comment]
> @tansaku What do you mean? What is the new functionality? 

branch protection on github

https://help.github.com/articles/about-protected-branches/

> What do you mean by 'collaborating more closely'?

I mean pushing branches to this repo instead of our own forked repos.

On AsyncVoter we've created a team with access to the main repo - we could do that for LS too

**Comment by bryszard** [comment]
@tansaku Sounds good to me. Let me know what to do.

**Comment by Maroo-b** [comment]
@bryszard I created a new branch in project repository: https://github.com/AgileVentures/LocalSupport/tree/68370622_upgrade_to_bootstrap_v3

to collaborate on: https://www.pivotaltracker.com/story/show/68370622

**Comment by bryszard** [comment]
@Maroo-b Ok, Marouen, great, I'll start maybe next week, because this week I'm out of time ;).

**Comment by Maroo-b** [comment]
@bryszard sure no worries, good luck :)

**Comment by tansaku** [comment]
@Maroo-b @bryszard should we close this PR ready for a new one?

**Pull request closed without merging**
