### PR TITLE
Sleep to avoid google query limit on seed:db

### PR DESCRIPTION
**Pull request by levgubin**
need to add something similar to rake:db:import emails

### CODE REVIEW

**Comment by tansaku** [comment]
thanks for this @levgubin - when you ran this locally did the overall process take much longer?  I need to try this out on a fresh environment ... hmm - wonder if I could run it on staging ...

**Comment by levgubin** [comment]
I haven't noticed that loading takes much longer, although it may be in fact. We would need delay between google requests 0.1 sec anyway. The question here is whether some of this delay time is already spent on other calculations and in some cases delay may be unnecessary.

**Comment by tansaku** [comment]
thanks - I'm getting a new computer in a couple of days and will run a test of it then

**Comment by tansaku** [comment]
still haven't had time to unpack new computer - think I'll just merge this in as it's so simple

**Pull request merged**
