### PR TITLE
150714873 refactor map javascript

### PR DESCRIPTION
**Pull request by gnomonunes**

### CODE REVIEW

**Comment by tansaku** [comment]
@gnomonunes I think we may have managed to fix this with ` spyOn(OrganizationMap, 'getVolOpCoordinates').and.callThrough()`

**Comment by gnomonunes** [comment]
@tansaku thank you for the feedback. I'll give that a try.

**Comment by tansaku** [comment]
@gnomonunes and/or check out the PR that @ZmagoD and I worked on that completes the feature: https://github.com/AgileVentures/LocalSupport/pull/486

**Comment by gnomonunes** [comment]
@tansaku oh that's better, didn't see that PR. Thanks!

**Comment by tansaku** [comment]
so @gnomonunes shall we just merge in #486 or was there anything you wanted to add?

**Comment by gnomonunes** [comment]
Hey @tansaku sorry for the delay, been quite busy lately.
I think #486 looks great, we should merge it.
I'd like to add a debounced version of updateInfoBox but I can do that in a separate ticket.

**Comment by tansaku** [comment]
sounds good @gnomonunes - I'll close this one and merge the other

**Pull request closed without merging**
