### PR TITLE
Geocoder logic moved to be applied on the OrganisationsController.

### PR DESCRIPTION
**Pull request by nisevi**
https://www.pivotaltracker.com/story/show/154737957

Tests on BaseOrganisation and Organisation models related to the callback to geocoder gem were removed since we have to create acceptance tests for covering this functionality.

### CODE REVIEW

**Comment by nisevi** [comment]
@tansaku by moving the logic to the `OrganisationsController` and while I removed the tests related to geolocation on `BaseOrganisation` and `Organisation` models, since we are gonna do acceptance tests, it seems to be that we have functionality regarding some import from a **CSV** file that we are doing that I haven't contemplated before:

```
  @vcr
  Scenario: import email addresses                                   # features/admin/import_email.feature:20
    Given Google is indisposed for "64 pinner road, HA1 4HZ"         # features/step_definitions/map_steps.rb:203
    And I import emails from "db/email_test.csv"                     # features/step_definitions/email_steps.rb:73
    Then "I love dogs" should have email "fred@dogs.com"             # features/step_definitions/basic_steps.rb:420
    Then "I love cats" should have email "superadmin@cats.com"       # features/step_definitions/basic_steps.rb:420
    Then "I hate animals" should have email "superadmin@cruelty.com" # features/step_definitions/basic_steps.rb:420
    And "I love cats" should not have nil coordinates                # features/step_definitions/map_steps.rb:211
      expected: not nil
           got: nil (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/map_steps.rb:213:in `/^"(.*?)" should not have nil coordinates$/'
      features/admin/import_email.feature:26:in `And "I love cats" should not have nil coordinates'

Failing Scenarios:
cucumber features/admin/import_email.feature:20 # Scenario: import email addresses

1 scenario (1 failed)
8 steps (1 failed, 7 passed)
0m1.245s
```

Is this functionality still used? should be go back to what we have before with the `after_validation` callback on the `BaseOrganisation` model? or should we remove the **CSV** import functionality if it is deprecated (meaning that we don't use it any more)?

**Comment by tansaku** [comment]
as I was saying in the scrum @nisevi I think maybe we just add explicit geocode requests to the csv operations ...

**Comment by nisevi** [comment]
@tansaku codeclimate was complaining so I did a little refactoring on `Organisation` and `OrganisationsController`.

On `OrganisationsController` I was able to pull out some logic to these methods:

```
  def user_can_edit?(org)
    unless current_user.try(:can_edit?,org)
      flash[:notice] = PERMISSION_DENIED
      redirect_to organisation_path(params[:id]) and return
    end
  end

  def check_privileges_destroy
    unless current_user.try(:superadmin?)
      flash[:notice] = PERMISSION_DENIED
      redirect_to organisation_path(params[:id]) and return
    end
  end

  def check_privileges_show
    unless current_user.try(:superadmin?)
      flash[:notice] = PERMISSION_DENIED
      redirect_to organisations_path and return
    end
  end
```

Which of course I will handle with some meta-programming :+1:

**Comment by nisevi** [comment]
@tansaku I think I have solved most of the codeclimate issues but the one saying that we have to many lines 112/100 it should be addressed on another story since it will involve moving some logic to another class :+1: (do you think we should do it with this PR?)

**Comment by tansaku** [comment]
will leave codeclimate issue and fix that in separate refactoring ticket: https://www.pivotaltracker.com/story/show/155030752

**Comment by nisevi** [comment]
hey @tansaku do you wanna take a final look before we merge this :+1: ? After that I will do the deploy :+1:

**Pull request merged**
