### PR TITLE
ability to delete volunteer opportunities

### PR DESCRIPTION
**Pull request by Maroo-b**
@tansaku should I allow deletion action to Org admin and Super admin only ? ( site admin isn't allowed to delete ? )

### CODE REVIEW

**Comment by tansaku** [comment]
@Maroo-b you're mentioning three categories of admins there, and I think we have some inconsistencies in the system about how they are labelled.  We might want to try and write up something on the domain model here, e.g. 

* SuperAdmin: can do anything in site
* OrgAdmin: has full permissions related to the org they are associated with
* SiteAdmin: (does this exist as a separate entity?) - there was something to allow volunteers to process edits or something similar, but I forget how it is represented in the system
* Users: not much more than basic login

I think this might be something we want to reflect back to the client ... as well as reviewing our codebase and UI for consistency ...

**Comment by Maroo-b** [comment]
@tansaku There is a flag for SiteAdmin and I checked from the existent feature that this role (SiteAdmin) is nearly the same as simple user:

-  no edit action on organisations
- no edit action on volunteer op

For the moment I'll add this feature for the SuperAdmin and OrgAdmin.

**Comment by tansaku** [comment]
oh and if possible please use the Paranoic gem to ensure we can in principle undelete - the same functionality is set up for Organisations if you want to see how it's done

**Comment by Maroo-b** [comment]
@tansaku Sure, thanks for the hint :)

**Comment by tansaku** [comment]
great work @Maroo-b - regarding the commit message, I think it needs to be in square brackets and also ideally have some english language description as well - see https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md for details if you haven't already ...

**Comment by Maroo-b** [comment]
Thank you@tansaku, I have updated the commit msg and added a short description.

**Comment by tansaku** [comment]
Fantastic work @Maroo-b - I've checked this all manually and it all works exactly as spec'd - only thing I could think to add is to check that those without permission can't see delete button in interface or even delete via the api so to speak, but since we have undelete I think that's a separate chore perhaps ...

**Comment by Maroo-b** [comment]
I totally agree @tansaku, I suggest that we should plan a refactoring for authorization control like using **pundit gem** for example because I saw different approaches to check for authorization in controllers.

**Comment by johnnymo87** [comment]
I agree with the pundit gem idea!

**Pull request merged**
