### PR TITLE
Cache files

### PR DESCRIPTION
**Pull request by cesswairimu**
Found following files when trying to merge after a fetch to the breadcrumb branch
Created this branch and tracked the files
Mostly the files are from the features folder.

### CODE REVIEW

**Comment by tansaku** [comment]
hi @cesswairimu sorry for slow response.

Number of tracked files seems very large ... there was a big change (since many had been ignored) but we probably need to clear out your old cached files - perhaps @sigu can help but we can look at this as a team on Monday

**Comment by cesswairimu** [comment]
@tansaku i think we can look at them in the sprint @sigu has been a bit busy

**Comment by tansaku** [comment]
my suggestion is to check back out to an earlier commit, e.g. 5bd5552, i.e. create a new branch;
then clean out the cache

```
$ rm -rf features/vcr_cassettes
$ rm -rf features/req_cache
```
then refresh from git

```
$ git checkout features/vcr_cassettes
$ git checkout features/req_cache
```

and then merge in develop.

Or more simple, might be to start from a fresh branch off develop ...

sorry this is so tricky

**Comment by sigu** [comment]
This seems not necessary as the `vcr` and `request_cache` files in this should actually be discarded

**Pull request closed without merging**
