### PR TITLE
146165913 fix events branch issues

### PR DESCRIPTION
**Pull request by rehan-work**
Attempting to fix some of the codeclimate issues raised in the main events branch PR, also fixed the typo that was preventing the travis CI build from running https://www.pivotaltracker.com/n/projects/742821

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @rehan-work - so this might replace @StlMaris123 's original events PR?

**Comment by rehan-work** [comment]
@tansaku yep, this adds the feature flag function for the Events tab (which also has tests to ensure it works), should hopefully make it easier to get merged in and open up for contribution a bit easier

**Comment by tansaku** [comment]
thanks @rehan-work - so we just need to confirm with @StlMaris123 that we can close her PR and pull this one in instead.

We also have to get clear with everyone about how feature branches work ... :-)

**Comment by StlMaris123** [comment]
@tansaku, yes it is fine.

**Pull request merged**
