### PR TITLE
Send email to superadmin when a new org is proposed

### PR DESCRIPTION
**Pull request by mtc2013**
PT story: https://www.pivotaltracker.com/story/show/98724066

### CODE REVIEW

**Comment by mtc2013** [comment]
@tansaku ready for review

**Comment by tansaku** [comment]
@mtc2013 thanks - just about to start transit to UK - may be a few days before I can review :-/

**Comment by tansaku** [comment]
hi @mtc2013 and @marianmosley great work getting this done - nice small pull request.

Some comments; nothing that's a show stopper I think - me just thinking out loud here - hope that's helpful.

"Scenario: Superadmin receives an email when an organisation is proposed" looks rather imperative rather than declarative.  Would be nice to review and condense scenarios in propose_new_organisation.feature so that we saw a simple description of all the consequences of a proposition, rather than the more unit-test feel of separately seeing each of the different consequences in different scenarios

Regarding step definitions, it seems odd to move proposed_org_categories and proposed_org_fields from basic_steps to proposed_organisation_testing_api.rb and not move the following as well:

```
Then(/^I should see all the proposed organisation fields$/) do
  proposed_org_fields.each_value do |value|
    expect(page).to have_content(value)
  end
  proposed_org_categories.each do |cat|
    expect(page).to have_content(cat)
  end
end
```

in email_steps.rb method expect_email_exists is looking a little long - interesting to run reek on the step definitions ... `reek features/step_definitions/`

is mailer spec giving us any value above and beyond the feature test? 

looks like admin_mailer.rb could be dried out a little

proposed_organisations_controller#create could be refactored a little:

```
  def create
    org_params = ProposedOrganisationParams.build params
    usr = User.find params[:proposed_organisation][:user_id] if params[:proposed_organisation][:user_id]
    @proposed_organisation = ProposedOrganisation.new(org_params)
    @proposed_organisation.users << [usr] if usr
    redirect_to new_proposed_organisation_path and return false unless  @proposed_organisation.save!
    session[:proposed_organisation_id] = @proposed_organisation.id
    send_email_to_superadmin_about_org_signup @proposed_organisation
    redirect_to @proposed_organisation, notice: 'Organisation is pending admin approval.'
  end
```

and it's looking a little long ... first four lines could be pulled out into a separate method?

```
  def send_email_to_superadmin_about_org_signup(org)
    superadmin_emails = User.superadmins.pluck(:email)
    AdminMailer.new_org_waiting_for_approval(org, superadmin_emails).deliver_now
  end
```

looks good, although just looking at the temporary variable name `superadmin_emails`, makes me think, wouldn't it be cool if we could just call SuperAdmin.emails by having a class method on a SuperAdmin object that extends from the basic User ...?

**Comment by mtc2013** [comment]
@tansaku so will this be pulled in then?

**Comment by tansaku** [comment]
@mtc2013 could be - although there are a couple of minor refactorings there you might want to fix up?

* Regarding step definitions, it seems odd to move proposed_org_categories and proposed_org_fields from basic_steps to proposed_organisation_testing_api.rb and not move the method that uses the data as well

* proposed_organisations_controller#create could be refactored a little

* in email_steps.rb method expect_email_exists is looking a little long - have you run reek on the step definitions? `reek features/step_definitions/`

**Comment by mtc2013** [comment]
The api prefix is meant to just compntain methods rather than steps.

**Comment by tansaku** [comment]
Following our discussion I think the extraction of the "api" stuff is good, but should go in helper files in support dir perhaps? https://github.com/cucumber/cucumber/wiki/A-Whole-New-World

**Comment by mtc2013** [comment]
@tansaku I have issued a pr to @marianmosley repo that should address your concerns.  Hopefully, @marianmosley pulls that in soon.

**Comment by tansaku** [comment]
thanks @mtc2013 much improved - test helpers look good - are we still waiting for @marianmosley to pull in - or is that done now?  I see some new commits ...

**Pull request merged**
