### PR TITLE
adds draft of domain vision statement

### PR DESCRIPTION
**Pull request by tansaku**
Addresses https://www.pivotaltracker.com/story/show/116192537

### CODE REVIEW

**Comment by tansaku** [comment]
very interested in comments, edits, additions on this from anyone, particularly @mtc2013 @johnnymo87 @marianmosley @ZmagoD @Maroo-b @decareano 

I'd like to keep iterating on this and take to the client for approval - I'm following Eric Evans Domain Driven Design (DDD) methodology here to try and make our underlying domain model as clear as possible to aid our overall development ...

**Comment by ZmagoD** [comment]
Interesting approach I need to read about the subject to make meaningful comments :)

**Comment by tansaku** [comment]
@ZmagoD do check out https://en.wikipedia.org/wiki/Domain-driven_design and the related books by Eric Evans and Vaughn Vernon:

http://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215

The key idea is that the core domain model is just as important as the user experience and the unit tests.  I think what Eric Evans is getting at is that if you can really understand the domain you are working in you can create a model makes it much much easier to deliver value to the end user.

**Comment by tansaku** [comment]
I just emailed the client a revised version of this statement:

> Organisations have locations and contact information.  Users can be assigned to administrate specific Organisations.  These Organisation Administrators can then edit data associated with the relevant Organisation, and create (delete, and restore) Volunteer Opportunities specific to that Organisation. Any User can request administrative rights on an Organisation which are then approved or declined by a SuperAdmin user.

> The SuperAdmin user has the ability to edit data associated with any Organisation and also delete and restore organisations. The SuperAdmin can also invite new Users for those Organisations that do not yet have an Organisation Administrator.

> There are different views and search functionality on the Organisations and the Volunteer Opportunities that allow all Users and Guests to discover items of interest.

**Pull request merged**
