### PR TITLE
Remove outdated volunteer ops from do-it 

### PR DESCRIPTION
**Pull request by Maroo-b**
update task to remove exisiting do-it volunteer ops then fetch them from dot-it API

Addresses https://www.pivotaltracker.com/story/show/116028741

### CODE REVIEW

**Comment by Maroo-b** [comment]
@tansaku should we set a background runner for this task ?

**Comment by tansaku** [comment]
We can use a heroku scheduler  - I've set that up before

**Comment by tansaku** [comment]
There's no special code needed as long as it's a rake task and I think it should be integrated into the current import task

**Comment by mtc2013** [comment]
This brings up the side issue of whether we want to delete all Volops that are Do-It related.  The knock on effect of that is to change the id of the same do-it volop each day or however frequently we import or prune.  Because we don't have friendly names for the urls, that means the URL for a do-it volop will change each day.

**Comment by tansaku** [comment]
However we don't actually use those ids for routing.  

Anyhow, perhaps a solution is to update any where the DoIt ID matches (set a flag as checked) and then just delete those that weren't checked ...?

**Comment by tansaku** [comment]
More explanation on my first comment; we route all doit VolOps directly to the doit site I think ...

**Comment by mtc2013** [comment]
@tansaku yes, you're actually right that we don't use them for routing.  I was thinking errantly

**Comment by Maroo-b** [comment]
@tansaku does the PR require additional updates ?

**Comment by tansaku** [comment]
hi @Maroo-b - yes - I think we need to avoid deleting all and prefer a scheme like the one I described above, e.g. "update any where the DoIt ID matches (set a flag as checked) and then just delete those that weren't checked" - does that make sense?

**Comment by Maroo-b** [comment]
@tansaku it's possible to check do-it volunteer ops via `doit_op_id` column so I suggest to add an index on it but is there a reason why we should avoid deleting all record ?

**Comment by tansaku** [comment]
@Maroo-b - I guess we can delete them all if we use the doit_op id as the index, although I'm a little wary of that ...

**Comment by Maroo-b** [comment]
@tansaku : I'll try to outline the 2 possible solutions ( correct me if I'm wrong):
1- Delete all do-it volunteer ops and it's based on `source` column then we use the current api to fetch records ( in this case we have a delete operation, it could be improved by adding index on `source` column and an insert operation)

2- Fetch records from do-it api then delete outdated volunteer ops from db and insert nonexistent ones (in this case we have a delete operation, that removes non existent records from DB, then we have a compare operation to get new records to insert, and finally the insert operation)

 As I checked there is no relations with VolunteerOp model so in term of performance I guess that the first alternative will be better. 

what do you suggest ?

**Comment by tansaku** [comment]
I think you are correct that those are the two alternatives.  I'm not so worried about performance as this is a batch task that will run once a day.

The main difference between the two options is that option 1 will create new VolunteerOp ids on each update, whereas with option 2 we will maintain our local VolunteerOp ids.

At the moment it's unclear if we actually need those ... 

I guess we should go with the simpler option 1 - delete all - and then adjust later if needed

**Comment by Maroo-b** [comment]
@tansaku I checked this PT ( https://www.pivotaltracker.com/story/show/116028767), it seems that the second solution will be better.
I'll update this PR by implementing the second alternative.

**Comment by tansaku** [comment]
@Maroo-b - I'm not sure that we should be anticipating that subsequent feature too heavily - I think it makes more sense to implement the simplest thing, and then change when we actually need that subsequent feature ...

**Comment by Maroo-b** [comment]
@tansaku Ok great.

**Comment by Maroo-b** [comment]
@tansaku did you check this PR locally ? So what changes should we add to this PR ?

**Comment by tansaku** [comment]
I hadn't checked it particularly because I thought it was still WIP - I think we agreed this simple functionality is good.  However we've changed the functionality here with no tests right?  Effectively we've spiked it, so now we need to comment it out (or stash it)  and write an appropriate test, so we can see the test fail and then see it pass when we add this functionality back in.  Make sense?

**Comment by Maroo-b** [comment]
@tansaku sure, I added a test for the updated service.

**Comment by tansaku** [comment]
great work @Maroo-b !  we could also use a cucumber acceptance test for this operation.  See `features/devops/import_doit.feature`.

According to the outside-in BDD approach we should start with the acceptance test, then write the unit test then write the actual functionality :-)  Let me know if you're happy to write the acceptance test or if you need help with that I could push you some code.

Ultimately once you are familiar with the various elements it should be possible to drive from acceptance test to unit test to code, but no rush - it's great to work on the different elements separately to get comfortable with all the stages and the ins and outs of the project :-)

**Comment by Maroo-b** [comment]
@tansaku, it seemed to me that a task shouldn't require an acceptance task because unit test in this case is faster and do the same check. For documentation purpose I agree that acceptance test provide better docs. Anyway I added the acceptance test :)
If the PR is ok I can squash the commits.

**Comment by tansaku** [comment]
Thanks for this @Maroo-b 
You are right that acceptance tests are good for documentation, but I think they are also useful as integration tests.  The Rails AR operations could change and our unit test would still pass but the user experience would fail - which is what the acceptance test is also checking. 

Either way thanks for adding the acceptance test:

```gherkin
Scenario: Check 3 miles with existent doit volunteer op
    Given I have existent doit volunteer ops
    And I run the import doit service with a radius of 3 miles
    Then there should be 166 doit volunteer ops stored
```

Although I think what we should be checking is that the existing doit volunteer op was deleted if it was not present in the new import, like so

```gherkin
Scenario: Check that existing doit ops not in the import are deleted
    Given I have existing doit volunteer ops that is not on the doit system
    And I run the import doit service with a radius of 0.5 miles
    Then the existing doit volunteer op should not be present
```

I'm not sure how familiar you are with Cucumber - but you could use instance vars to maintain the reference to the volunteer op between the first and third steps or do something more specific like so:

```gherkin
Scenario: Check that existing doit ops not in the import are deleted
    Given there is a doit volunteer op named "no longer on doit"
    And I run the import doit service with a radius of 0.5 miles
    Then the doit volunteer op named "no longer on doit" should be deleted
```

Make sense?

It also makes me think about Paranoid volops - which we have already - you implemented right?   So we'll have deleted doit volops stored and could pull them back in if we wanted right?

**Comment by tansaku** [comment]
p.s. I think we have new options from Github to automate the squashing of PRs, so you can possibly leave the squashing to me in future ... :-)

**Comment by Maroo-b** [comment]
@tansaku thank you for the suggestion, I update the acceptance test using the third alternative. 
So for the paranoia gem I made some test to find that using `delete_all` bypass paranoia (it covers only delete and destroy method). If we really need to keep the possibility of restoring outdated doit volunteer ops we have to review and change this PR again :)

**Comment by tansaku** [comment]
@Maroo-b thanks for this - great work.  Let's leave the ability to restore to later - it's good for the time being to know the way things work.

I've made a few adjustments to the pull request to use consistent spacing and formatting - I've also adjusted the spec to be a bit tighter - take a look at the diff and see if you can work out why I've done what I've done.

Also, note that even with my changes the spec is still not as tight as it could be - can you see another place to tighten up? We've added some functionality that's not explicitly requested in the ticket, and it's part of the interface between our service and AR that we're not testing in a fine grained fashion at the moment so I'm going to merge this anyway as I think it's high time; but it's interesting to reflect how we could adjust the spec (and possibly refactor) further to improve the code design ...

**Pull request merged**
