### PR TITLE
logging in from /events/new should return user to /events/new

### PR DESCRIPTION
**Pull request by Xiaohong-Deng**
the solution is add events to whitelist.
now auto redirect after signing in is working correctly for events/new

Addresses: https://www.pivotaltracker.com/n/projects/742821/stories/157115541

### CODE REVIEW

**Comment by tansaku** [comment]
thanks for this @Xiaohong-Deng 

If you can, please do add a hyperlink to the pivotal ticket to the PR description and add the id in the git comment, which makes processing the PR much easier (automated connection with PT) - specifics here: https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#pull-requests

Looks like a lovely simple fix - any interest in addressing the associated code climate issues?  https://codeclimate.com/github/AgileVentures/LocalSupport/pull/733  If not, perhaps we can make those into refactoring tickets ...?

**Comment by Xiaohong-Deng** [comment]
@tansaku not sure how to compress the method to 7 line long again.

and yes I did add a PR link to the corresponding ticket.

**Comment by tansaku** [comment]
hi @Xiaohong-Deng - you added the PT ticket ID - I edited the description for you so that it was a URL - if you're stuck on reducing the method open a refactoring ticket (in pivotal tracker) and we'll look at it separately.

You won't need to attach code if you follow the instruction to add the ticket id to the git commit, then PT will add the code to the ticket automatically.

**Comment by Xiaohong-Deng** [comment]
@tansaku my misunderstanding. on the PT side, you can optionally add a link the the ticket to link you back to the PR. I thought that was required, too.

**Comment by tansaku** [comment]
wonderful - thanks @Xiaohong-Deng - those refactoring tickets are super-useful for newcomers to get started on.

You're correct, you can add a link to the ticket directly in PT - although I've never done that.

Since you don't need to make any more commits you now should add an empty one to this PR/branch to include the linkage, i.e.

```
git commit --allow-empty -m "[Finishes #157115541]"
```
then push that up, and it will all link up correctly.

Then when the PR is merged the ticket automatically gets marked as finished.  The idea is that the ticket is finished when the team has reviewed and merged, not at the point that the individual developer is done.

More at: https://github.com/AgileVentures/LocalSupport/blob/develop/CONTRIBUTING.md#git-comments

**Comment by tansaku** [comment]
thanks @Xiaohong-Deng - I'm getting a fail in the build - am re-running to see if it is intermittent, but do you get this locally?

```
features/admin/events/event_location.feature:34
    When I visit the events page                                                                # features/step_definitions/navigation_steps.rb:52
    Then I should see "Care for animals" description marker in "Care" event location in the map # features/step_definitions/events_steps.rb:40
      expected "[{\"lat\":51.5814735,\"lng\":-0.3439997,\"infowindow\":\"\\u003cbutton class='close infowindow_close...6b770b43fd.png\\\" alt=\\\"Volunteer icon local\\\" /\\u003e\\n\",\"index\":1,\"type\":\"vol_op\"}]" to include "35.4513251" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/events_steps.rb:51:in `/^I should see "(.*?)" description marker in "(.*?)" (event|organisation) location in the map$/'
      features/admin/events/event_location.feature:36:in `Then I should see "Care for animals" description marker in "Care" event location in the map'
Failing Scenarios:
cucumber -p second_try features/admin/events/event_location.feature:34 # Scenario: The event shows on the map
```

**Comment by Xiaohong-Deng** [comment]
@tansaku You mean a test covering redirecting back to events/new after logging in? feels like it should be an acceptance test. should I write a new scenario? where should I put the scenario?

**Comment by tansaku** [comment]
@Xiaohong-Deng somewhere like here: https://github.com/AgileVentures/LocalSupport/blob/develop/features/sign_in_sign_up/sign_in.feature#L50

**Comment by Xiaohong-Deng** [comment]
@tansaku the sign in page for `events/new` is a legacy sign in. Burned me over 30 minutes.

**Comment by tansaku** [comment]
@Xiaohong-Deng - not sure what you mean by a "legacy sign in" can you explain further?

**Comment by Xiaohong-Deng** [comment]
@tansaku there are two patterns for signing in defined in `authentication_steps.rb`
1. I sign in as "superadmin@example.com" with password "pppppppp" on the legacy sign in page
2. I sign in as "superadmin@example.com" with password "pppppppp"

two different sign in pages. the difference is legacy sign in page has more than one `user_email` values associated with some attribute.

what I am not sure is the relevant Capybara method looks for which attribute. because it reports multiple matches for `user_email` if I don't specify it's legacy sign in. I think it's not `id`. maybe `class` or something. I didn't dig in.

this is a leaky abstraction. people don't usually expect two sign in pages when they are writing cucumber tests.

**Comment by tansaku** [comment]
@Xiaohong-Deng thanks for explaining - perhaps we could create a refactoring ticket to improve the situation.

I'm still a little confused by the statement:

> the events/new is a legacy sign in

because `events/new` is a route that we want to redirect to, independently of whether we are using legacy or newer sign in page.  It sounds like the issue is ambiguity in the construction of cucumber tests about whether they should be using the legacy sign in page or not.   In principle the test should work for both new and old sign in pages ... although it would be good to root out whether we can remove the legacy sign in page throughout ...

**Comment by Xiaohong-Deng** [comment]
@tansaku investigating this sounds like a good idea.

what I said is the sign in page for `events/new`, not `events/new` itself, is a legacy sign in. but maybe I should have said

> the sign in page you are redirected to after you access `events/new` while not logged in, is a legacy sign in.

you're suggesting including a branch for legacy sign in inside the pattern
> I sign in as "superadmin@example.com" with password "pppppppp"

right? agreed. also it would be better if we can remove the legacy sign in page from the application.

**Comment by tansaku** [comment]
right, so sounds like we need a refactoring ticket for that - in the meantime we have test coverage and this can be merged - many thanks for the fix :-)

**Comment by tansaku** [comment]
related refactoring ticket: https://www.pivotaltracker.com/story/show/158180472

**Pull request merged**
