### PR TITLE
check travis build result - no merge !

### PR DESCRIPTION
**Pull request by Maroo-b**
Checking if Travis build will pass on failing cucumber test

### CODE REVIEW

**Comment by Maroo-b** [comment]
@tansaku cucumber test made the travis build fail as expected  https://travis-ci.org/AgileVentures/LocalSupport/builds/132480330#L2675

**Comment by Maroo-b** [comment]
@tansaku there is a strange behavior if the failing cucumber test is the last one like in this PR https://github.com/AgileVentures/LocalSupport/pull/316 the exit status will be 0 (it supposed to be 1 for exit system)

**Comment by tansaku** [comment]
weird @Maroo-b ....

**Comment by tansaku** [comment]
@Maroo-b but so in this PR the build request failed correctly as it should do, so does that mean the problem is gone?

**Comment by Maroo-b** [comment]
@tansaku the build fails only if the cucumber test isn't the last one, I didn't investigate much the issue so maybe we should open a ticket in PT

**Comment by tansaku** [comment]
@Maroo-b - yes please do - this will need some attention ...

**Comment by Maroo-b** [comment]
@tansaku PT task created https://www.pivotaltracker.com/story/show/120650627

**Comment by tansaku** [comment]
I'll close this then

**Pull request closed without merging**
