### PR TITLE
Removed "config/database.yml" file.

### PR DESCRIPTION
**Pull request by nisevi**
- `database.yml` is a file added to the `.gitignore`;

- `database.yml.sample` is the one we should use as a sample for database configuration;

I tracked the commit where `database.yml.sample` was created and database.yml was not removed but added to the `.gitignore` file:
screenshot from 2017-11-10 00-41-08

`git show ae5a92882b38ddf96e61173920f515ca4afe1555` will display the commit.

@tansaku what do you think about this change? I just switched what is on `database.yml` now with `database.yml.sample` and removed that file.

### CODE REVIEW

**Comment by nisevi** [comment]
Travis is failing because we are using that file:

image

Why we are using an ignored file on TravisCI?

**Comment by tansaku** [comment]
@nisevi - what's the motivation for making this change?

**Comment by nisevi** [comment]
Hey @tansaku, when I was installing everything and doing the setup of the project I saw that `database.yml` is a file on the `.gitignore` so it was weird for me to see that the file it was there while is being excluded, that was my main motivation, and also I thought that removing this file and updating the sample it wasn't going to crash TravisCI, but since this change is not as simple as I thought, maybe we could just update the sample file in a pivotaltracker issue and close this PR :+1: . What do you think?

**Comment by nisevi** [comment]
@tansaku closing this one.

**Pull request closed without merging**
