### PR TITLE
112899357_refactor_gem_show_me_the_cookies

### PR DESCRIPTION
**Pull request by decareano**
Added cucumber test(s) from the READme. 
Files changed: `features\home_page\map.feature (added lines 92-101)`
                        `features\step_definitions\authentication_steps.rb (added lines 122-145)`
                        `features\support\helpers.rb (added "ShowMeTheCookies" to World`
I wrote some tests just to understand better the gem but I still do not get the info for the cookie(s).

### CODE REVIEW

**Comment by tansaku** [comment]
great to see you exploring this @decareano - looking forward to pairing on it next week

**Comment by Maroo-b** [comment]
@decareano chech the changes pushed to this PR

@tansaku I suggest to check puffing_billy gem, in cucumber setup it's configured to use poltergeist JS driver, but currently we are using Webkit. Also I noted there is unnecessary use of puffing_billy tags in some acceptance tests but I didn't change any existent test. Only I configure show_me_the_cookies gem and integrated it in the existing steps ( the simplest PR possible :) )

**Comment by tansaku** [comment]
thanks @Maroo-b - I'll review with @decareano tomorrow

**Comment by tansaku** [comment]
@decareano great to review this with you.  I think we agreed this is looking almost good to go - I'll close the other PR - you just let me know when you're happy for me to do a final review on this one :-)

**Pull request closed without merging**
