### PR TITLE
Ensure dates are displayed in UK format (day month year)

### PR DESCRIPTION
**Pull request by rachaelkiteme**
Ensure dates are displayed in UK format 
changed the date format to day month year
Addresses https://www.pivotaltracker.com/story/show/156190099

### CODE REVIEW

**Comment by tansaku** [comment]
hi @rachaelkiteme - thanks for this - it looks great!

However the automated tests appear to be failing in a way that I'm not familiar with :-( 

Are they passing for you locally?

**Comment by rachaelkiteme** [comment]
No

Regards
Rachael

**Comment by tansaku** [comment]
@rachaelkiteme what failure are you getting locally?

**Comment by rachaelkiteme** [comment]
This is it 
 ```WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST http:///opportunities with body '{"advertise_start_date":"2018-08-23","advertise_end_date":"2018-08-24","blurb":"Some nice people","description":"Some nice people","owner_recruiter_id":"4dd7dfe2-c281-4170-8f0b-da17e8af5e5d","locations":[{"address":null,"postcode":null,"location_type":"SL","lat":51.5676116,"lng":-0.3580085}],"title":"Help out"}' with headers {'Content-Type'=>'application/json', 'X-Api-Key'=>'dummy_token'}
     
       You can stub this request with the following snippet:
     
       stub_request(:post, "http:///opportunities").
         with(
           body: "{\"advertise_start_date\":\"2018-08-23\",\"advertise_end_date\":\"2018-08-24\",\"blurb\":\"Some nice people\",\"description\":\"Some nice people\",\"owner_recruiter_id\":\"4dd7dfe2-c281-4170-8f0b-da17e8af5e5d\",\"locations\":[{\"address\":null,\"postcode\":null,\"location_type\":\"SL\",\"lat\":51.5676116,\"lng\":-0.3580085}],\"title\":\"Help out\"}",
           headers: {
       	  'Content-Type'=>'application/json',
       	  'X-Api-Key'=>'dummy_token'
           }).
         to_return(status: 200, body: "", headers: {})
     
       registered request stubs:
     
       stub_request(:post, "http://api.qa2.do-it.org/v2/opportunities")
       stub_request(:any, "/maps\.googleapis\.com/")```

**Comment by tansaku** [comment]
hi @rachaelkiteme - I've pulled out your branch locally and I'm getting these rspec failures:

```
  1) OrganisationsController#build_map_markers 
     Failure/Error: @collection = Array(collection)
     
     ActiveRecord::StatementInvalid:
       PG::DatetimeFieldOverflow: ERROR:  date/time field value out of range: "24-08-2017 02:23:58.171739000"
       LINE 1: ...isations.*, (CASE WHEN organisations.updated_at > '24-08-201...
                                                                    ^
       HINT:  Perhaps you need a different "datestyle" setting.
       : SELECT organisations.*, (CASE WHEN organisations.updated_at > '24-08-2017 02:23:58.171739000' AND organisations.id IN (SELECT users.organisation_id FROM users) THEN TRUE ELSE FALSE END) as recently_updated_and_has_owner FROM "organisations" WHERE "organisations"."type" IN ('Organisation') AND "organisations"."deleted_at" IS NULL

```

it looks to me like the posgresql database is expecting US formatted dates ...

we might have to ensure that the dates are converted back to US form when they get stored in the DB - makes this a bit of a tricky feature maybe.

Are you in our slack chat instance? we usually try and have a little discussion about tickets to help flush out problems like this.  It's not required but we'd love to give you more help and support there or here in this github issue if you'd like to continue working on this :-)

**Comment by tansaku** [comment]
hi @rachaelkiteme - did you have another chance to look at this? :-)

**Pull request closed without merging**
