### PR TITLE
Org cat show style

### PR DESCRIPTION
**Pull request by Icicleta**
I have changed html and css to create a new style when categories are displayed and the <h> of titles to get a better hierarchy .
Because of the last change I had some feature test and view spec failing so It was fixed also.

### CODE REVIEW

**Comment by tansaku** [comment]
great work @Icicleta - I'm just playing with a new feature on heroku which (sort of) auto-deploys a version of the app in question: https://harrowcn-develop-pr-161.herokuapp.com/

**Comment by Icicleta** [comment]
Cool, still a bit lost with heroku, and the link gives me 
```500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.```

I'm thinking that is not needed a new feature as the categories where already sort out by types, just change the layout, so I think, but not sure, it's not needed a new feature.
So If you reckon so, I will create a new branch and style this three divs.

**Comment by tansaku** [comment]
yeah, don't worry - you're not lost - I just haven't got that functionality working - I just pushed to develop with something that might fix it - please sync to develop and update your branches and open pull requests - I'm just going to review this code now

**Comment by Icicleta** [comment]
I have pull upstream develop and merged to this branch.

**Comment by tansaku** [comment]
this looks great - well done @Icicleta - will merge in as soon as the build passes

Separately we could have a discussion (possibly involving @sjmog) about the tests we touched here - some of them specify particular heading sizes, which I think we could be replacing with perhaps relative sizing ...

**Comment by Icicleta** [comment]
Ok @tansaku, not sure how to do that, I'll do some research, otherwise we can talk about it in the afternoon meetup

**Pull request merged**
