### PR TITLE
Adds friendly_id feature (2nd attempt) [PT #89294872]

### PR DESCRIPTION
**Pull request by bryszard**
Second attempt on - https://www.pivotaltracker.com/story/show/89294872.

@tansaku: I followed your advice. I cleared up everything, made small steps and assured that :slug column would be filled with content with the migration. 

Unfortunately, it turned out to be impossible to make just small changes. Just adding $extend FriendlyId to BaseOrganisation model made 6 specs fail. After fixing them 56 cucumber tests were failing. To fix them all I needed in fact to implement friendly_id in the whole app (at least everywhere, where the tests showed me to). I had also to update some steps in cucumber and specs (especially I had to stub new :friendly method).

Now I'm left with 5 failing cucumber tests, which are tricky for me, because they appear in part of app, which authenticates the user (with Devise) and in some point redirects the flow to the page with id instead of friendly_id. 

It seems that friendly_id has quite long tentacles embracing the whole app.

### CODE REVIEW

**Comment by bryszard** [comment]
I tried to resolve the resting errors in tests. I got only one, rest of them is hidden somewhere in Devise logic I guess.

My notes:
- this-is-my-org.feature, it's getting into devise processes (login page), application_controller.rb - I don't know where the redirection comes from (somewhere from RegistrationController#create, probably super, but exactly where?), 
maybe it's possible to add some code to def after_sign_in_path_for(resource)?
- create_volunteer_opportunities.feature, for some reason it redirects org super admin to the root instead of new vol_op page, don't know where the redirection comes from - maybe Devise method def after_sign_in_path_for(resource_or_scope); stored_location_for(resource_or_scope) || signed_in_root_path(resource_or_scope); end

**Comment by tansaku** [comment]
great work @bryszard !

Notes from standup

a) coveralls --> double check whether coveralls is including acceptance tests in coverage stats
b) travis --> why does it say pass, when four tests are failing
c) devise/friendly_id problem
d) slugs are really long for some orgs

**Comment by bryszard** [comment]
OK, now everything is passing and working.

Due to the Hound comments I've set myself to change all double-quotes to single-quotes, where it's necessary in organisations_controller_spec.rb, and changed also rocket-hashes into new syntax in this file, where I found them.

**Comment by tansaku** [comment]
this looks really solid @bryszard !  I'm just thinking it might be good to deploy this and show the client the new experience before we merge ... are you interested in doing an exploratory push to heroku from this feature branch?

**Comment by bryszard** [comment]
@tansaku: OK, I'll push it to heroku.

**Comment by tansaku** [comment]
@bryszard thanks - could be a good learning experience if you haven't done it before - you'll want to run the seed operation when it's set up to get some data in there - feel free to reach out for help if you need it

**Comment by tansaku** [comment]
should I merge this in first @bryszard ...? or do you want to open a fresh one?

**Comment by bryszard** [comment]
This one was a working one, so you definitely can merge it.

**Comment by tansaku** [comment]
don't worry about migrations my side - just check if this has the correct base you want to work from :-)

**Comment by bryszard** [comment]
@tansaku: Yes, the last commit of this PR was a point of departure for custom parser.

**Comment by Maroo-b** [comment]
@tansaku  and @bryszard : is it ok to keep the creation of friendly ids in a migration file instead of rake task ? https://github.com/bryszard/LocalSupport/blob/b54f117476e6f3584c47a7706bf3e01d7fe18242/db/migrate/20160421100439_add_slug_to_organisations.rb#L7

**Comment by tansaku** [comment]
@Maroo-b we might want to move this discussion to an open PR, but I think we need to look carefully at this as I identified some other related issues here in the client meeting yesterday, i.e. side effects of updating all these orgs ...

I think that the code should be moved out of the migration ... whether it has to be a rake task is another matter.  Perhaps the critical thing is that it is a service with it's own tests, and that we then have the option of hooking it into a rake task or a migration, or whatever we want ...

**Pull request merged**
