### PR TITLE
113527215 taking logic from views to controllers 

### PR DESCRIPTION
**Pull request by bryszard**
WiP.

Another approach to the topic - https://www.pivotaltracker.com/story/show/113527215.

I couldn't find any other solution for nested_attributes, but I tried to move the logic from view helper methods to the controller. It works on my local repo, but in my opinion it's now less DRY, as it was centralized in one place in FormHelper class.

If you decide that the logic should be moved from the FormHelper, we could work on this pull request.

### CODE REVIEW

**Comment by tansaku** [comment]
hi @bryszard - thanks for taking a stab at this - very interesting.

I like what you've done with the form helper and I see that you've taken an "extract method" refactoring within the controller as a first pass, which is a great start.  We might also think about trying to pull these out into service objects.  Have you read much about service objects?

* https://blog.engineyard.com/2014/keeping-your-rails-controllers-dry-with-services
* http://blog.silvabox.com/musings-on-service-objects/

maybe we should work out a day next week for you and I to pair on a service object refactoring if you're interested ...

Also, you said:

> I couldn't find any other solution for nested_attributes

It would be good to hear what if anything you did find out, and ideally we should post some SO posts and possibly file issues on the rails github as a priority over our own refactoring.  I'll be very happy to help you craft those, if you can tell me what you did find out in your researches.  Did you read any of the top hits in:

https://www.google.co.uk/?ion=1&espv=2#q=rails%20form%20helper%20%22many%20to%20many%22%20nested_attributes

**Comment by bryszard** [comment]
Hey @tansaku. I thought about making a service to DRY it up, but I wasn't sure how, so I'd like to work on that with you next week.

> I couldn't find any other solution for nested_attributes

In fact, I read the first article on the list you've linked  (http://www.createdbypete.com/articles/working-with-nested-forms-and-a-many-to-many-association-in-rails-4/) and also the documentation of Rails Guides on FormHelper and nested_attributes.rb in ActiveRecord repo on Github.

The thing is that I got doubtful about if we need to find another solution for nested_attributes or that we just can find a way to use it a bit differently. I'm not sure why do we need another solution. 

The main problem for me with refactoring was the fact that "_destroy" = '1' on nested category_organisations was denying creation Organisation object with full list of category associations (after @organisation = Organisation.new(org_params). That was the reason why the method setup_organisation in FormHelper needed to "rebuild" the list of categories on each form rendering.
So the problem, it seems to me, is not with the nested_attributes structure, but with the implementation.

But maybe I'm just wrong, please tell me if I am :).

**Comment by tansaku** [comment]
@bryszard I'm not saying we need another solution to nested_attributes - I'm hoping that there's a simpler solution that uses nested_attributes or some close relative.

I have no problem with nested_attributes, but it seems that we had to add a lot of strange operations to make things work with nested_attributes (particularly the destroy stuff).  If I was approaching this problem myself I would try and create a small rails app with just two models (with a many to many relation) and then see if I can get a clean solution using nested_attributes (or whatever) that allows the deletion and creation of individual "many to many" relations through a single form.

Adjusting the query to add "destroy":

https://www.google.co.uk/#q=rails+form+helper+%22many+to+many%22+nested_attributes+destroy

gives me some interesting results e.g.

https://hackhands.com/building-has_many-model-relationship-form-cocoon/

Note that the active record docs on accepts_nested_attributes_for also does not describe how to handle "many to many", which is what makes me think that it might not be possible to do this cleanly, so I think we really want to move towards asking the community how to do it.

http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html

So I think the next step should be setting up a simple rails app - is that something that you're not comfortable doing?  Would it help if I created a shell to get you started?

**Comment by bryszard** [comment]
@tansaku: Ok, now I understand. I'll try to set up a small rails app for that.

**Comment by bryszard** [comment]
@tansaku: I can try to work on Hound comments, but I don't understand why Travis is not passing.

**Comment by bryszard** [comment]
In two last Hound comments I guess the Hound is wrong - 1. I can't use && in "and return false" (doesn't work), 2. I think that .all.each is something else that .all.find_each or .find_each.

I moved some logic to model and refactored methods which were too long. I also deleted the test case in view spec, which is now obsolete (after moving logic to model). I think it's ready to go.

**Pull request merged**
