### PR TITLE
Adds 'Do-it' logo to site footer

### PR DESCRIPTION
**Pull request by RajeevHejib**
Addresses https://www.pivotaltracker.com/story/show/113260749

### CODE REVIEW

**Comment by tansaku** [comment]
great work @RajeevHejib - only thought I have is that maybe this should be covered by the do-it feature flag, so the icon is only shown when the feature is enabled.  What do you think?

**Comment by RajeevHejib** [comment]
That sounds appropriate.  I will work on this.

**Comment by RajeevHejib** [comment]
Hi @tansaku when you get a chance can you please have a look at this.  Travis CI failing on scenario cucumber features/individual_charity_pages/this-is-my-org.feature. This scenario is not related to my change. Interestingly when I run the test for this scenario interactively it gives no errors.

**Comment by tansaku** [comment]
yeah, sorry @RajeevHejib - we have this one temperamental test - https://www.pivotaltracker.com/story/show/112902301 - I've restarted the build - I guess I'll have to focus on stabilising this soon as it is getting pretty irritating ...

**Comment by RajeevHejib** [comment]
no worries, my branch was out of step with upstream so have pulled and merged with this branch.

**Comment by tansaku** [comment]
great work @RajeevHejib

**Pull request merged**
