### PR TITLE
ensure upcoming events have nicely formatted dates

### PR DESCRIPTION
**Pull request by sstamoulas**
https://www.pivotaltracker.com/n/projects/742821/stories/148842261

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @sstamoulas - are there some tests we should modify here?

**Comment by sstamoulas** [comment]
This is all I could find. From what I see, nothing needs to be updated.

screen shot 2017-10-14 at 8 37 24 am.

**Comment by sigu** [comment]
@sstamoulas for stories that change the view, it is a nice practice to attach a screenshot reflecting the changes, not required though but its  easier to view the visual changes without downloading it

**Comment by tansaku** [comment]
@sstamoulas so in this case I'd say the cucumber test should be updated to check that the date is displayed in the correct format - what we have here is an absence of a test for the way the date was before.  Given that we are changing it (we have a request from the client) it's now important to encode that in the test so that we know if it breaks in future, so for example we might add the following to the test:

```
  And I should see "Thursday, May 13th at 14:15"
```

or whatever the precise output of the date format is now (and the date for that specific test)

**Comment by tansaku** [comment]
@sstamoulas hope you're well - we'll be working on this next week to get it closed out.  

If you want to pair on this with me or @sigu you can do so my taking advantage of our Premium F2F offer: https://www.agileventures.org/premium-f2f-offer

**Comment by sstamoulas** [comment]
Greetings @tansaku , I am doing well. I have 3 weeks left in the States. After which I will be able to be more heavily involved. About this task, I mentioned previously, while you were on vacation, that it was completed via another task including the cucumber tests. You can find the updates completed in the following pull request https://github.com/AgileVentures/LocalSupport/pull/480. Thanks and let me know if you have any questions.

**Comment by tansaku** [comment]
thanks @sstamoulas - apologies if I'm not understanding, but I don't see any commits from you in that other PR, and I don't see the changes that I suggested above.

If you've made a change to the view, then that requires a change to tests. 

The `see_upcoming_events.feature` needs to be amended as I described in order to test the changes you made.  The other PR you refer to is not sufficient.  No problem if you can't make the necessary change - we'll do it ourselves in the next couple of weeks to get this merged in, but if you can understand what we are asking for and can provide when you are free we will be very grateful :-)

**Comment by sstamoulas** [comment]
I apologize, I think I was confusing the files. I have attached the current updates including the cucumber tests. Please advice if they are sufficient.
screen shot 2017-11-10 at 5 38 32 pm

**Comment by tansaku** [comment]
wonderful - great work @sstamoulas ! thanks so much

**Comment by sstamoulas** [comment]
💪Yes! Thank you so much.💪

**Pull request merged**
