### PR TITLE
fix incoming nil coords

### PR DESCRIPTION
**Pull request by NickSchimek**
Both doit and reachskills were being assigned either a 0 or nil for the coordinate. Both zero and nil will triangulate to the center of the earth, which is why some volunteer ops took the map to a body of water on the equator.

Some doit opportunities came in with nil and were persisted to the database with nil coordinates, and when triangulated through the Geocoder to display on the map were given the coordinates of (0.0, 0.0).

Reachskills opportunities were being triangulated through the Geocoder before the coordinates were persisted based on the 'town' attribute, however some opportunities came in with a list of towns which the Geocoder would return nil and when the Geocoder came back as nil then the system was assigning the coordinates of (0.0, 0.0)

To fix this I decided to assign default Harrow coordinates instead of 'nil'/0 
In my original PR #642 I simply did not display the map marker when the coordinate was nil or 0, but I think that may give the user an impression that the application is broken when it is not. 

Assigning a default coordinate is a better approach for two reasons:
It ensures the application has a consistent behavior.
The imported opportunities are in Harrow to begin with so they should have a Harrow coordinate.

This fixes https://www.pivotaltracker.com/story/show/150890866

### CODE REVIEW

**Comment by sigu** [comment]
@NickSchimek , do we need the `vcr_cassete` files that have been checked in to this PR. I thought they are generated for every user in development environment on their machines

**Comment by NickSchimek** [comment]
Yes we need these specific vcr cassettes as they have the necessary information to test against nil coordinates

**Comment by NickSchimek** [comment]
of course I could be wrong. It may be something to ask @tansaku about ❓

**Comment by tansaku** [comment]
we potentially would need VCR files checked in if the kinds of network requests being made are different as a result of the changes in the test.  

However when checking in VCR files it's important to run the cache clearance task first ```rake vcr_billy_caches:reset``` and then make sure that only changes that have been introduced on a green test run get checked in 

@NickSchimek this is great work - as regards defaulting to a particular location in harrow, is the danger that we end up implying that an opportunity is in a different place from where it actually is?

Would it make better sense to just avoid displaying opps on the map when they are invalid from our point of view?

**Comment by sigu** [comment]
It actually makes sense to have them not showing instead of defaulting to a location to which they do not belong

**Comment by NickSchimek** [comment]
@tansaku I'm fine doing it either way, but would like to point out that if we don't want to show markers for opportunities that don't have an exact location then we should not be displaying markers for the reach skills opportunities since all they provide is a town and zip code and we've been Geocoding a default location based on the town name and zip code.
line 45: import_reach_skills_volunteer_opportunities.rb
```
  def find_coordinates(op)
    Geocoder.search(
      "#{op['node']['Postcode']}, #{op['node']['Town']}"
    ).first
  end
```
Personally as a user I've always felt that when dealing with a map I have always viewed the location marker as a general area marker due to the fact that an actual address isn't always supplied, which the user can verify when the link is followed, but maybe I'm the only who thinks that way.

**Comment by tansaku** [comment]
@NickSchimek ah, I didn't realise that about the reach skills

My hope for the whole app was that seeing which volunteer ops were close to your own house was a really valuable part of the whole offering here.

I think ideally we should be pressuring reachskills to provide more precise info.

I don't think we're under any requirement to show items in the map if they appear in the list - I guess having everything default on the center of harrow is not a bad default. 

Would be nice to use a different marker or something, but I guess we should merge this and see how folks react rather than me over-anticipating everyone's reaction :-)

**Pull request merged**
