### PR TITLE
Added VCR in cucumber test [ RDY ]

### PR DESCRIPTION
**Pull request by ZmagoD**

### CODE REVIEW

**Comment by tansaku** [comment]
Hi @ZmagoD thanks for this - I thought I left you a long comment yesterday on this, but it doesn't appear to have shown up :-(

Please do try and leave a description on the pull request letting us know what you are doing and your plans.  Please also try and use the labels, e.g. RFC -> 'Request for Comments'; WIP -> 'Work in Progress'; RDY 'Ready to be pulled in' to let us know the status of pull requests.

Many thanks in advance :-)

**Comment by ZmagoD** [comment]
In these pull request I had added the VCR gem into the project and use it in the cucumber test suite to prevent cucumber scenarios to make third party calls

**Comment by tansaku** [comment]
cool - to make progress here I think we might need to look at some of the cucumber features in isolation.  I can't immediately see from the build if we have removed any of the messages from the cucumber output.

This could be good to pull in, but I need to test when I am not on the train and I have good connectivity :-)

**Comment by mtc2013** [comment]
I just ran this branch with wifi turned off.  And the map features and some others are failing:

Failing Scenarios:
cucumber features/home_page/map.feature:22 # Scenario: Show all charities in map on homepage map
cucumber features/home_page/map.feature:29 # Scenario: Infowindow appears when clicking on map marker
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:52 # Scenario: Organisation map has small icon for organisation with no users
cucumber features/individual_charity_pages/propose_new_organisation.feature:34 # Scenario: Unregistered user proposes new organisation
cucumber features/individual_charity_pages/propose_new_organisation.feature:49 # Scenario: Unregistered user proposes new organisation without checking confirmation box
cucumber features/individual_charity_pages/propose_new_organisation.feature:64 # Scenario: Signed in user proposes new organisation
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:22 # Scenario: See a map of current volunteer opportunities
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:30 # Scenario: Volunteer opportunites are listed in map popups
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:30 # Scenario: Volunteer opportunites are listed in map popups
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:41 # Scenario: See map when editing my volunteer opportunity

**Comment by mtc2013** [comment]
Oh, now the tapes aren't in version control.  I need to run them again and see what goes on.

**Comment by tansaku** [comment]
@mtc2013 @ZmagoD do we just need the VCR tag on every cucumber feature? or can we turn it on globally or something?

**Comment by tansaku** [comment]
I think the strategy here should be to identify a single cucumber feature that fails due to 3rd party API when internet is off, e.g. 

cucumber features/home_page/map.feature:22 # Scenario: Show all charities in map on homepage map

as @mtc2013 has at the top of his list above.  @ZmagoD @decareano can you run that single scenario and check that it fails when you have disconnect from the network.  Then when you've validated that that fails, reconnect to the network, wrap it in VCR, grab a recording and then confirm whether or not you can then have it pass when the network is disconnected.

make sense?

**Comment by ZmagoD** [comment]
@mtc2013  @tansaku  These are the failng test when it run offline:
Failing Scenarios:
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:37 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:52 # Scenario: Organisation map has small icon for organisation with no users

247 scenarios (7 failed, 3 undefined, 237 passed)
1950 steps (7 failed, 4 skipped, 3 undefined, 1936 passed)
2m26.949s

**Comment by tansaku** [comment]
thanks @ZmagoD so is VCR wrapped on these?   really really let's focus on just one, and see if we can fix the problem for that one, with VCR, or something ... :-)

**Pull request closed without merging**
