### PR TITLE
[WIP]Add recurrence to events

### PR DESCRIPTION
**Pull request by cesswairimu**
Ticket [151086152](https://www.pivotaltracker.com/n/projects/742821/stories/151086152)
- Implement with ice_cube gem alone

### CODE REVIEW

**Comment by tansaku** [comment]
hi @cesswairimu how's this PR going?

**Comment by cesswairimu** [comment]
hey @tansaku, its partly finished was planning to create a kind of checklist and break-down the issue to subsections. Sorry this is taking too long but will break down the issue to subsections today if thats okay?

**Comment by tansaku** [comment]
that's great @cesswairimu  - please do push up any code your working on :-)

**Comment by tansaku** [comment]
@cesswairimu I guess this is the latest version of this?  but you don't have time to work on it?  if so that's totally fine - maybe we close this and pass it on to someone else?

**Comment by cesswairimu** [comment]
Actually I am still interested in this I might find sometime this coming week and look in to but we can close it and I will just reopen if noone works on it until when I can

**Pull request closed without merging**
