### PR TITLE
Build controller, models and views for the services[WIP]

### PR DESCRIPTION
**Pull request by StlMaris123**
This pr solves issue #165189344, story link: https://www.pivotaltracker.com/n/projects/742821/stories/165189344/comments/201896347

### CODE REVIEW

**Comment by StlMaris123** [comment]
Still git a few issue to fix:

- [ ] Style index and new pages to match other existing pages i.e organizations

- [ ] validations

- [ ] tests

- [ ] fix code climate issues

@mattwr18  @tansaku , please feel free to top up on the to do list then I can fix them

**Comment by StlMaris123** [comment]
Comments from the previous pr: https://github.com/AgileVentures/LocalSupport/pull/1038 for reference

**Comment by StlMaris123** [comment]
Hi @tansaku , @mattwr18 ,
This is the current view for a new service, please lemmi know how we can improve it. Thanks
screencapture-localhost-3000-services-new-2019-05-10-10_08_05

**Comment by tansaku** [comment]
hi @StlMaris123 - great start!  Thanks so much.

One quick thing is that the created_at and modified_at fields are rails under the hood stuff and probably shouldn't be available for the user to edit.

**Comment by mattwr18** [comment]
interestingly @StlMaris123, it looks to be failing the build in a similar way to @ciremoussadia `PR`.
both these `PR`s have 30 cucumber failures :thinking: 

@tansaku ^^^

**Comment by tansaku** [comment]
thanks for flagging this @mattwr18 - something weird going on ...

**Comment by tansaku** [comment]
the really strange thing is that the few PRs that I put in the last few days didn't seem to have any trouble - I wonder if merging the latest develop might help?

**Comment by tansaku** [comment]
@StlMaris123 I merged in the latest develop branch on @ciremoussadia 's PR and it seemed to fix the issues - maybe that could help here too?

**Comment by tansaku** [comment]
@StlMaris123 apologies if you wanted to merge in develop yourself, but I thought I'd just do it to see if it works on your PR as it did on @ciremoussadia 's

**Comment by tansaku** [comment]
hmm, doesn't seem to have helped :-/ maybe need to address the code climate issues and the rspecs, and not worry about the cukes for the time being?

**Comment by mattwr18** [comment]
@StlMaris123, @tansaku I pulled this down locally and ran the tests, which all passed and noticed there were a lot of new vcr cassettes, which at least some were from the cukes that are failing on CI... so I had the idea to commit them and push it up to see.

Not sure it will help, feel free to rollback the commit, if it doesn't help

**Comment by mattwr18** [comment]
didn't help :worried: I did notice a lot of these
```
Google API error: request denied (You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account).
```
in the build output

**Comment by tansaku** [comment]
hi @StlMaris123 - I think I've made some progress here by fixing up some of the rubcop issues and removing some of the un-needed specs - to experiment I put in a new PR: https://github.com/AgileVentures/LocalSupport/pull/1090 where I managed to get the cukes to go green at least once ...

**Comment by tansaku** [comment]
but the services themselves look great!



thanks so much for working on this and the complexity of the build process - still not sure what the underlying problem was ...

**Comment by tansaku** [comment]
hi @StlMaris123 thanks so much for all your work on this.  I'm going to pull in the same commits as part of a different PR #1095 - so I'll close this one for the time being

**Pull request closed without merging**
