### PR TITLE
Make cukes use fake sinatra app for geocoding

### PR DESCRIPTION
**Pull request by mtc2013**
I am proposing this change because while working on a bug fix I am finding it necessary to simplify testing.

The bug's PT is https://www.pivotaltracker.com/story/show/93410464

"editing postcode does not appear to trigger geocode event"

Our current testing does not care about postcode, just the address.  By going through the Sinatra app we can make all our tests postcode aware in one place.

### CODE REVIEW

**Comment by tansaku** [comment]
this certainly looks like a sensible step - although as discussed one alternative is to allow VCR to pick up the slack for all network interactions in feature tests.

I think this needs rebased with develop and would be great to get my bundle update of geocoder in there too ..

Presumably this is not dependent on #177 or should that be pulled in first?

**Comment by mtc2013** [comment]
No it's not dependent on #177.

**Comment by mtc2013** [comment]
@tansaku up to date with upstream now.

**Comment by mtc2013** [comment]
@tansaku if #170 is a better consolidation of internet dependencies, we can use that instead.

**Pull request merged**
