### PR TITLE
Fix doit vol op import tasks[fixes #127384707]

### PR DESCRIPTION
**Pull request by Maroo-b**
https://www.pivotaltracker.com/story/show/127384707
Issue description: we had vol op from doit persisted without longitude and latitude. The cause of the issue was an after_validation in Volunteer Op model which set longitude and latitude attributes of record to nil if there is no address.

Work done:
- Remove after_validation in volunteer_op, it sets longitue and latitude
  of record to nil if there is no address

- Add filter for doit vol op to save only vol ops with longitude and
  latitude coordinates

### CODE REVIEW

**Comment by tansaku** [comment]
thanks for working on this @Maroo-b - I think we could probably use a cucumber scenario for this.  I think if we have a bug occur in production then we want a write up of it in our cucumber docs.

Having read through once I'm not quite following the problem.  Maybe it just needs more study on my part, but I think that's also a warning signal we need a more "readable" cucumber scenario for this.  Happy to collaborate on this asynchronously if it will be a while before you can get to this again ...

**Comment by bryszard** [comment]
Hey guys, I was working on db:seed right now and I found that when I use now the task `rake db:import_doit` locally, ALL of volops have nil latitude, longitude, addres and organisation_id and it throws me a NoMethod for Nil error on `rails s` when getting to volops.

So I guess the problem is on our side and it may be the callback `after_validation :clear_lat_lng` in the volunteer_op model.

**Comment by Maroo-b** [comment]
@bryszard you are right, this PR is intended to fix that issue, but we need a feedback from @ZmagoD to know why he implemented  `after_validation :clear_lat_lng` :)

**Comment by Maroo-b** [comment]
@tansaku so should we merge this fix or wait for @ZmagoD  feedback? because the recurrent task for importing doit vol ops is disabled temporary.

**Comment by ZmagoD** [comment]
Hi @Maroo-b I checked this method and the problem is if you delete the clear_lat_lng method when the user add a different address/postcode of the opportunity the marker will be updated to a new location and if the user choose to remove the address/postcode of the opportunity the marker location goes to the organization address. Without clear_lat_long the marker will not update/fallback to organization location and will stay on the previous location. Why do you want to clean this method?

**Comment by Maroo-b** [comment]
@ZmagoD thanks for the feedback, now I understand the utility of `clear_lat_lng` 
The issue is that for volunteer op from doit we persist longitude and latitude coordinates but not the  address which results in setting the coordinates for all the doit vols op to nil. 

As a solution we may add a condition for the callback to use it with volunteer ops from 'local' source.
@tansaku should we refactor by creating separate class for doit volunteer_op and local volunteer_op ? (we start to have conditional validations based on type)

**Comment by tansaku** [comment]
@Maroo-b separate class is probably the way to go ..., but the priority is whatever gets the bug fixed in production quickly ...

**Comment by Maroo-b** [comment]
@tansaku PR updated

**Comment by mtc2013** [comment]
@tansaku please review

**Comment by tansaku** [comment]
@Maroo-b it would be interesting to see if your new test here will pass against the current develop - maybe cherrypicking it out is the way to go ...

**Comment by Maroo-b** [comment]
@tansaku that interesting so should I update this PR ? or just we can restart the CI build ?

**Comment by tansaku** [comment]
at the very least I think we need to remove this commit: 7c261a01ba5638ce28b9244f72037c8e6855cde4 - that's the broken one

**Comment by Maroo-b** [comment]
@tansaku I suggest that I submit a new PR to add the regression test (as simple solution)
I saw that I added a regression test to the model spec file, so it will be an opportunity to refactor the last tests added.

**Comment by tansaku** [comment]
yeah, new PR is good - if you do one, please close this old one

**Comment by Maroo-b** [comment]
@tansaku I added a simple validator to save only doit volunteer op that have longitude and latitude coordinates. (https://github.com/AgileVentures/LocalSupport/pull/335/files#diff-db13357b47767943d6120c611c84d181R35 ) 

Do you think that we should keep this validator or it's safe to proceed without it ?

**Comment by tansaku** [comment]
@Maroo-b I am not immediately sure - I'd need to work through the code flow in detail.  I think the key thing is to make sure that we have cucumber tests describing the expected functionality - is there a test failure that we can expose with our tests that this validator would fix?

**Comment by Maroo-b** [comment]
@tansaku after reflection, that depends on doit results, for the moment all imported volunteer op have longitude and latitude coordinates. 

In our case I prefer to go on defensive side, because if we import volunteer op with a missing coordinates it's enough to reproduce to last production bug. 

Anyway I added the regression test for the `clear_lat_lng` callback in this new PR https://github.com/AgileVentures/LocalSupport/pull/354 and I'm interested to know your point of vue.

**Pull request closed without merging**
