### PR TITLE
CSS layout on volunteer detail page #103878360 

### PR DESCRIPTION
**Pull request by ZmagoD**
I have added the org-information it to the volunteer show page to get the same styling like the organisation show page.

### CODE REVIEW

**Comment by deepskd** [comment]
This does fix the solution but is it the right thing to add a css selector thats not relevant for this page at least in the name.

**Comment by ZmagoD** [comment]
Thank you for the info :) I check it again and find out that removing the div do the trick

**Comment by tansaku** [comment]
@ZmagoD so want to update this?

**Comment by ZmagoD** [comment]
@tansaku  I already removed it you can merge this.

**Comment by tansaku** [comment]
thanks @ZmagoD - sorry I missed that :-)

**Pull request merged**
