### PR TITLE
[WIP] move search on top of map in mobile view 

### PR DESCRIPTION
**Pull request by Kachulio1**
fireshot capture 002 - harrow community network i harrow volunteering - http___localhost_5050_

[#159175247](https://www.pivotaltracker.com/n/projects/742821/stories/159175247)

### CODE REVIEW

**Comment by mattwr18** [comment]
@Kachulio1 getting these failures on the build... what are you getting locally?
Failing Scenarios:
cucumber -p second_try features/organisations/local_resident_seeking_support.feature:17 # Scenario: Find help with care for elderly
cucumber -p second_try features/organisations/local_resident_seeking_support.feature:28 # Scenario: Find a bereavement counsellor
cucumber -p second_try features/organisations/local_resident_seeking_support.feature:45 # Scenario: See a list of current organisations
cucumber -p second_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:31 # Scenario: See a list of current doit volunteer opportunities with a link to  organisation page
cucumber -p second_try features/volunteer_opportunities/doit_volunteer_opportunities.feature:37 # Scenario: See a list of current doit volunteer opportunities with a link to opportunity page
cucumber -p second_try features/volunteer_opportunities/list_volunteer_opportunities.feature:18 # Scenario: See a list of current volunteer opportunities
cucumber -p second_try features/volunteer_opportunities/reachskills_volunteer_opportunities.feature:31 # Scenario: See a list of current reachskills volunteer opportunities with a link to organisation page
cucumber -p second_try features/volunteer_opportunities/show_volunteer_opportunity.feature:18 # Scenario: See a volunteer opportunity and hyperlink

**Comment by mattwr18** [comment]
@Kachulio1 did we get anywhere with this one? I can pull it down locally and see how it is failing locally/ help you get through some of the failures if you want

**Comment by tansaku** [comment]
@mattwr18 @Kachulio1 - is this one now superceded by what Cire is doing?

**Comment by mattwr18** [comment]
yes, I believe that is the idea

**Comment by tansaku** [comment]
@mattwr18 @Kachulio1 so good to close this?

**Comment by Kachulio1** [comment]
yes, you can close that coz cire is going to fix that in the issue his working on.

**Pull request closed without merging**
