### PR TITLE
Vcr_cucumber_only

### PR DESCRIPTION
**Pull request by decareano**
@tansaku; This is a PR for VCR cassettes used in Cucumber Scenarios only. 
We have cassettes in the following features. I also enclose the outcome on those features.

Without_users.feature     `passes with cassette`
Invited Users Page          `passes with cassette`
Map of local charities       `fails with cassette entirely. nothing passes`
Propose_new_organization.feature  `fails some scenarios, passes some scenarios`
Remind_charity_admin_to_update_page.feature   `passes with cassette`
This-is-my-org.feature  `passes with cassette`
Sign_in.feature  `passes with cassette`
Map_volunteer_opportunities.feature `fails some scenarios, passes others`

In an ideal outcome, you should have `249 scenarios passing` with internet ON and `16 failures` when you turn internet OFF.

Most of the failures are related to VCR gem not being able to record maps and/or measle/markers. We should work, as Sam suggested on: `cucumber features/home_page/map.feature:22

### CODE REVIEW

**Comment by ZmagoD** [comment]
@decareano I think you should cherry-pick relevant commits.

**Comment by tansaku** [comment]
@decareano this is the cucumber output I get when online:

https://gist.github.com/tansaku/adc8e7b83d2763e94f57

**Comment by tansaku** [comment]
@decareano similar for single test online: 

https://gist.github.com/tansaku/ebc14942100d69080374

**Comment by tansaku** [comment]
@decareano then this is what I get for that same single test offline:

```
→ bundle exec cucumber features/home_page/map.feature:22 --format progress
Using the default profile...
....WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.6.
Request to unknown URL: http://maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("http://maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry")
To allow requests to URLs from this host:
  page.driver.allow_url("maps.google.com")
Request to unknown URL: http://www.google-analytics.com/analytics.js
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("http://www.google-analytics.com/analytics.js")
To allow requests to URLs from this host:
  page.driver.allow_url("www.google-analytics.com")
Request to unknown URL: https://www.expeditedssl.com/ssl-secure-badge.png
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("https://www.expeditedssl.com/ssl-secure-badge.png")
To allow requests to URLs from this host:
  page.driver.allow_url("www.expeditedssl.com")
.F

(::) failed steps (::)

expected to find css ".measle" 3 times but there were no matches (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/map_steps.rb:43:in `/^I should( not)? see the following (measle|vol_op) markers in the map:$/'
features/home_page/map.feature:24:in `Then I should see the following measle markers in the map:'

Failing Scenarios:
cucumber features/home_page/map.feature:22 # Scenario: Show all charities in map on homepage map

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m4.551s
```

**Comment by tansaku** [comment]
so it may well be that the vcr sandbox is not properly capturing these things.  Feel free to work on a different feature if you are finding this all getting a bit frustrating, but to make progress on this we need to dig down to find what causes what.

Personally I would start taking apart the individual test and gradually removing things step by step and finding out what individual actions caused particular bits of output, and then research what those individual pieces were doing if you know what I mean?  Maybe you could join me in a hangout to discuss at some point ...?

**Comment by decareano** [comment]
@tansaku, thanks for the input. I will continue working on this issue but I think it's going to take a while. There are so many moving parts. In the meantime, I will work on other PT's features. I do think it 's a good idea to do a HOA once we get some clarifications on the issue of cukes and maps/markers/measle and capybara/webkit.

**Comment by tansaku** [comment]
@decareano there are many moving parts but the process is simple if you take a single scenario and gradually remove elements monitoring the change in the output at each stage.  I'll try and do a walkthrough or video for you if you're still not clear on the approach

**Comment by decareano** [comment]
@tansaku, a video/walkthrough would be great. I would like to get a better idea on debugging step definitions. Also, any features I can work on while I continue to work on VCR? thanks.

**Comment by tansaku** [comment]
@decareano please see this mornings scrum video - we go through step by step on attacking that problem and talk about other tickets for people to pick up: https://www.youtube.com/watch?v=xxnJ38DD9dU

**Comment by decareano** [comment]
@tansaku, I have not had time to look at the video yet.

**Comment by tansaku** [comment]
@ZmagoD do you want to take a look at this video  https://www.youtube.com/watch?v=xxnJ38DD9dU where I talk about how to approach this problem?

**Comment by decareano** [comment]
@tansaku, using code below in `features/support/features/env.rb`, I am able to suppress capybara's log messages. The test(s) are still failing. 
https://github.com/thoughtbot/capybara-webkit/issues/717
I am under the impression that "whitelisting" is not good coding practice? Anyway, I could submit a PR if we decide to go that route:
`Capybara::Webkit.configure do |config|
      #config.debug = true
      config.block_unknown_urls
end`

I watched the video: 
1. Geocoder update got rid of lots of capybara log messages. Some remained.
2. Failures ONLINE and in ISOLATION are mostly related to rendering the MAP. I am playing with the debug feature in VCR to see if I can see something there.
3. I have trimmed down the test to one organization. I still get the error. But I see your point about eliminating items.
4. Michael is right. We have the log messages issue as well as the tests failing in isolation.

**Comment by tansaku** [comment]
great progress @decareano - sorry I haven't had a chance to look at this properly yet - it's always hampered by my intermittent connectivity on trains, and I was off Mon/Tues this week - also the MOOC is taking up a lot of my attention.  I pushed the client meeting back to next Thursday - will definitely review this before then

**Comment by tansaku** [comment]
reviewing this now @decareano  

Regarding the trimming down - one can go even further - can one set up a test of another page - I suspect here that it is the presence or the absence of the map that either gives us a big chunk of capybara-webkit messages, or not, as the case may be.

I added the code as you suggested:

```ruby

Capybara::Webkit.configure do |config|
  #config.debug = true
  config.block_unknown_urls
end
```

and saw all the messages disappear as you indicated, as well as the test failing (I was in a tunnel so no internet I think):

```
$ bundle exec cucumber features/home_page/map.feature:22 --format progress
Using the default profile...
....WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.6.
.F

(::) failed steps (::)

expected to find css ".measle" 3 times but there were no matches (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/map_steps.rb:43:in `/^I should( not)? see the following (measle|vol_op) markers in the map:$/'
features/home_page/map.feature:24:in `Then I should see the following measle markers in the map:'

Failing Scenarios:
cucumber features/home_page/map.feature:22 # Scenario: Show all charities in map on homepage map

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m4.898s
```

I would say that this configuration is the way to go, i.e. we should be blocking anything external.  The remaining question is can we make this text pass somehow.  We shouldn't be hitting any 3rd party servers as part of our tests, so I don't think we should be "whitelisting" sites to hit.  However if we block them (and VCR is not recording them) can the test still pass ...?

Running again with connection they still fail

Big thing is that we need to be clear exactly what environment our feature tests are running in.  I know we are using [capybara-webkit](https://github.com/thoughtbot/capybara-webkit) as a headless browser which then relies on Qt and xvfb.

capybara-webkit is creating the javascript environment that the map is running in, and maybe therein lies our problem - maybe we can't sandbox that without breaking the tests ...

Maybe this environment will only allow our tests to pass if it can access 3rd party services.  Maybe we have to live with that; or maybe we need to switch to something else that will allow us to sandbox that javascript environment; and then the question is whether it is worth the effort to switch over.

The ideal of never hitting 3rd party services is a nice one, but Google (who we are hitting), isn't complaining, so maybe whitelisting is the path of least resistance to have the tests pass and remove the capybara-webkit output; although that will still not allow the tests to pass without an internet connection; although perhaps I'm the only person who ever tries to run them without an internet connection ...

Anyway, clear path here is to open a ticket with capybara-webkit ...

https://github.com/thoughtbot/capybara-webkit/issues/850

**Comment by tansaku** [comment]
@decareano a comment on https://github.com/thoughtbot/capybara-webkit/issues/850 suggests that we should look at the puffing billy gem that apparently can provide VCR like functionality through the capybara webkit proxy:

https://github.com/oesmith/puffing-billy

At the very least we should try out this solution

**Comment by decareano** [comment]
@tansaku, I saw that. I will look into it.

**Comment by tansaku** [comment]
great thanks @decareano - will be interested to see how easy or difficult it is to set up

**Comment by ZmagoD** [comment]
@tansaku I will take a look at this gem.

**Comment by ZmagoD** [comment]
@decareano I moved the billy configure block to the features/support dir and the gem start to work. All the test are passing when online or offline. Please check my branch https://github.com/ZmagoD/LocalSupport/tree/vcr-billy-cucumber

**Comment by decareano** [comment]
@zmagod, great !!. I will check it out. I did a bit of testing with the gem and indeed tests were passing both online and in isolation. I only run the scenario we always use (`features/home_page/map.feature:22`). Couple of issues though: I was getting log messages from capybara again and the setup work with my Mac but not in Ubuntu. what are you using?

**Comment by ZmagoD** [comment]
Yes I'm using Ubuntu. I still get a log Request to unknown URL: www.......   These log messages can be suppressed by using the  page.driver.allow_url() method

**Comment by decareano** [comment]
@tansaku, @zmagod, I still have 2 issues with the branch. 1. Test(s) are passing in ISOLATION but now the capybara log messages are back in my Mac. 2. I cannot make it work in my ubuntu VM (zmagod ubuntu setup works though). I think Puffing-billy has some nice features stubbing the browser. A bit of progress.

**Comment by tansaku** [comment]
thanks @decareano and @ZmagoD - tried this locally and got this error:

```Missing EM-Synchrony dependency: gem install em-http-request```

so added ` gem 'em-http-request'` to test group, and that's what's breaking the build at the moment.

**Comment by ZmagoD** [comment]
@tansaku do you check my repo?

**Comment by tansaku** [comment]
and have you guys read the notes on using puffing billy with webmock and VCR? 

https://github.com/oesmith/puffing-billy#working-with-vcr-and-webmock

In the meantime I can confirm that on `features/home_page/map.feature:22` the presence or absence of puffing billy does seem to determine whether the tests can pass in isolation or not.  And the presence or absence of puffing billy does not seem to have any effect on Capybara::Webkit (?) log messages.  Have you read the following about those log messages?  Should we now white list everything since puffing billy will handle them?

* http://blog.arkency.com/2015/02/upgrade-capybara-webkit-to-1-dot-4-and-save-your-time/
* https://github.com/thoughtbot/capybara-webkit/issues/717

**Comment by tansaku** [comment]
@ZmagoD I haven't checked your repo - if you want me to, please open a pull request

**Comment by tansaku** [comment]
@zmago @decareano do check out what jpb and yana are doing with a simple rails app to display the do-it data.  It might be a good idea to help them get that set up with VCR and puffing billy to practice getting everything properly sandboxed for a smaller app before getting everything in LS ... see slack for details ... does it make sense to close this pull request in the meantime?

**Pull request closed without merging**
