### PR TITLE
132571821 Volenteers to all have individual title tags

### PR DESCRIPTION
**Pull request by lollypop27**
PT Story:
https://www.pivotaltracker.com/story/show/132571821

- Add set_meta_tag to controller

### CODE REVIEW

**Comment by lollypop27** [comment]
@tansaku ready for review

**Comment by tansaku** [comment]
thanks @lollypop27 - did you review the codeclimate comments?  https://codeclimate.com/github/AgileVentures/LocalSupport/pull/394 are their any you think you could fix?  Or do you need extra input from me on how they might be addressed?

**Comment by lollypop27** [comment]
@tansaku I see codeclimate is complaining about "private" in the applications controller, should it be removed?

**Comment by tansaku** [comment]
@lollypop27 yes definitely - we have private in there twice and it's only needed once - one of the issues with increasing file length ... would be nice to be able to run CC analysis locally to catch these things before pushing ...

**Comment by lollypop27** [comment]
@tansaku sorry my rookie fault. To excited to have learnt something new and get it merged in.

**Comment by lollypop27** [comment]
@tansaku Yay! All test pass!

**Pull request merged**
