### PR TITLE
client side organization website validation

### PR DESCRIPTION
**Pull request by samover**
Client side validation. All is green, but I will pull out the different changes to different tickets, because I mixed in some server side validation.

Pivotal Ticket: https://www.pivotaltracker.com/story/show/62111296

also related to https://www.pivotaltracker.com/story/show/61986126

### CODE REVIEW

**Comment by johnnymo87** [comment]
I'm not a huge fan of Rail's concerns, but it may make sense to try them out in this case, where we're copy-pasting code between these different organisation models. 

[Docs](http://api.rubyonrails.org/classes/ActiveSupport/Concern.html)

In `app/models/concerns/url_validations.rb`, you could have something like:
```
module Concerns
  module UrlValiations
    extend ActiveSupport::Concern
    
    # code for before_validation, code for validates_format_of
  end
end
```

And then in the models you'd just have:
```
include Concerns::UrlValidations
```

**Comment by tansaku** [comment]
@johnnymo87 good point - @samover what do you think of that refactoring suggestion?

**Comment by samover** [comment]
Absolutely. However, the official docs suggest validator classes, which is what I have implemented http://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html

**Comment by tansaku** [comment]
@samover cool - but you've got some repetition that could be DRYed out?  Do you have an angle on how to do that, or would you like more input and/or a pairing session?

**Comment by samover** [comment]
Hi. did a pull request for server side validation. will work on client side now

**Comment by samover** [comment]
oops. cross that. seems I broke something ;-)

**Pull request closed without merging**
