### PR TITLE
Miniprofiler

### PR DESCRIPTION
**Pull request by johnnymo87**
For consideration after [Include all category types in search](https://github.com/AgileVentures/LocalSupport/pull/116) is merged.

Michael and I were playing around with [miniprofiler](https://github.com/MiniProfiler/rack-mini-profiler), and we noticed that `build_map_markers` was taking a long time. It's a mix of database and application logic, and I decided to try to push more logic into the database layer, and optimise it there.

In an attempt test the database speed while uncached, I did the following steps while switching from the develop and this branch, with local and production data.
* restart postgres
* screenshot of sql calculation, ending when it first hits `app/controllers/organisations_controller.rb:32`

I'm looking at what my total runtime at that point.

#### Local, first commit: 10900 ms
trhdbd

#### Local, last commit: 7300 ms
hgfhgdfhdfh

#### Production, first commit: 12600 ms
rteyehts

#### Production, last commit: 7800 ms
oiuhmjg

## EDIT
Returning to this a week later ...
I must have really needed to reboot my computer the day I did this, because these runtimes are atrocious. I'm now seeing the benchmark change from 2000ms to 1500ms from develop to this branch, with production data.

### CODE REVIEW

**Comment by tansaku** [comment]
cool - so what's the outlook here? pull in the original first?

**Comment by mtc2013** [comment]
Yes

**Comment by mtc2013** [comment]
This might be ready to go.

**Comment by tansaku** [comment]
oh yeah - let me know when I should start reviewing

**Comment by mtc2013** [comment]
I think you can start reviewing it now, if you want.

**Comment by tansaku** [comment]
so this all sounds good in principle - moving logic into DB for speed - although I'm not getting a strong sense of where in the system the slowness is - is it in drawing the map?  How does the end user experience the slowness @mtc2013 @johnnymo87 ?

**Comment by johnnymo87** [comment]
I was suspicious of [not_updated_recently_or_has_no_owner?](https://github.com/AgileVentures/LocalSupport/blob/develop/app/models/organisation.rb#L198-L200) being called for each of our ~650 organisations on page load. I figured that rather instantiating `users` for each organisation, we could use a calculated column.

**Comment by mtc2013** [comment]
@tansaku the profiling suggests that it speeds up the main loading page by 25% or so.  And the main loading page is our slowest place.

**Comment by mtc2013** [comment]
@tansaku I think the user experiences the slowness first of all by latency when loading the main page.

**Comment by tansaku** [comment]
@mtc2013 right so it's the map load - ironically I had a group of students ask me how we achieved that effect because they thought it looked cool :-)

**Comment by mtc2013** [comment]
@tansaku you mean the way the markers stream in?  That's not the latency I mean.  I mean the response-request latency is what is measured by miniprofiler, I think.

**Comment by tansaku** [comment]
okay let's remove the profiler code and break up that long method and then merge?

**Comment by mtc2013** [comment]
@tansaku I pushed those changes requested.

**Pull request merged**
