### PR TITLE
Upgrade to latest rubygems.

### PR DESCRIPTION
**Pull request by nisevi**
https://www.pivotaltracker.com/story/show/63299434

### CODE REVIEW

**Comment by nisevi** [comment]
@tansaku I upgraded the ruby version to 2.4.2 that is why TravisCI is failing, I don't know about the error in Codeclimate? what do you think?

**Comment by NickSchimek** [comment]
It may be useful to add the rails-bootstrap-forms gem. Although a throough investigation will need to be done to see how this change will affect existing code. 
https://github.com/bootstrap-ruby/rails-bootstrap-forms

**Comment by nisevi** [comment]
Hey @NickSchimek, I think that is a good idea but maybe it would be better if we create another issue on PivotalTracker for the change that you propose :+1: . We also can talk about it in our meeting today :+1:

**Comment by tansaku** [comment]
@nisevi upgrading to the latest ruby requires a little coordination - would be good to do.

There are also lots of gem upgrades to do - I've been doing that using https://dependabot.com/ on some other projects - would be good to do here, but it would generate a fair amount of work.  Perhaps we can discuss in the team meeting today :-)

**Pull request merged**
