### PR TITLE
doit on a new branch [WIP]

### PR DESCRIPTION
**Pull request by Proskurina**
@tansaku As agreed I started from the beginning from tests to see how coverall behaves.

### CODE REVIEW

**Comment by tansaku** [comment]
excellent @Proskurina - looks like coverage is maintained - are all the features in place or is there more to add?

**Comment by Proskurina** [comment]
@tansaku All basic things are in place. But there are many things to add/improve. I think that the list of opportunities in a popup window may be an important one for the client. On the other hand maybe it is better to move a method that makes a request to doit api from controller to a separate service and do some more tests...

**Comment by tansaku** [comment]
good show @Proskurina - are you free to discuss?  was just doing an LS retro now, but will be available at next standup - or kick off that follows that ...

**Comment by Proskurina** [comment]
@tansaku sorry, I missed it... I am ready to discuss further steps tomorrow morning or Wednesday morning

**Comment by tansaku** [comment]
@Proskurina no worries - I was offline this AM (Tuesday) - hope to catch you Wednesday AM - BTW, should we close the old pull request?  i.e. https://github.com/AgileVentures/LocalSupport/pull/216

Also, I've pulled in the billy/vcr components - so you'll need to sync upstream/develop - apologies if that creates some merge conflicts - happy to look at them together with you tomorrow ...

**Comment by Proskurina** [comment]
@tansaku  Yes, please, close the old one.

I will try to merge, but let's discuss tomorrow.

**Comment by tansaku** [comment]
@Proskurina do sync to upstream/develop to sort hound out :-)

**Comment by tansaku** [comment]
great work @Proskurina!  I think we just need a round of refactoring review as we discussed and we can pull in  ...

**Comment by tansaku** [comment]
BTW, did we ever identify what was bothering coveralls in the previous version of the pull request?

**Comment by Proskurina** [comment]
@tansaku Thanks! I solved the problem with Gemfile.lock, did not touch the tests. 
Refactoring would be nice! 
No, I am not sure what was wrong with coveralls...

**Comment by tansaku** [comment]
just for reference here is the video of us discussing the refactoring: https://www.youtube.com/watch?v=FnNIKnIgsu8

**Comment by Proskurina** [comment]
@tansaku All tests pass on local, the one that fails here is not related to do-it

**Comment by Proskurina** [comment]
@tansaku https://safe-basin-52704.herokuapp.com/volunteer_ops

**Comment by tansaku** [comment]
thanks @Proskurina awesome!  I've passed that on to the client.

Let me know how you want to move this forward and how you are getting on thinking about services.

Do also see the discussion in https://github.com/AgileVentures/LocalSupport/pull/245

**Comment by Proskurina** [comment]
@tansaku  I moved the request to do-it api to a service. But `assemble_volunteer_markers` method uses `build_map_markers` method from volunteer_ops_controller, which is used in several actions in the controller, so I am not sure we can make `assemble_volunteer_markers` a service without also making `build_map_markers` a service, but as I understand @johnnymo87 is working on it... what are your thoughts?

**Comment by tansaku** [comment]
We will probably need to expose some callback methods on the controller such as build map markers, which we can ultimately refactor into a service ..., but they can be public callbacks for the time being ...

**Comment by tansaku** [comment]
Just reviewing this in more detail.  I notice that our billy cache "features/req_cache" is full of quite a of facebook and other components that shouldn't be there.  

That's because of the click through on lines 37 and 47 in `features/volunteer_opportunities/doit_volunteer_opportunities.feature`.  We probably shouldn't actually click through the remote site here (i.e. do-it) - just use cucumber/capybara to check that the link is correct.

Regarding the services we should probably have a look at things together.  I'd like to call the service ListVolunteerOpportunities if possible ...

**Comment by Proskurina** [comment]
@tansaku Thank you! Will correct tests and the name tonight. When will you have time to work on services? What about tomorrow after the morning stand up?

**Comment by tansaku** [comment]
@Proskurina tomorrow am is definitely a possibility - I have to go out at 11am so there's some time before that

**Comment by Proskurina** [comment]
@tansaku perfect! See you then!

**Comment by Proskurina** [comment]
@tansaku I added tests, though I did not manage to put mock data to a separate file in fixtures, need your help here.. 

On other matters:
- id for doit markers is made up now, we did it as id(integer) was required to build markers, but it should not be a problem when doit vol ops moved to our database
- I did not add feature activation in seed.rb, should I add it?
- in seed.rb we do not use destroy_all in the beginning, so if it is run more than once, everything is doubled/tripled/etc.

**Comment by tansaku** [comment]
hi @Proskurina - great work.  I can get that data in fixtures or we can do it together if you have time.

The two changes you suggest for seed.rb make sense - would be good to add at least the feature activation.  The destroy_all could be a separate ticket and pull request.  Want to open a separate issue for that?

Opening the issue doesn't mean that you're responsible for fixing it :-) It's good practice to open other tickets when you see broader issues that are beyond the scope of the pull request that you are working on.

**Comment by Proskurina** [comment]
@tansaku Thank you! I added the feature activation to seeds.rb. Sorry, but I travel to Russia this week, so will not be able to do much... If you could do the data in fixtures, that would be great, as I do not want to delay with it... I can make the separate ticket for destroy_all at some point during the week.

**Comment by tansaku** [comment]
sounds good @Proskurina - have a great trip - I'll take care of everything else including the destroy_all ticket :-)

https://www.pivotaltracker.com/story/show/113803075

Creating new tickets is the kind of thing one wants to get out of the way rather than putting on the todo list :-)  Of course for me creating tickets is really fast, but it's the kind of thing that can easily be forgotten ...

**Pull request merged**
