### PR TITLE
Adds search to volops show page [fixes: #117609727]

### PR DESCRIPTION
**Pull request by ZmagoD**
https://www.pivotaltracker.com/story/show/117609727

### CODE REVIEW

**Comment by ZmagoD** [comment]
Wow hound didn't bark today I deserve a beer

**Comment by tansaku** [comment]
yes, but we did have another concealed failure:

```
  @javascript @billy
  Scenario: Unregistered User                                                                                                                  # features/individual_charity_pages/this-is-my-org.feature:54
    Given I click "This is my organisation" on the "Helpful Folk" page and stay there                                                          # features/step_definitions/basic_steps.rb:415
    And I click "toggle_link"                                                                                                                  # features/step_definitions/navigation_steps.rb:129
    When I sign up as "normal_user@myorg.com" with password "pppppppp" and password confirmation "pppppppp"                                    # features/step_definitions/authentication_steps.rb:27
      Unable to find css ".dropdown-menu" (Capybara::ElementNotFound)
      features/individual_charity_pages/this-is-my-org.feature:57:in `When I sign up as "normal_user@myorg.com" with password "pppppppp" and password confirmation "pppppppp"'
    Then I should see "A message with a confirmation link has been sent to your email address. Please open the link to activate your account." # features/step_definitions/basic_steps.rb:336
    And I should be on the show page for the organisation named "Helpful Folk"                                                                 # features/step_definitions/navigation_steps.rb:89
    Then I should see "You have requested admin status for Helpful Folk"                                                                       # features/step_definitions/basic_steps.rb:336
    And "normal_user@myorg.com"'s request for "Helpful Folk" should be persisted                                                               # features/step_definitions/basic_steps.rb:431
    And I click on the confirmation link in the email to "normal_user@myorg.com"                                                               # features/step_definitions/authentication_steps.rb:132
    When I sign in as "normal_user@myorg.com" with password "pppppppp" on the legacy sign in page                                              # features/step_definitions/authentication_steps.rb:80
    Then I should be on the show page for the organisation named "Helpful Folk"                                                                # features/step_definitions/navigation_steps.rb:89
    And an email should be sent to "superadmin@localsupport.org" as notification of the request for admin status of "Helpful Folk"             # features/step_definitions/email_steps.rb:25
Failing Scenarios:
cucumber features/individual_charity_pages/this-is-my-org.feature:54 # Scenario: Unregistered User
```
this is the related PT ticket to that: https://www.pivotaltracker.com/story/show/119350175 we've really got to get that fixed as it's totally confusing - at least the coverage drop alerts us, but ... well anyway, are the specs passing locally for you?

**Comment by ZmagoD** [comment]
Hi @tansaku locally the rspec passes but the cucumber passes only if I use xvfb-run if not this error pops out and this is the only spec that fail.
      /usr/local/rvm/gems/ruby-2.3.0@global/gems/capybara-webkit-1.6.0/bin/webkit_server failed to start. (Capybara::Webkit::ConnectionError)
      features/admin/organisation_reports/without_users.feature:42:in `Given cookies are approved'

**Comment by tansaku** [comment]
@ZmagoD thanks for this one - I think I'll need to close this and re-open having cherry picked your latest commit of it

**Pull request closed without merging**
