### PR TITLE
151326803 [WIP] test volunteer opportunities   map works correctly when missing Long and Lat values

### PR DESCRIPTION
**Pull request by vardyb**
https://www.pivotaltracker.com/story/show/151326803

Work in progress to create new cucumber scenario to test volunteer opportunities map works correctly when missing Long and Lat values.

The purpose of this PR is to build new acceptance test that will test the map functionality for volunteering opportunities without valid longitude and latitude values.  It was identified when implementing fix for #473 that there were insufficient tests.

Thanks to @gnomonunes for his involvement.

### CODE REVIEW

**Comment by tansaku** [comment]
looks like a great start @vardyb

**Comment by vardyb** [comment]
@tansaku  - based on another session with @gnomonunes  we feel that testing for this scenario in the acceptance tests is not a reliable approach and it feels like it should be tested using Jasmine.  Before this though @gnomonunes  feels there should be a refactor of the javascript so that it will hopefully allow for a more reliable test using Jasmine.  With the current code this does not seem viable.  We would like to discuss this further in the LocalSupport planning meeting later today.

**Comment by vardyb** [comment]
@tansaku as per conversation in today's scrum I've cleaned up the new tests ready for review and merge

**Comment by tansaku** [comment]
Thanks @vardyb - this looks great :-)

**Pull request merged**
