### PR TITLE
url validation

### PR DESCRIPTION
**Pull request by samover**
Show flash error when entering invalid url. 
`http://test` is considered a valid url

### CODE REVIEW

**Comment by tansaku** [comment]
thanks for this @samover - we need a sync to upstream/develop to check this one ...

**Comment by tansaku** [comment]
hi @samover - so we'll need to merge in the upstream to get this one pulled in I think ...

**Comment by samover** [comment]
same as we did for name_and_description?

**Comment by tansaku** [comment]
right, it should be easier this time I think as I don't think we will have to cope with reverts, but let's see ...

**Comment by samover** [comment]
I can't find any problems since I merged upstream a few weeks ago.

**Comment by tansaku** [comment]
@samover ah great - in principle this could be merged then ... I might take a little extra time checking after what happened last time :-)

I have a side-chore to review to what depth we should be checking validation support in acceptance tests ... https://www.pivotaltracker.com/story/show/113996343

**Comment by tansaku** [comment]
interesting this branch says it has no merge conflicts, but I get one when merging in develop locally ...

**Comment by samover** [comment]
Ok. I'll revert the merge and make sure I have the latest fron develop

**Comment by tansaku** [comment]
hi @samover - looking at this I think we have the same problem as before - the earlier reversions are cancelling out your changes to the validations - so I'm not seeing them in the pull request itself.

Looks like another interactive rebase is required :-(

I also note that the vcr.log should not be appearing in the commit since it's in the .gitignore file, so that's a little weird ...

**Comment by samover** [comment]
I rebased again, but I don't know why it's still causing problems on your side. merging it locally in the the most recent upstream/develop does not delete anything of this pull request.

**Comment by tansaku** [comment]
no but look in the files in this pull request on github - there are no validations - you may have to rebase interactively against an earlier commit ...

the files are not being deleted - but the changes are being reverted due them having matching revert merges earlier ...

**Comment by samover** [comment]
I see them now. last rebase must have fixed it

**Comment by tansaku** [comment]
the current code has:

```
  validates_url :website, :prefferred_scheme => 'http://', :if => Proc.new{|org| org.website.present?}
  validates_url :donation_info, :prefferred_scheme => 'http://', :if => Proc.new{|org| org.donation_info.present?}
```
 
Since your last rebase I now see some shoulda's in base_organisation_spec, but I don't see any changes to the base_organisation or am I missing something.

What validations were we going for with this pull request?

Also sorry for the pain but we've merged in ruby 2.3 - do you want to sync to develop and upgrade? thanks

**Comment by samover** [comment]
no need to change base_organisation. the existing validations do the job

**Comment by tansaku** [comment]
oh right, given as you say that http://test is considered valid and that http:// is automatically prepended ... but so is there any case in which the user would actually see the flash message saying the URL is invalid?  only if inappropriate characters are used? e.g. the ## that you have in the test?

ah, we are using https://github.com/perfectline/validates_url ... okay, so this is just adding the flash message - right sorry ... :-)

I find that the preffered_scheme misspelling is kind offputting (not a blocker for this pull request) that seems to come from https://github.com/zdenal/url_validator

Weird, which one are we actually using ... hmmm ... looks like some investigation is warranted there ... https://www.pivotaltracker.com/story/show/114080323

**Comment by samover** [comment]
yes. I really do not like how they spelled it. We are using the zdenal url_validator gem becasue it adds the scheme automatically from the model. other gems don't have that

**Comment by tansaku** [comment]
right - we could do pull request on that gem to fix it ... also confused because the gem names seem ambiguous ...

**Pull request merged**
