### PR TITLE
Tweaks to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tansaku**
Addresses https://www.pivotaltracker.com/story/show/113802431

### CODE REVIEW

**Comment by tansaku** [comment]
@ethanluoyc I made these documentation updates based on some issues you encountered.

Hoping other members of the team such as @johnnymo87 @ZmagoD and others will glance over it and confirm that I'm describing our approach.  Comments from everyone very welcome - just trying to ensure we have an agreed upon engineering process :-)

**Comment by ethanluoyc** [comment]
I think the updates are useful for new comers like me.

For forking the project, I think it is better if you include the exact link of the project for reference here. I noticed that there is one LocalSupport project under you personal account and another forked version under Agile Ventures. While it is intuitive to fork from the one from Agile Ventures org, including the exact address eliminates any ambiguity.

**Comment by C9905557** [comment]
Seems the there is a typo in the command:

`git pull upstream/develop`

Gives an error, while 

`git pull upstream develop`

works fine.

**Comment by tansaku** [comment]
thanks @ethanluoyc and @C9905557 !  I'll get those fixed up straight away ...

**Pull request merged**
