### PR TITLE
Modified BreadCrumbs and added Cucumber Feature Tests

### PR DESCRIPTION
**Pull request by sstamoulas**
https://www.pivotaltracker.com/n/projects/742821/stories/149069793

Modified Breadcrumbs where needed and added Cucumber Tests

### CODE REVIEW

**Comment by nisevi** [comment]
@sstamoulas @tansaku I have opened an issue here https://github.com/travis-ci/travis-ci/issues/9130 regarding `travis-ci` not running anymore

**Comment by nisevi** [comment]
@sstamoulas could you try pushing something like:

`git commit --allow-empty -m "Trying to activate travis-ci."`

in order to activate travis-ci again, please :+1:

**Comment by nisevi** [comment]
Hi there @sstamoulas I tracked some of the issues and I was able to see:

```
bundle exec rspec ./spec/controllers/organisations_controller_spec.rb:324
Run options: include {:locations=>{"./spec/controllers/organisations_controller_spec.rb"=>[324]}}

Randomized with seed 53763

OrganisationsController
  POST create
    while signed in as superadmin
      with valid params
        assigns a newly created organisation as @organisation (FAILED - 1)

Failures:

  1) OrganisationsController POST create while signed in as superadmin with valid params assigns a newly created organisation as @organisation
     Failure/Error: bba.send("#{action_name}_breadcrumb".to_sym)
     
     NoMethodError:
       undefined method `create_breadcrumb' for #<BreadcrumbsByAction:0x000056118ebe1338>
     # ./app/controllers/application_controller.rb:82:in `add_breadcrumbs'
     # ./app/controllers/base_organisations_controller.rb:5:in `add_breadcrumbs'
     # ./spec/controllers/organisations_controller_spec.rb:326:in `block (5 levels) in <top (required)>'

Top 1 slowest examples (0.1503 seconds, 32.8% of total time):
  OrganisationsController POST create while signed in as superadmin with valid params assigns a newly created organisation as @organisation
    0.1503 seconds ./spec/controllers/organisations_controller_spec.rb:324

Finished in 0.45892 seconds (files took 9.27 seconds to load)
1 example, 1 failure
```

I hope it helps :+1: 

Maybe you forgot to track the latests changes and push them?

**Comment by tansaku** [comment]
great work getting all these passing @sstamoulas :-)

**Comment by nisevi** [comment]
@tansaku @sstamoulas can we merge this one?

**Pull request merged**
