### PR TITLE
Fix rubocop issues on hash syntax in all controller actions

### PR DESCRIPTION
**Pull request by StlMaris123**
This Pr is not linked to any issue number.
It simply fixes rubocop errors on hash syntax

### CODE REVIEW

**Comment by sigu** [comment]
Is it possible to get screenshot of the rubocop errors? @StlMaris123

**Comment by StlMaris123** [comment]
screenshot from 2018-02-20 18-19-25
@sigu I focused on the  errors dealing with hash syntax across all controllers

**Comment by sigu** [comment]
Cool, creating an issue for this then will link. Will do a review and merge if everything is cool :+1:

**Comment by StlMaris123** [comment]
cool. There are over 700 issues, will you create for all?

**Comment by sigu** [comment]
@StlMaris123 😄 you making sense

**Pull request merged**
