### PR TITLE
Change expired token message when resetting password

### PR DESCRIPTION
**Pull request by Aleks4ndr**
I had to change devise helper to change message, because errors.full_messages return array of strings where strings have been built as "%{attribute} %{message}". I cannot get rid of 'Reset password token' mention otherwise.

### CODE REVIEW

**Comment by tansaku** [comment]
great work getting this working @Aleks4ndr 

Interesting question relating to whether this is better tested with a controller test versus an acceptance test.

I lean towards a cucumber acceptance test as this was something specifically identified by the client as being a problem with the system, although of course acceptance tests are expensive and slow, so we would prefer to avoid them where possible.

See the discussion in https://github.com/AgileVentures/LocalSupport/pull/234

**Comment by tansaku** [comment]
we could just merge this @Aleks4ndr - but would be great to have at least some discussion about whether we should prefer a cucumber test from this.  Perhaps @johnnymo87 might have some thoughts ...

**Comment by tansaku** [comment]
@Aleks4ndr since I haven't heard from you I guess I should write the cucumber test myself?

**Comment by Aleks4ndr** [comment]
Sorry Sam, I just don't know how to properly get the change_passwordd_token from the email box in a Cucumber test an persist it between steps.

**Comment by tansaku** [comment]
@Aleks4ndr any instance variable will persist between cucumber steps

http://stackoverflow.com/questions/18962439/preserve-variable-in-cucumber

don't use global vars if you can avoid it.

**Comment by tansaku** [comment]
@Aleks4ndr thanks for the new commits!  sorry about the confusing hound messages - this is not quite configured the way I want ...

**Comment by tansaku** [comment]
@Aleks4ndr - this looks great, I went ahead and did some refactoring of your code - check out:  https://github.com/AgileVentures/LocalSupport/pull/263

I also wonder if we need both the controller integration test and the acceptance test, but since we've written both we'll keep them.   The things I really want to remove are view tests and controller tests that stub out interactions with models, views etc., so if you're happy with my refactorings I'll maybe close this pull request and merge in #263 ?

**Comment by tansaku** [comment]
actually it has some important rubocop config that really needs merged in ... so I might just go ahead and merge (when the CI passes) and close this

**Pull request closed without merging**
