### PR TITLE
[WIP]Change admin to superadmin

### PR DESCRIPTION
**Pull request by marianmosley**

### CODE REVIEW

**Comment by mtc2013** [comment]
I think this might no longer be WIP.

**Comment by tansaku** [comment]
time for me to review then @mtc2013 ?

**Comment by mtc2013** [comment]
I think so, yes.

**Comment by tansaku** [comment]
have started looking through this ...  I am getting a set of fails on my local machine, but I think I'm getting them on my develop branch too.  Trying to sort that out.  

One thing I note is that we are going through converting admin to super-admin consistently through the codebase, which is fine, but if we want to be consistent with that then shouldn't we also be updating the feature folders to refer to the same.  At the moment we still have an admin directory and then various admin_* features.

I'm also thinking it might be good to review exactly what roles we have (or are planning to have), e.g. 

* super-admin - ability to edit all orgs, send invites, delete users, edit static pages
* admin - ability to edit all orgs, but not invites 
* org-admin - ability to edit an individual org

I wonder if 'super-admin' would be better called 'site-admin' although I know the client has used the term 'super-admin'. Writing it out as above makes me feel the need for a role and permissions system, or at least something with permissions that we can associate with particular users --> maybe time to look at cancan again

Not that we have to do a refactoring before pulling all this in, but when I look at methods in the organisation controller like this:

```ruby
  def show
    @organisation = Organisation.find(params[:id])
    @pending_org_admin = current_user.pending_org_admin? @organisation if current_user
    @editable = current_user.can_edit?(@organisation) if current_user
    @deletable = current_user.can_delete?(@organisation) if current_user
    @can_create_volunteer_op = current_user.can_create_volunteer_ops?(@organisation) if current_user
    @grabbable = current_user ? current_user.can_request_org_admin?(@organisation) : true
    @can_propose_edits = current_user.present? && !@editable
   # @next_path = current_user ? organisation_user_path(@organisation.id, current_user.id) : new_user_session_path
    @markers = build_map_markers([@organisation])
  end
```

It definitely feels like there could be a win by setting up a user permissions method that itself had a set of methods for indicating what a user can and can't do e.g.

```ruby
  def show
    @organisation = Organisation.find(params[:id])
    @permissions = current_user.permissions(@organisation) if current_user
    @markers = build_map_markers([@organisation])
  end
```

or possibly

```ruby
  def show
    @organisation = Organisation.find(params[:id])
    @permissions = Permission.assess(current_user, @organisation)
    @markers = build_map_markers([@organisation])
  end
```

Anyhow, the errors I'm getting in cucumber at the moment are in:

```sh
features/home_page/map.feature
features/volunteer_opportunities/map_volunteer_opportunities.feature
```

```sh
expected to find css ".measle" 3 times but there were no matches
expected to find css ".vol_op[data-id='1']" but there were no matches
```

Any ideas?

**Comment by mtc2013** [comment]
@tansaku  Is this still failing locally for you?

**Comment by tansaku** [comment]
they are failing when I am offline suggesting that we have some network dependency in there ... I could go ahead and merge, but might be good to route out that network dependency first ...

**Comment by tansaku** [comment]
can you ( @mtc2013 and @marianmosley ) try running locally without network connection - although I guess this is a bug unrelated to this pull request, as I get this on develop as well ...

**Comment by mtc2013** [comment]
@tansaku I get the failures when I turn off my network:
Failing Scenarios:
cucumber features/home_page/map.feature:21 # Scenario: Show all charities in map on homepage map
cucumber features/home_page/map.feature:27 # Scenario: Infowindow appears when clicking on map marker
cucumber features/home_page/map.feature:33 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:33 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:33 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:33 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:33 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:33 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:33 # Scenario: Organisation map has small icon for organisations updated more than 365 days ago
cucumber features/home_page/map.feature:48 # Scenario: Organisation map has small icon for organisation with no users
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:21 # Scenario: See a map of current volunteer opportunities
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:28 # Scenario: Volunteer opportunites are listed in map popups
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:28 # Scenario: Volunteer opportunites are listed in map popups
cucumber features/volunteer_opportunities/map_volunteer_opportunities.feature:38 # Scenario: See map when editing my volunteer opportunity


It seems that we're relying on google to actually respond for real ever since we started testing the map with our new setup rather than just scrapping json on the html.

**Comment by mtc2013** [comment]
We might look at something like VCR.  Thoughts @tansaku @marianmosley @johnnymo87 ?

**Comment by mtc2013** [comment]
@tansaku at any rate, this breakage without network doesn't have to do with the PR.  Should we continue to process this and open a ticket/chore to look into fixing the dependency?

**Comment by johnnymo87** [comment]
I agree that we should handle these failures as a separate chore. We probably just need to look at what's going on with webmock and update the redirects to our internal sinatra app.

**Comment by tansaku** [comment]
okay, I'm going to merge then and open a chore https://www.pivotaltracker.com/story/show/88585880

**Comment by tansaku** [comment]
@marianmosley @mtc2013 did this actually bring any new functionality - or is it just re-labelling in preparation of new functionality?

**Comment by mtc2013** [comment]
@tansaku Just a refactoring to realign the names to what the client wanted.

**Pull request merged**
